---
permalink: get-started/command-line-parameters.html 
sidebar: sidebar 
keywords: command line, parameters 
summary: 对于具有嵌入式Web服务的E2800和E5700控制器、SANtricity OS 11.40版本可以使用安全HTTPS协议在命令行上进行交互。这些控制器可以选择使用符号协议进行命令行交互。 
---
= 命令行参数
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== 11.40版本中的新命令行参数

对于具有嵌入式Web服务的E2800和E5700控制器、SANtricity OS 11.40版本可以使用安全HTTPS协议在命令行上进行交互。这些控制器可以选择使用符号协议进行命令行交互。符号协议是E2700和E5600控制器唯一支持的协议。为了保留现有脚本并最大限度地缩短过渡时间、CLI选项和语法会尽可能保留下来。但是、E2800和E5700控制器在安全性、身份验证、AutoSupport 和警报消息方面的功能存在一些差异、这些差异会使这些控制器的某些命令行界面语法变得过时。但是、在某些情况下、只有在使用新的https协议时、E2800或E5700上的语法才会过时。

对于仅适用于`* https*`客户端类型的新参数、它们同样仅适用于E2800或E5700控制器。

有关此版本中新增、已弃用和已废弃命令的列表、请参见 xref:changes-in-the-cli-and-script-commands-in-this-release.adoc[此版本中CLI和Script命令的更改]。

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`客户端类型`
 a| 
此参数用于强制创建适当的脚本引擎。将此可选参数与以下值之一结合使用：

* `*自动*`—自动执行设备发现以检测适当的脚本引擎类型。
* `* https*`—创建基于REST的脚本引擎。
* `*符号*`—创建基于符号的脚本引擎。




 a| 
`-u`
 a| 
请使用` username_`变量使用此参数。只有`* https*`客户端类型才需要此用户名。此参数不适用于`*符号*`客户端类型、将被静默忽略。

如果指定username参数、则会执行设备发现以确定正确的客户端类型(`* https*` vs.`*符号*`)。



 a| 
` P`
 a| 
此参数需要以下两个参数之一：

* `_password_file_s`—包含用于身份验证的密码。
* `-`(短划线)-从`stdin`中读取密码。


请注意、添加此参数适用于所有控制器、无论使用的是`* https *` client类型还是`* symbol*` client类型。



 a| 
` k`
 a| 
此可选参数允许`* https*`客户端在不安全模式下运行。这意味着不会验证存储阵列的证书。默认情况下、如果省略、则会执行正确的身份验证。此参数不适用于`*符号*`客户端类型、将被静默忽略。

|===


== 仅适用于E2700或E5600控制器的命令行参数

由于E2700和E5600控制器没有嵌入式警报管理功能、因此、这些命令行参数适用。这些参数不适用于E2800或E5700控制器。

[cols="2*"]
|===
| 参数 | 定义 


 a| 
` A`
 a| 
添加简单网络管理协议(Simple Network Management Protocol、SNMP)陷阱目标或电子邮件地址警报目标。

* 添加SNMP陷阱目标时、SNMP社区会自动定义为陷阱的社区名称、而`* host*`是应将陷阱发送到的系统的IP地址或域名服务器(Domain Name Server、DNS)主机名。
* 为警报目标添加电子邮件地址时、`*电子邮件地址*`是要将警报消息发送到的电子邮件地址。


[NOTE]
====
对于E2800和E5700存储阵列、此命令行选项已过时。使用RESTful API、SANtricity System Manager或curl命令。

====


 a| 
` m`
 a| 
指定发送电子邮件警报通知的电子邮件服务器的主机名或IP地址。

[NOTE]
====
对于E2800和E5700存储阵列、此命令行选项已过时。使用RESTful API、SANtricity System Manager或curl命令。

====


 a| 
`-s`(小写)
 a| 
显示与`-d`参数结合使用时配置文件中的警报设置。

[NOTE]
====
对于E2800和E5700存储阵列、此命令行选项已过时。使用RESTful API、SANtricity System Manager或curl命令。

====


 a| 
`-x`(小写)
 a| 
删除SNMP陷阱目标或电子邮件地址警报目标。` city_`是陷阱的SNMP社区名称、`主机_`是要将陷阱发送到的系统的IP地址或DNS主机名。

[NOTE]
====
对于E2800和E5700存储阵列、此命令行选项已过时。使用RESTful API、SANtricity System Manager或curl命令。

====
|===


== 命令行参数、适用于使用符号客户端类型运行的所有控制器

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`-R`(大写)
 a| 
定义密码的用户角色。这些角色可以是：

* `*管理*`—用户有权更改存储阵列配置。
* `*监控*`—用户有权查看存储阵列配置、但无法进行更改。


只有在与`*–p*`参数结合使用时、`*-R*`参数才有效、该参数用于指定您为存储阵列定义密码。

只有在存储阵列上启用了双密码功能时、才需要`*-R*`参数。在以下情况下、不需要`*-R*`参数：

* 存储阵列上未启用双密码功能。
* 只设置了一个管理员角色、而未为存储阵列设置监控角色。


|===


== 命令行参数适用于所有控制器和所有客户端类型

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`主机名或IP地址_`
 a| 
指定带内受管存储阵列或带外受管存储阵列的主机名或Internet协议(IP)地址(`_xxx.xxx.xxx.xxx.xxx.xxx.xxx _`)。

* 如果您要通过带内存储管理使用主机来管理存储阵列、则如果有多个存储阵列连接到主机、则必须使用`-n`参数或`-w`参数。
* 如果您要通过每个控制器上的以太网连接使用带外存储管理来管理存储阵列、则必须指定控制器的`主机名或IP地址_`。
* 如果您先前已在企业管理窗口中配置存储阵列、则可以使用`-n`参数按用户提供的名称指定存储阵列。
* 如果您之前在企业管理窗口中配置了存储阵列、则可以使用`-w`参数通过其全球通用标识符(WWID)指定该存储阵列。




 a| 
` A`
 a| 
将存储阵列添加到配置文件中。如果不使用`主机名或IP地址`的` a`参数、则自动发现会扫描本地子网中的存储阵列。



 a| 
`-c`
 a| 
指示您输入一个或多个脚本命令以在指定存储阵列上运行。使用分号(`；`)结束每个命令。您不能在同一命令行上放置多个`-c`参数。您可以在`-c`参数后包含多个脚本命令。



 a| 
` - d`
 a| 
显示了脚本配置文件的内容。文件内容采用以下格式：`_storage-system-name host-name1 host-name2_`



 a| 
`-e`
 a| 
运行命令时不首先执行语法检查。



 a| 
`-F`(大写)
 a| 
指定要从中发送所有警报的电子邮件地址。



 a| 
`-f`(小写)
 a| 
指定包含要在指定存储阵列上运行的脚本命令的文件名。`-f`参数与`-c`参数类似、因为这两个参数均用于运行脚本命令。`-c`参数可运行各个脚本命令。`-f`参数运行脚本命令文件。默认情况下、在文件中运行脚本命令时遇到的任何错误都将被忽略、并且文件将继续运行。要覆盖此行为、请在脚本文件中使用`set session errorAction=stop`命令。



 a| 
`-g`
 a| 
指定包含电子邮件发件人联系信息的ASCII文件、该信息将包含在所有电子邮件警报通知中。命令行界面假定ASCII文件仅为文本文件、没有分隔符或任何预期格式。如果存在`userdata.txt`文件、请勿使用`-g`参数。



 a| 
` h`
 a| 
指定运行存储阵列所连接的SNMP代理的主机名。使用`-h`参数和以下参数：

* ` A`
* `-x`




 a| 
`-i`(大写)
 a| 
指定要包含在电子邮件警报通知中的信息类型。您可以选择以下值：

* `eventOnly`—电子邮件仅包含事件信息。
* `profile`—电子邮件中包含事件和阵列配置文件信息。


您可以使用`-q`参数指定电子邮件传送频率。



 a| 
`-I`(小写)
 a| 
显示了已知存储阵列的IP地址。使用`-i`参数和`-d`参数。文件内容采用以下格式：`_storage-system-name IP-address1 ipaddress2_`



 a| 
`-n`
 a| 
指定要运行脚本命令的存储阵列的名称。使用`主机名或IP地址_`时、此名称是可选的。如果使用带内方法管理存储阵列、则在指定地址将多个存储阵列连接到主机时、必须使用`-n`参数。如果未使用`主机名或IP地址_`、则需要提供存储阵列名称。配置为在企业管理窗口中使用的存储阵列的名称(即、此名称列在配置文件中)不得与任何其他已配置存储阵列的名称重复。



 a| 
`-o`
 a| 
为运行脚本命令后生成的所有输出文本指定文件名。使用`-o`参数和以下参数：

* `-c`
* ` f`


如果不指定输出文件、则输出文本将转到标准输出(stdout)。不是脚本命令的命令的所有输出都会发送到stdout、而不管是否设置了此参数。



 a| 
` -p`
 a| 
定义要运行命令的存储阵列的密码。在以下情况下、不需要密码：

* 尚未在存储阵列上设置密码。
* 密码在您正在运行的脚本文件中指定。
* 您可以使用`-c`参数和以下命令指定密码：


[listing]
----
set session password=password
----


 a| 
` P`
 a| 
此参数需要以下两个参数之一：

* `_password_file_s`—包含用于身份验证的密码。
* `-`(短划线)-从`stdin`中读取密码。


请注意、添加此参数适用于所有控制器、无论使用的是`* https *` client类型还是`* symbol*` client类型。



 a| 
`-q`
 a| 
指定要接收事件通知的频率以及事件通知中返回的信息类型。对于每个严重事件、始终会生成一个电子邮件警报通知、其中至少包含基本事件信息。这些值对`-q`参数有效：

* `everyEvent`—信息随每个电子邮件警报通知一起返回。
* `2`—每两小时返回的信息不超过一次。
* `4`—每四小时返回的信息不超过一次。
* `8`—每八小时返回一次以上的信息。
* `12`—每12小时返回的信息不超过一次。
* `24`—每24小时返回的信息不超过一次。


使用`-I`参数、您可以指定电子邮件警报通知中的信息类型。

* 如果将`-i`参数设置为`eventOnly`、则`-q`参数的唯一有效值为`everyEvent`。
* 如果您将`-i`参数设置为`profile`值或`supportBundle`值、则此信息将随频率由`-q`参数指定的电子邮件一起提供。




 a| 
`-快速`
 a| 
减少运行单行操作所需的时间。例如、`recreate snapshot volume`命令就是单行操作的一个示例。此参数可在命令执行期间不运行后台进程、从而缩短时间。对于涉及多个单行操作的操作、请勿使用此参数。广泛使用此命令可能会使控制器的命令超出控制器可以处理的数量、从而导致操作失败。此外、通常从后台进程收集的状态更新和配置更新将不会提供给CLI。此参数会导致依赖后台信息的操作失败。



 a| 
`-S`(大写)
 a| 
禁止显示说明运行脚本命令时显示的命令进度的信息消息。(禁止信息性消息也称为静默模式。) 此参数可禁止显示以下消息：

* `正在执行语法检查`
* `s同步检查完成`
* `正在执行脚本`
* `s记录执行完成`
* `sMcli completed successfully`




 a| 
`-v`
 a| 
显示与`-d`参数结合使用时配置文件中已知设备的当前全局状态。



 a| 
`-w`
 a| 
指定存储阵列的WWID。此参数可替代`-n`参数。使用`-w`参数和`-d`参数显示已知存储阵列的WWID。文件内容采用以下格式：`_storage-system-name world-wide-ID ip-address1 ip-address2_`



 a| 
`-X`(大写)
 a| 
从配置中删除存储阵列。



 a| 
`-？`
 a| 
显示了有关CLI命令的使用情况信息。

|===