---
permalink: get-started/downloadable-smcli-parameters.html 
sidebar: sidebar 
keywords: downloadable, smcli, command line, parameters 
summary: 'SANtricity OS 11.60版支持直接通过SANtricity 系统管理器下载和安装基于http的命令行界面版本(也称为安全命令行界面或SMcli)。' 
---
= 可下载的SMcli命令行参数
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== 11.60及更高版本的可下载SMcli命令行参数

SANtricity OS 11.60版可以直接通过SANtricity 系统管理器下载和安装基于http的命令行界面版本(也称为"Secure CLI"或SMcli)。此可下载版本的SMcli可从EF600、EF300、E5700、EF570、E2800、 和EF280控制器。要在SANtricity 系统管理器中下载SMCLI、请选择*设置*>*系统*和*加载项*>*命令行界面*。


NOTE: 要运行命令行界面命令的管理系统必须具有Java Runtime Environment (JRE) 8及更高版本。

与先前版本的SMcli一样、可通过SANtricity 系统管理器下载的SMcli具有一组唯一的参数。有关在SANtricity OS 11.53及更早版本中使用命令行参数的信息、请参见 xref:./get-started/command-line-parameters.adoc[原有命令行参数]



=== 多因素身份验证

如果启用了SAML (安全断言标记语言)、则CLI只能使用访问令牌。如果未启用SAML、则可以使用用户名/密码或访问令牌。可以通过SANtricity 系统管理器生成访问令牌。

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`-t`
 a| 
定义用于通过存储阵列进行身份验证的访问令牌。访问令牌可替代用户名和密码。



 a| 
`-T` (大写)
 a| 
此参数需要以下两个参数之一：

* `access_token-file` —包含用于身份验证的访问令牌
* `-(dash)` —从stdin读取访问令牌




 a| 
`-u`
 a| 
将此参数与结合使用 `_username_` 变量。如果不使用访问令牌、则需要此参数。



 a| 
` -p`
 a| 
定义要运行命令的存储阵列的密码。在以下情况下、不需要密码：

* 尚未在存储阵列上设置密码。
* 密码在您正在运行的脚本文件中指定。




 a| 
`-P` (大写)
 a| 
此参数需要以下两个参数之一：

* `_password_file_s`—包含用于身份验证的密码。
* `-`(短划线)-从`stdin`中读取密码。


|===


=== 常规https模式命令行参数

可下载的SMcli仅支持https模式。以下是https模式常用的命令行参数。

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`主机名或IP地址_`
 a| 
指定主机名或Internet协议(IP)地址 (`_xxx.xxx.xxx.xxx_`)。

在通过每个控制器上的以太网连接管理带外存储管理时、必须指定 `_host-name-or-IP-address_` 控制器。



 a| 
` k`
 a| 
此可选参数允许 `*https*` 客户端以在不安全模式下运行。这意味着不会验证存储阵列的证书。默认情况下、如果省略、则会执行正确的验证。


NOTE: 有关管理存储阵列证书的追加信息 、请参见 <<storedcertificates,管理存储的证书命令行参数>>。



 a| 
`-e`
 a| 
运行命令时不首先执行语法检查。



 a| 
`-L` (大写)
 a| 
显示可下载SMcli的法律声明。



 a| 
`-n`
 a| 
指定要运行脚本命令的本地存储标签。使用时、此选项为可选 `_host-name-or-IP-address_`。如果需要、则需要本地存储的标签 `_host-name-or-IP-address_` 未使用。


NOTE: 有关使用本地存储的标签管理存储阵列的追加信息 、请参见 <<managearrays,管理存储的阵列命令行参数>>。



 a| 
`-o`
 a| 
为运行脚本命令后生成的所有输出文本指定文件名。使用`-o`参数和以下参数：

* `-c`
* ` f`


如果不指定输出文件、则输出文本将转到标准输出  `stdout`）。所有来自非脚本命令的命令的输出都将发送到 `stdout`、而不管是否设置此参数。



 a| 
`-S`(大写)
 a| 
禁止显示说明运行脚本命令时显示的命令进度的信息消息。(禁止信息性消息也称为静默模式。) 此参数可禁止显示以下消息：

* `正在执行语法检查`
* `s同步检查完成`
* `正在执行脚本`
* `s记录执行完成`
* `sMcli completed successfully`




 a| 
`-version`
 a| 
显示可下载的SMcli版本



 a| 
`-？`
 a| 
显示了有关CLI命令的使用情况信息。

|===


=== 管理存储的阵列

您可以使用以下命令行参数通过本地存储的标签管理存储的阵列。


NOTE: 本地存储的标签可能与SANtricity 系统管理器下显示的实际存储阵列名称不匹配。

[cols="2*"]
|===
| 参数 | 定义 


 a| 
`SMcli storageArrayLabel show all`
 a| 
显示所有本地存储的标签及其关联地址



 a| 
`SMcli storageArrayLabel show label <LABEL>`
 a| 
显示与名为的本地存储标签关联的地址 `<LABEL>`



 a| 
`SMcli storageArrayLabel delete all`
 a| 
删除所有本地存储的标签



 a| 
`SMcli storageArrayLabel delete label <LABEL>`
 a| 
删除本地存储的名为的标签 `<LABEL>`



 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] storageArrayLabel add label <LABEL>`
 a| 
* 添加本地存储的标签并添加名称 `<LABEL>` 包含提供的地址
* 不直接支持更新。要更新、请删除标签、然后重新添加。



NOTE: 添加本地存储的标签时、SMcli不会与存储阵列联系。

|===
[cols="2*"]
|===
| 参数 | 定义 


 a| 
`SMcli localCertificate show all`
 a| 
显示本地存储的所有受信任证书



 a| 
`SMcli localCertificate show alias <ALIAS>`
 a| 
显示具有别名的本地存储的受信任证书 `<ALIAS>`



 a| 
`SMcli localCertificate delete all`
 a| 
删除本地存储的所有受信任证书



 a| 
`SMcli localCertificate delete alias <ALIAS>`
 a| 
删除本地存储的具有别名的受信任证书 `<ALIAS>`



 a| 
`SMcli localCertificate trust file <CERT_FILE> alias <ALIAS>`
 a| 
* 使用别名保存要信任的证书 `<ALIAS>`
* 要信任的证书将通过单独的操作(例如使用Web浏览器)从控制器下载




 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] localCertificate trust`
 a| 
* 连接到每个地址并将返回的证书保存到可信证书存储中
* 指定的主机名或IP地址将用作以这种方式保存的每个证书的别名
* 在运行此命令之前、用户应验证控制器上的证书是否可信
* 为了获得最高安全性、应使用用于生成文件的信任命令来确保证书在用户验证和运行此命令之间不会发生更改


|===