---
permalink: get-started/learn-about-volume-group-migration.html 
sidebar: sidebar 
keywords: volume, group, migration, learn, data, access, export, import, component 
summary: 通过卷组迁移、您可以导出卷组、以便将卷组导入到其他存储阵列。您还可以导出卷组、以便脱机存储数据。 
---
= 了解卷组迁移
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过卷组迁移、您可以导出卷组、以便将卷组导入到其他存储阵列。您还可以导出卷组、以便脱机存储数据。

[CAUTION]
====
如果卷组包含支持NVMe或FIPS的驱动器、则需要从源阵列记录/保存安全密钥和密码短语、以便在开始迁移到目标阵列之前解除驱动器的锁定。如果安全密钥和密码短语未知且/或不需要数据完整性、则可以执行安全擦除。E系列存储系统不支持混用不同的加密安全驱动器。有关如何使用安全密钥解锁驱动器、擦除FIPS驱动器以及解锁或重置已锁定NVMe驱动器的详细信息、请参见SANtricity 系统管理器的联机帮助。

====
[NOTE]
====
*可能丢失数据访问*-在移动卷组或导入卷组之前、必须导出卷组。

====


== 导出卷组

导出卷组操作会准备要删除的卷组中的驱动器。您可以删除驱动器以进行脱机存储、也可以将卷组导入到其他存储阵列。完成导出卷组操作后、所有驱动器均已脱机。任何关联的卷或可用容量节点将不再显示在存储管理软件中。



== 不可导出的组件

您必须先删除任何不可导出的组件、然后才能完成导出卷组操作步骤。您必须删除以下组件：

* 持久预留
* 映射
* 卷副本对
* 远程镜像对
* 镜像存储库




== 卷组的基本导出步骤

导出卷组包括在_source"存储阵列上执行的这些步骤。

. 保存存储阵列配置。
. 停止所有 I/O
. 备份卷组中卷上的数据。
. 卸载或断开卷组中卷上的文件系统。
. 找到卷组、并使用卷组中的源和目标存储阵列名称、卷组名称以及驱动器总数为驱动器贴上标签。
. 使卷组脱机。
. 要保持托盘中的通风良好、请获取空驱动器箱或新驱动器、以便您可以在卸下与导出的卷组关联的驱动器后更换这些驱动器。


导出卷组包括_target_存储阵列上的以下步骤。

. 确保目标存储阵列具有可用的驱动器插槽。
. 确保目标存储阵列支持要导入的驱动器。
. 确保目标存储阵列可以支持新卷。
. 确保控制器上安装了最新版本的固件。
. 如果要导出RAID级别6卷组、请确保目标存储阵列支持RAID级别6。
. 确保目标存储阵列上安装了最新版本的存储管理软件。
. 如果要导出启用了驱动器安全的卷组、请确保目标存储阵列上已启用驱动器安全。




== 导入卷组

导入卷组操作会将导入的卷组添加到目标存储阵列。完成导入卷组操作后、所有驱动器均处于最佳状态。现在、任何关联的卷或可用容量节点都会显示在目标存储阵列上安装的存储管理软件中。



== 卷组的基本导入步骤

[NOTE]
====
必须先将卷组中的所有驱动器插入托盘、然后才能导入卷组。

====
在_target_存储阵列上导入卷组包括以下步骤：

. 将导出的驱动器插入可用的驱动器插槽。
. 查看导入报告、了解要导入的卷组的概况。
. 检查是否存在不可导入的组件。
. 确认您要继续导入操作步骤。




== 不可导入的组件

某些组件无法在导入卷组操作步骤 期间导入。这些组件将在操作步骤 期间删除：

* 持久预留
* 映射
* 卷副本对
* 远程镜像对
* 镜像存储库

