---
permalink: get-started/new-https-mode.html 
sidebar: sidebar 
keywords: new, smcli, https mode 
summary: 新的SMcli可以在https模式下运行、从而提供更多安全功能。 
---
= 了解 https 模式下的 SANtricity Secure CLI (SMcli)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMcli可以在`* https*`模式下运行、从而提供额外的安全功能。

[NOTE]
====
如果您当前使用的是SANtricity 11.52或更早版本、则无法通过原有命令行界面升级到最新版本的SANtricity。从SANtricity 11.52升级到更高版本只能通过SMcli执行。

====
使用11.42版本的CLI时、将在以下模式之一中创建脚本引擎：

* `* https*`—创建了一个基于REST的脚本引擎、并提供了其他安全功能。
* `*符号*`-创建基于符号的脚本引擎。


在`* https *` client中提供了新的安全功能：

* 要实现高级安全性、需要使用可信证书进行证书身份验证。您可以使用`-k`选项使用自签名证书并在不安全模式下运行命令。
* 您可以使用基于角色的访问管理、并为不同角色分配不同的安全权限。使用`-u`选项使用用户名参数运行命令。
* 先前在`*符号*`模式下提供的密码参数也可以在`* https *`模式下使用、用于为特定用户角色指定密码。`-p`选项用于在命令行上指定密码、或者`-P`选项可以从文件或`stdin`中读取密码。


本主题中有几个示例有助于说明新的命令行参数：



== 需要密码的操作、 `https` 客户端模式下、受信任证书安装在阵列上

在以下示例中、提供了用户名和密码选项、并在阵列上安装了可信证书。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1 -u admin@local -p adminPassword -c "set storageArray cacheBlockSize=4;"

Syntax check complete.

Executing script...

Script execution complete.

SMcli completed successfully.
----


== 需要密码的操作、 `https` 客户端模式下、阵列上未安装可信证书

在以下示例中、提供了用户名和密码选项、但阵列上未安装可信证书、并且未使用`-k`选项。此示例显示了返回的输出。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1 -u admin@local -p adminPassword -c "set storageArray cacheBlockSize=4;"

Unable to establish a secure connection to the storage array as we were unable to confirm the connection is secure.
Please configure the storage array to use a trusted security certificate. If the problem persists, contact Technical Support.

SMcli failed.
----


== 需要密码的操作、 `https` 客户端模式、未安装可信证书、但对自签名证书使用-k

在以下示例中、与前面的示例一样、提供了用户名和密码选项、但阵列上未安装可信证书。但是、在这种情况下、会使用`-k`选项来使用自签名证书。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1 -u admin@local -p adminPassword -c "set storageArray cacheBlockSize=4;" -k
Performing syntax check...

Syntax check complete.

Executing script...

Script execution complete.
----
在此示例中、使用`*符号*`客户端模式时、要成功完成此命令、只需输入密码选项即可。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1 -p adminPassword -c "set storageArray cacheBlockSize=4;"
Performing syntax check...

Syntax check complete.

Executing script...

Script execution complete.

SMcli completed successfully.
----


== 只读操作、 `symbol` 客户端模式

在此示例中、在`*符号*`客户端模式下、不提供用户名或密码。此操作仅针对只读操作成功完成。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1  -c "show allVolumes;"
Performing syntax check...

Syntax check complete.

Executing script...

STANDARD/THIN VOLUMES------------------------------

   Number of volumes: 0
Missing Volumes

   Number of missing volumes: 0


Script execution complete.

SMcli completed successfully.
----


== 只读操作、http客户端模式

在以下示例中、也可以使用只读操作、但在`* https *`客户端模式下、需要提供用户名和密码以及`-k`来接受自签名证书。`* https*`客户端模式需要密码、即使只读操作也是如此。

[listing]
----
C:\Program Files\StorageManager\client>SMcli -n Array1 -u admin@local -p adminPassword -c "show allVolumes;" -k
Performing syntax check...

Syntax check complete.

Executing script...

THICK/THIN VOLUMES------------------------------

   Number of volumes: 0
Missing Volumes

   Number of missing volumes: 0


Script execution complete.

SMcli completed successfully.
----