---
permalink: get-started/synopsis-of-the-script-commands.html 
sidebar: sidebar 
keywords: synopsis, script commands 
summary: '由于您可以使用脚本命令定义和管理存储阵列的不同方面(例如主机拓扑、驱动器配置、控制器配置、卷定义和卷组定义)、因此实际命令数量非常庞大。' 
---
= 脚本命令摘要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由于您可以使用脚本命令定义和管理存储阵列的不同方面(例如主机拓扑、驱动器配置、控制器配置、卷定义和卷组定义)、因此实际命令数量非常庞大。

这些命令分为常规类别、在您应用这些命令来配置或维护存储阵列时、这些命令会重复使用。下表列出了脚本命令的常规形式以及每个命令的定义。

[cols="2*"]
|===
| 语法 | Description 


 a| 
[listing]
----
accept object
{statement-data}
---- a| 
执行待定操作。



 a| 
[listing]
----
activate object
{statement-data}
---- a| 
设置环境、以便在已正确设置环境的情况下执行操作或执行操作。



 a| 
[listing]
----
autoConfigure storageArray
{statement-data}
---- a| 
根据命令中指定的参数自动创建配置。



 a| 
[listing]
----
check object
{statement-data}
---- a| 
启动一个操作以报告对象中的错误、这是一个同步操作。



 a| 
[listing]
----
clear object
{statement-data}
---- a| 
丢弃对象某些属性的内容。此操作具有破坏性、无法反转。



 a| 
[listing]
----
create object
{statement-data}
---- a| 
创建指定类型的对象。



 a| 
[listing]
----
deactivate object
{statement-data}
---- a| 
删除操作的环境。



 a| 
[listing]
----
delete object
---- a| 
删除先前创建的对象。



 a| 
[listing]
----
diagnose object
{statement-data}
---- a| 
运行测试并显示结果。



 a| 
[listing]
----
disable object {statement-data}
---- a| 
阻止功能运行。



 a| 
[listing]
----
download object
{statement-data}
---- a| 
将数据传输到存储阵列或与存储阵列关联的硬件。



 a| 
[listing]
----
enable object
{statement-data}
---- a| 
设置要运行的功能。



 a| 
[listing]
----
load object
{statement-data}
---- a| 
将数据传输到存储阵列或与存储阵列关联的硬件。此命令在功能上类似于`download`命令。



 a| 
[listing]
----
recopy object
{statement-data}
---- a| 
使用现有卷副本对重新启动卷复制操作。您可以在重新启动操作之前更改这些参数。



 a| 
[listing]
----
recover object
{statement-data}
---- a| 
使用已保存的配置数据和语句参数重新创建对象。(此命令类似于`create`命令。)



 a| 
[listing]
----
remove object
{statement-data}
---- a| 
删除对象之间的关系。



 a| 
[listing]
----
repair object
{statement-data}
---- a| 
修复通过`check`命令发现的错误。



 a| 
[listing]
----
replace object
{statement-data}
---- a| 
指定对象将替换存储阵列中的现有对象。



 a| 
[listing]
----
reset object
{statement-data}
---- a| 
将硬件或对象返回到初始状态。



 a| 
[listing]
----
resume object
---- a| 
启动暂停的操作。此操作将从暂停时停止的位置开始。



 a| 
[listing]
----
revive object
---- a| 
强制对象从故障状态变为最佳状态。请仅将此命令用作错误恢复操作步骤 的一部分。



 a| 
[listing]
----
save object
{statement-data}
---- a| 
将有关对象的信息写入文件。



 a| 
[listing]
----
set object
{statement-data}
---- a| 
更改对象属性。命令返回后、所有更改都将完成。



 a| 
[listing]
----
show object
{statement-data}
---- a| 
显示有关对象的信息。



 a| 
[listing]
----
start object
{statement-data}
---- a| 
启动异步操作。您可以在某些操作启动后停止这些操作。您可以查询某些操作的进度。



 a| 
[listing]
----
stop object
{statement-data}
---- a| 
停止异步操作。



 a| 
[listing]
----
suspend object
{statement-data}
---- a| 
停止操作。然后、您可以重新启动已暂停的操作、该操作将从其暂停的位置继续进行。



 a| 
[listing]
----
validate object
{statement-data}
---- a| 
验证安全密钥。

|===