---
permalink: commands-a-z/add-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: add volume, asynchronous, mirror group, supported arrays, roles, context, syntax, parameter, minimum firmware level 
summary: add volume asyncMirrorGroup命令可将主卷添加到异步镜像组。 
---
= 将卷添加到异步镜像组
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`add volume asyncMirrorGroup`命令可将主卷添加到异步镜像组。



== 支持的阵列

此命令会对任何单个存储阵列执行适用场景 操作、但有一些限制。如果您在E2700或E5600阵列上运行命令、则没有任何限制。

[NOTE]
====
如果在E2800、E5700、EF600或EF300阵列上运行命令、则客户端类型必须设置为 `symbol`。如果客户端类型设置为、则不会执行此命令 `https`。

====


== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

此命令仅在包含要添加主卷的异步镜像组的本地存储阵列上有效。异步镜像组具有一个存储库卷、用于保存异步镜像组中所有时间点映像的数据。异步镜像组中的每个主卷在远程存储阵列上都有一个相应的镜像卷。



== 语法

[listing, subs="+macros"]
----
pass:quotes[add volume="_volumeName_" asyncMirrorGroup="_asyncMirrorGroupName_"
remotePassword="_password_"
(repositoryVolume="repos_xxxx" |
repositoryVolume=(_volumeGroupName_ ]pass:quotes[[capacity=_capacityValue_])]
repositoryVolume=pass:quotes[(_diskPoolName_] pass:quotes[[capacity=_capacityValue_]))
----


== 参数

|===
| 参数 | Description 


 a| 
`卷`
 a| 
要添加到异步镜像组的主卷的名称。将卷名称用双引号("")括起来。



 a| 
`asyncMirrorGroup`
 a| 
要添加的主卷所在的异步镜像组的名称。将异步镜像组名称用双引号("")括起来。



 a| 
`remotePassword`
 a| 
此参数是可选的。如果远程存储阵列受密码保护、请使用此参数。请将密码用双引号("")括起来。



 a| 
`repositoryVolume`
 a| 
要包含主卷中更改的数据的存储库卷的名称。

您可以通过两个选项来定义存储库卷的名称：

* 使用现有存储库卷：name。
* 运行此命令时、请创建一个新的存储库卷。


现有存储库卷的名称由两部分组成：

* 术语repos.
* 存储管理软件分配给存储库卷名称的四位数字标识符。


将现有存储库卷的名称用双引号("")括起来。

如果要在运行此命令时创建新的存储库卷、则必须输入要在其中创建存储库卷的卷组或磁盘池的名称。您也可以选择定义存储库卷的容量。如果要定义容量、可以使用以下值：

* 一个整数值、表示基本卷容量的百分比。
* 一个小数值、表示基本卷容量的百分比。
* 存储库卷的特定大小。大小的单位为`bytes`、`KB`、`MB`、`GB`或`TB`。


如果不定义容量、则存储管理软件会将容量设置为主卷容量的20%。

存储管理软件将创建存储库卷并将存储库卷链接到主卷。

|===


== 注释：

* 必须在要用于镜像活动的本地和远程存储阵列上启用和激活异步镜像功能。
* 本地和远程存储阵列必须通过正确的光纤通道网络结构或iSCSI接口进行连接。
* 远程存储阵列中的卷容量必须大于或等于本地存储阵列上主卷的容量。远程存储阵列上的卷将用作镜像卷。




== 最低固件级别

7.84.接受采取后续行动

11.80增加了EF600和EF300阵列支持
