---
permalink: commands-a-z/check-volume-parity.html 
sidebar: sidebar 
keywords: check, volume, parity 
summary: check volume parity命令会检查卷的奇偶校验和介质错误、然后将检查结果写入文件。 
---
= 检查卷奇偶校验
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`check volume parity`命令可检查卷的奇偶校验和介质错误、然后将检查结果写入文件。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[listing, subs="+macros"]
----
check volume pass:quotes[[_volumeName_]] parity
[parityErrorFile=pass:quotes[_filename_]]
[mediaErrorFile=pass:quotes[_filename_]]
[priority=(highest | high | medium | low | lowest)]
[startingLBA=pass:quotes[_LBAvalue_]]
[endingLBA=pass:quotes[_LBAvalue_]]
[verbose=(TRUE | FALSE)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`卷`
 a| 
要检查奇偶校验的特定卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或仅包含数字、则必须将标识符用双引号("")括在方括号内。



 a| 
`参数错误文件`
 a| 
要将奇偶校验错误信息保存到的文件路径和文件名。将文件名用双引号("")括起来。例如：

`file="C：\Program Files\cli\logs\parerr.txt`

此命令不会自动向保存的文件附加文件扩展名。输入文件名时、必须指定文件扩展名。



 a| 
`mediaErrorFile`
 a| 
要将介质错误信息保存到的文件路径和文件名。将文件名用双引号("")括起来。例如：

`file="C：\Program Files\cli\logs\mederr.txt`

此命令不会自动向保存的文件附加文件扩展名。输入文件名时、必须指定文件扩展名。



 a| 
`优先级`
 a| 
奇偶校验检查相对于主机I/O活动的优先级。有效值为`最高`、`高`、`m中`、`低`或`最低`。最低优先级比率有利于系统性能、但奇偶校验检查所需时间较长。最高优先级比率有利于奇偶校验检查、但系统性能可能会受到影响。



 a| 
`sTartingLBA`
 a| 
起始逻辑块地址。



 a| 
`endingLBA`
 a| 
结束逻辑块地址。



 a| 
`verbose`
 a| 
用于捕获进度详细信息(例如完成百分比)以及在扫描卷奇偶校验时显示信息的设置。要捕获进度详细信息、请将此参数设置为`true`。要防止捕获进度详细信息、请将此参数设置为`false`。

|===


== 注释：

对于非常大的单卷LUN或命名空间、起始逻辑块地址和结束逻辑块地址非常有用。在非常大的单个卷LUN或命名空间上运行卷奇偶校验检查可能需要很长时间。通过定义数据块的起始地址和结束地址、您可以缩短完成卷奇偶校验检查所需的时间。
