---
permalink: commands-a-z/clear-asyncmirrorfault.html 
sidebar: sidebar 
keywords: clear, asynchronous mirroring, fault 
summary: 'clear asyncMirrorFault命令可从一个或多个异步镜像组以及一个或多个异步镜像组成员卷清除异步镜像"粘性"故障。' 
---
= 清除异步镜像故障
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`clear asyncMirrorFault`命令可从一个或多个异步镜像组以及一个或多个异步镜像组成员卷清除异步镜像"粘滞"故障。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

异步镜像组及其成员卷可能会遇到异步镜像"粘滞"故障、此故障发生在一个时间点、但不会影响镜像的功能。必须检查此类故障、但可能不需要对配置进行任何更改。

异步镜像组及其成员卷可能存在或可能存在多个关联的粘滞故障。此命令将清除与异步镜像组及其成员卷关联的所有故障。但是、如果异步镜像组出现故障、而其某个成员卷出现故障、则清除异步镜像组上的故障不会清除其成员卷上的故障。



== 语法

[source, cli, subs="+macros"]
----
clear asyncMirrorFault(all |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_"asyncMirrorGroupName1"
... "asyncMirrorGroupNameN"_]] |
volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]])
----


== 参数

|===
| 参数 | Description 


 a| 
`全部`
 a| 
如果要清除所有异步镜像组以及所有异步镜像组成员卷上的所有异步镜像故障、请使用此参数。



 a| 
`asyncMirrorGroup`
 a| 
要从中清除异步镜像故障的异步镜像组的名称。将异步镜像组名称用方括号([])括起来。如果异步镜像组名称包含特殊字符或仅包含数字、则必须将名称用双引号("")括在方括号内。



 a| 
`asyncMirrorGroups`
 a| 
要从中清除异步镜像故障的多个异步镜像组的名称。使用以下规则输入异步镜像组的名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`卷`
 a| 
要从中清除异步镜像故障的特定成员卷(异步镜像组中)的名称。将成员卷名称用方括号([])括起来。如果卷名称包含特殊字符或仅包含数字、则必须将名称用双引号("")括在方括号内。



 a| 
`卷`
 a| 
要从中清除异步镜像故障的多个成员卷(异步镜像组中)的名称。使用以下规则输入成员卷的名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。


|===


== 最低固件级别

7.84.接受采取后续行动

11.80增加了EF600和EF300阵列支持
