---
permalink: commands-a-z/clear-storagearray-configuration.html 
sidebar: sidebar 
keywords: clear, storage array, configuration 
summary: clear storageArray configuration命令可清除整个存储阵列配置或部分存储阵列配置、或者仅清除卷组和卷配置。 
---
= 清除存储阵列配置
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`clear storageArray configuration`命令可清除整个存储阵列配置或部分存储阵列配置、或者仅清除卷组和卷配置。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

使用此命令执行以下操作之一：

* 清除整个存储阵列配置、并将其恢复到初始安装状态。
* 清除配置、但安全信息和标识信息除外。
* 仅清除卷组配置信息和卷配置信息。


[NOTE]
====
*可能会损坏存储阵列配置*-运行此命令后、现有存储阵列配置将被删除。

====


== 语法

[listing]
----
clear storageArray configuration (all | volumeGroups)
----
[listing]
----
clear storageArray configuration factoryReset
----


== Parameters

|===
| 参数 | Description 


 a| 
无
 a| 
如果不输入参数、则此命令将删除存储阵列的所有配置信息、但与安全性和标识相关的信息除外。



 a| 
`全部`
 a| 
用于删除存储阵列的整个配置的设置、包括安全信息和标识信息。删除所有配置信息将使存储阵列返回到其初始状态。



 a| 
`卷组`
 a| 
用于删除卷配置和卷组配置的设置。其余配置将保持不变。



 a| 
`factoryReset`
 a| 
此设置会删除存储阵列的整个配置(与`All`参数的功能相同)、但也会重置控制器中存储的网络配置和任何密码信息。



 a| 
`supportReset`
 a| 
[NOTE]
====
此命令仅供技术支持使用。

====
此设置的行为类似于`factoryReset`参数、但也会清除所有捆绑包密钥。

|===


== 注释：

使用此命令、您可以通过多种不同方式清除存储阵列的配置。清除卷组的存储阵列后、恢复模式将自动启动。在恢复模式下、板载(缓存)备份(如果平台上存在)会保留下来。当存储阵列处于恢复模式时、您可以选择从基于主机的备份文件或板载(缓存)备份之一还原存储阵列配置。

此命令还会重置存储阵列标识符。通过密钥文件启用的任何高级功能均会失效、必须创建并应用新的高级功能密钥。请联系技术支持。

运行此命令时、存储阵列将无响应、并且所有脚本处理都将取消。要恢复与主机的通信、必须删除并重新添加存储阵列。要删除无响应的存储阵列、请使用以下smcli wrapper命令：

[listing, subs="+macros"]
----
SMcli -X -n pass:quotes[_storageArrayName_]
----
`X`是唯一的SMcli终端、必须为大写。

要重新添加存储阵列、请使用以下smcli wrapper命令：

[listing, subs="+macros"]
----
SMcli -A -n pass:quotes[_storageArrayName_]
----
`a`是唯一的SMcli终端、必须为大写。



== 最低固件级别

7.10添加了以下参数：

* `全部`
* `卷组`


7.83增加了恢复模式功能。

11.41添加了以下参数：

* `factoryReset`
* `supportReset`

