---
permalink: commands-a-z/create-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency, group 
summary: create ConsistencyGroup命令将创建一个新的空一致性组、该一致性组可以包含快照组。您必须使用set ConsistencyGroup addCGMember命令添加快照组。 
---
= 创建一致性组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`create ConsistencyGroup`命令可创建一个新的空一致性组、该一致性组可以包含快照组。您必须使用`set ConsistencyGroup addCGMember`命令添加快照组。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
create consistencyGroup userLabel=pass:quotes[_"consistencyGroupName"_]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapSchedule_])]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`用户标签`
 a| 
要创建的新一致性组的名称。将新一致性组名称用双引号("")括起来。



 a| 
`repositoryFullPolicy`
 a| 
希望在快照存储库卷已满时继续执行快照处理的方式。您可以选择对基础卷的写入失败(`failBaseWrites`)或删除(清除)快照映像(`purgeSnapImages`)。默认操作为`purgeSnapImages`。



 a| 
`repositoryFullLimit`
 a| 
收到快照存储库卷接近全满警告时存储库容量的百分比。使用整数值。例如、值70表示70%。默认值为75。



 a| 
`autodeleteLimit`
 a| 
可以将每个快照组配置为自动删除其快照映像、以使快照组中的快照映像总数保持在指定级别或以下。启用此选项后、每当在快照组中创建新的快照映像时、系统都会自动删除组中最早的快照映像、以符合限制值。此操作可释放存储库容量、以便用于满足其余Snapshot映像的持续写入时复制要求。



 a| 
`enableSchedule`
 a| 
计划快照操作的功能是打开还是关闭。要启用快照计划、请将此参数设置为`true`。要关闭快照计划、请将此参数设置为`false`。



 a| 
`rollBackPriority`
 a| 
确定是否应将系统资源分配给回滚操作而牺牲系统性能。值`high`表示回滚操作的优先级高于所有其他主机I/O值`low`表示执行回滚操作时、应尽可能减少对主机I/O的影响

|===


== 注释：

一致性组是一个逻辑实体、可用于批量管理添加到集合中的所有快照映像。一致性组是指对其快照映像具有共同一致性要求或依赖关系的快照组的集合。您为此集合创建和使用的任何快照映像都必须根据一致性依赖关系进行管理。

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

一致性组中的快照映像可以根据一致性组中是否存在快照映像来推断。一致性组中的所有Snapshot映像都共享一个通用时间戳和序列号。

对快照映像一致性组执行的操作将被视为一个请求、它会导致在创建快照映像之前、对每个成员的关联基础卷执行的所有待定I/O操作均被清空并暂停。如果无法成功为所有一致性组成员创建快照映像、则此操作将失败且不会产生任何影响(即、不会创建新的快照映像)。

根据此行为、一致性组的所有成员通常具有相同数量的快照映像。但是、在将新成员添加到一致性组中时、该新成员缺少先前在一致性组的已建立成员上创建的快照映像。缺少快照映像不会被视为错误情况。如果此后请求删除或回滚仅存在于一致性组的一部分成员上的快照映像、则只会影响实际存在指定快照映像的成员。



== 自动删除

您可以将每个快照组配置为自动删除其快照映像、以使快照组中的快照映像总数保持在或低于最大映像数。如果快照组中的快照映像数达到最大限制、则每当在快照组中创建新的快照映像时、`autodeleteLimit`参数都会自动删除快照映像。`autodeleteLimit`参数将删除快照组中最早的快照映像、直到达到使用参数定义的最大映像数为止。这样就可以释放存储库容量、以便可以使用它来满足其余Snapshot映像的持续写时复制要求。



== 计划一致性组中的快照映像

使用`enableSchedule`参数和`sschedule`参数可以计划快照。使用这些参数、您可以计划每日、每周或每月(按天或日期)创建快照。`enableSchedule`参数用于启用或禁用快照计划功能。启用计划时、您可以使用`schedule`参数来定义快照的发生时间。

下表说明了如何使用`schedule`参数的选项：

|===
| 参数 | Description 


 a| 
`s计划`
 a| 
用于指定计划参数。



 a| 
`即时`
 a| 
立即启动操作。此项与任何其他计划参数不能共存。



 a| 
`enableSchedule`
 a| 
如果设置为`true`、则会启用计划。如果设置为`false`、则计划将关闭。

[NOTE]
====
默认值为 `false` 。

====


 a| 
`sTartDate`
 a| 
启动操作的特定日期。输入日期的格式为MM：DD：YY。默认值为当前日期。例如、此选项为`startDate=06：27：11`。



 a| 
`scheduleDay`
 a| 
要启动操作的一周中的某一天。可以是以下全部或一个或多个值：

* `m每日`
* `星期二`
* `星期三`
* `星期四`
* `星期五`
* `saturday`
* `sUnday`


[NOTE]
====
将值括在圆括号中。例如、`scheduleDay=(星期三)`。

====
可以通过将天数括在一组圆括号中并使用空格分隔来指定一天以上。例如、`scheduleDay=(星期一星期三星期五)`。

[NOTE]
====
此参数与每月计划不兼容。

====


 a| 
`sTartTime`
 a| 
一天中启动操作的时间。输入时间的格式为HH：mm、其中HH是小时、MM是小时后的分钟。使用24小时制时钟。例如、下午2：00为14：00。此选项的一个示例是`startTime=14：27`。



 a| 
`scheduleInterval`
 a| 
两次操作之间的最短时间(以分钟为单位)。计划间隔不应超过1440 (24小时)、并且应为30的倍数。

此选项的一个示例是``scheduleInterval=180``。



 a| 
`endDate`
 a| 
停止操作的特定日期。输入日期的格式为MM：DD：YY。如果不需要结束日期、可以指定`noEndDate`。例如、此选项为`endDate=11：26：11`。



 a| 
`TimesPerDay`
 a| 
一天中执行此操作的次数。此选项的一个示例是`timesPerDae=4`。



 a| 
`时区`
 a| 
指定计划要使用的时区。可以通过两种方式指定：

* * GMT±HH：MM*
+
与GMT的时区偏移。示例：`timezone=GMT-06：00`。

* *文本字符串*
+
标准时区文本字符串必须用引号括起来。示例：``timezone="America/Chicago"``





 a| 
`s计划日期`
 a| 
要执行此操作的月份中的某一天。这些天数的值为数字值、范围为1-31。

[NOTE]
====
此参数与每周计划不兼容。

====
例如、`scheduleDate`选项为`scheduleDate=("15")`。



 a| 
`mon th`
 a| 
要执行此操作的特定月份。月份的值为：

* `JAN` 1月
* `feb`—2月
* `mar`- 3月
* `4月` 4月
* `may`- 5月
* `jun`—6月
* `Jul`- Jul
* `8月` 8月
* `sEP`—9月
* `oct`—10月
* `11月`—11月
* `dEC`—12月


[NOTE]
====
将值括在圆括号中。例如、`month=(JAN)`。

====
可以指定多个月、方法是将月份括在一组圆括号中、并使用空格分隔每个月。例如、`month=(Jul Jul decd)`。

将此参数与`scheduleDate`参数结合使用、可在一个月的特定日期执行此操作。

[NOTE]
====
此参数与每周计划不兼容。

====
|===
下表说明了如何使用`timezone`参数：

|===
| 时区名称 | GMT偏移 


 a| 
`etc/GMT+12`
 a| 
`GMT-12：00`



 a| 
`etc/GMT+11`
 a| 
`GMT-11：00`



 a| 
`太平洋/火鲁鲁鲁`
 a| 
`GMT-10：00`



 a| 
`美洲/安克雷奇`
 a| 
`GMT-09：00`



 a| 
`America/Santa_ISA贝尔`
 a| 
`GMT-08：00`



 a| 
`美洲/洛杉矶`
 a| 
`GMT-08：00`



 a| 
`美洲/凤凰城`
 a| 
`GMT-07：00`



 a| 
`美洲/奇瓦华`
 a| 
`GMT-07：00`



 a| 
`美洲/丹佛`
 a| 
`GMT-07：00`



 a| 
`美洲/危地马拉`
 a| 
`GMT-06：00`



 a| 
`美洲/芝加哥`
 a| 
`GMT-06：00`



 a| 
`美洲/墨西哥_城市`
 a| 
`GMT-06：00`



 a| 
`美洲/里贾纳`
 a| 
`GMT-06：00`



 a| 
`美洲/波哥大`
 a| 
`GMT-05：00`



 a| 
`美洲/纽约`
 a| 
`GMT-05：00`



 a| 
`etc/GMT+5`
 a| 
`GMT-05：00`



 a| 
`美洲/ Caracas`
 a| 
`GMT-04：30`



 a| 
`美洲/亚松森`
 a| 
`GMT-04：00`



 a| 
`美洲/哈利法克斯`
 a| 
`GMT-04：00`



 a| 
`美洲/Cuiaba`
 a| 
`GMT-04：00`



 a| 
`America/La_Paz`
 a| 
`GMT-04：00`



 a| 
`美洲/圣地亚哥`
 a| 
`GMT-04：00`



 a| 
`America/St_Johns`
 a| 
`GMT-03：30`



 a| 
`America/Sao_圣保罗`
 a| 
`GMT-03：00`



 a| 
`America/布宜诺斯艾利斯`
 a| 
`GMT-03：00`



 a| 
`America/Cayenne`
 a| 
`GMT-03：00`



 a| 
`America/godthab`
 a| 
`GMT-03：00`



 a| 
`美洲/蒙特维亚`
 a| 
`GMT-03：00`



 a| 
`etc/GMT+2`
 a| 
`GMT-02：00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01：00`



 a| 
`Atlantic/CAPE_Verde`
 a| 
`GMT-01：00`



 a| 
`非洲/卡萨布兰卡`
 a| 
`GMT`



 a| 
`etc/GMT`
 a| 
`GMT`



 a| 
`欧洲/伦敦`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`欧洲/柏林`
 a| 
`GMT+01：00`



 a| 
`欧洲/布达佩斯`
 a| 
`GMT+01：00`



 a| 
`欧洲/巴黎`
 a| 
`GMT+01：00`



 a| 
`欧洲/华沙`
 a| 
`GMT+01：00`



 a| 
`非洲/拉各斯`
 a| 
`GMT+01：00`



 a| 
`非洲/温得和克`
 a| 
`GMT+01：00`



 a| 
`亚洲/安曼`
 a| 
`GMT+02：00`



 a| 
`亚洲/贝鲁特`
 a| 
`GMT+02：00`



 a| 
`非洲/开罗`
 a| 
`GMT+02：00`



 a| 
`亚洲/大马市`
 a| 
`GMT+02：00`



 a| 
`非洲/约翰内斯堡`
 a| 
`GMT+02：00`



 a| 
`欧洲/基辅`
 a| 
`GMT+02：00`



 a| 
`亚洲/耶路撒冷`
 a| 
`GMT+02：00`



 a| 
`欧洲/伊斯坦布尔`
 a| 
`GMT+03：00`



 a| 
`欧洲/明斯克`
 a| 
`GMT+02：00`



 a| 
`亚洲/巴格达`
 a| 
`GMT+03：00`



 a| 
`亚洲/利雅得`
 a| 
`GMT+03：00`



 a| 
`非洲/内罗比`
 a| 
`GMT+03：00`



 a| 
`亚洲/ Tehran`
 a| 
`GMT+03：30`



 a| 
`欧洲/莫斯科`
 a| 
`GMT+04：00`



 a| 
`亚洲/迪拜`
 a| 
`GMT+04：00`



 a| 
`亚洲/巴库`
 a| 
`GMT+04：00`



 a| 
`印度/毛里塔尼亚`
 a| 
`GMT+04：00`



 a| 
`亚洲/第比利斯`
 a| 
`GMT+04：00`



 a| 
`亚洲/埃里温`
 a| 
`GMT+04：00`



 a| 
`亚洲/卡布尔`
 a| 
`GMT+04：30`



 a| 
`亚洲/卡拉奇`
 a| 
`GMT+05：00`



 a| 
`亚洲//Tashkent`
 a| 
`GMT+05：00`



 a| 
`亚洲/加尔各答`
 a| 
`GMT+05：30`



 a| 
`亚洲/科伦坡`
 a| 
`GMT+05：30`



 a| 
`亚洲/加德满都`
 a| 
`GMT+05：45`



 a| 
`亚洲/叶卡捷林堡`
 a| 
`GMT+06：00`



 a| 
`亚洲/阿拉木图`
 a| 
`GMT+06：00`



 a| 
`亚洲/达卡`
 a| 
`GMT+06：00`



 a| 
`亚洲/ Rangoon`
 a| 
`GMT+06：30`



 a| 
`亚洲/新西比斯克`
 a| 
`GMT+07：00`



 a| 
`亚洲/曼谷`
 a| 
`GMT+07：00`



 a| 
`亚洲/克拉斯尼亚尔斯克`
 a| 
`GMT+08：00`



 a| 
`亚洲/上海`
 a| 
`GMT+08：00`



 a| 
`亚洲/新加坡`
 a| 
`GMT+08：00`



 a| 
`澳大利亚/珀斯`
 a| 
`GMT+08：00`



 a| 
`亚洲/台北`
 a| 
`GMT+08：00`



 a| 
`亚洲/乌兰巴托`
 a| 
`GMT+08：00`



 a| 
`亚洲/伊尔库茨克`
 a| 
`GMT+09：00`



 a| 
`亚洲/东京`
 a| 
`GMT+09：00`



 a| 
`亚洲/首尔`
 a| 
`GMT+09：00`



 a| 
`澳大利亚/阿德雷德`
 a| 
`GMT+09：30`



 a| 
`澳大利亚/ Darwin`
 a| 
`GMT+09：30`



 a| 
`亚洲/雅库茨克`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/布里斯班`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/悉尼`
 a| 
`GMT+10：00`



 a| 
`太平洋/莫尔斯比港`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/霍巴特`
 a| 
`GMT+10：00`



 a| 
`亚洲/符拉迪沃斯托克`
 a| 
`GMT+11：00`



 a| 
`太平洋/瓜达尔卡纳尔`
 a| 
`GMT+11：00`



 a| 
`太平洋/奥克兰`
 a| 
`GMT+12：00`



 a| 
`etc/GMT-12`
 a| 
`GMT+12：00`



 a| 
`太平洋/斐济`
 a| 
`GMT+12：00`



 a| 
`亚洲/Kamchatka`
 a| 
`GMT+12：00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13：00`

|===
用于定义计划的代码串类似于以下示例：

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
如果您还使用`scheduleInterval`选项、则固件会通过选择两个选项中的最低值在`timedPerDay`选项和`scheduleInterval`选项之间进行选择。该固件会将1440除以您设置的`scheduleInterval`选项值来计算`scheduleInterval`选项的整数值。例如、1440/180 = 8。然后、固件会将`timedPerDay`整型值与计算得出的`scheduleInterval`整型值进行比较、并使用较小的值。

要删除计划、请使用`delete volume`命令和`sschedule`参数。带有`sschedule`参数的`delete volume`命令仅删除计划、而不删除快照卷。

在一致性组中执行回滚时、默认操作是回滚一致性组的所有成员。如果无法为一致性组中的所有成员成功启动回滚、则回滚将失败且不起作用。快照映像不会回滚。



== 最低固件级别

7.83.

7.86添加了`scheduleDate`选项和`month`选项。
