---
permalink: commands-a-z/create-storagearray-securitykey.html 
sidebar: sidebar 
keywords: create, storage, array, security, key 
summary: 'create storageArray securityKey命令可为具有全磁盘加密(Full Disk Encryption、FDE)驱动器的存储阵列创建或更改新的安全密钥。' 
---
= 创建存储阵列安全密钥
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`create storageArray securityKey`命令可为具有全磁盘加密(Full Disk Encryption、FDE)驱动器的存储阵列创建或更改新的安全密钥。



== 支持的阵列

如果启用了外部密钥管理、则此命令仅适用于E2800、E5700、EF600和EF300阵列。如果启用了内部密钥管理、则只要安装了所有SMcli软件包、命令适用场景 any individual storage array即可。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有安全管理员角色。



== 环境

对于内部密钥管理、此命令将启用内部密钥管理功能并创建安全密钥。创建密钥后、使用`set storageArray securityKey`命令将该密钥投入使用。此命令也可用于更改安全密钥。

对于外部密钥管理、此命令会创建一个不同的密钥来替换在启用此功能时最初创建的密钥。使用`enable storageArray externalKeyManagement`命令启用外部密钥管理功能并创建初始安全密钥。此命令也可用于更改安全密钥。



== 语法

[listing, subs="+macros"]
----
create storageArray securityKey
[keyIdentifier=pass:quotes[_"keyIdentifierString"_]]
passPhrase=pass:quotes[_"passPhraseString"_
file=_"fileName"_]
[commitSecurityKey=(TRUE | FALSE)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`KeyIdentifier`—仅适用于内部密钥管理
 a| 
一个字符串、您可以读取该字符串作为安全密钥的包装。将密钥标识符用双引号("")括起来。

您可以为内部安全密钥的密钥标识符输入字符、以帮助您稍后识别密钥。以下是格式规则：

* 一个密钥标识符最多可以输入189个字母数字字符。密钥标识符不能包含以下字符：
+
** 空格
** 标点符号
** 符号


* 如果不为内部密钥输入`keyIdentifer`参数、则控制器会自动生成`keyIdentifer`参数。


系统会自动生成其他字符、并将其附加到为密钥标识符输入的字符串末尾。如果未为`KeyIdentifier`参数输入任何字符串、则密钥标识符仅包含自动生成的字符。

[NOTE]
====
外部密钥管理会忽略此参数、因为密钥标识符完全自动生成。如果存储阵列具有用户标签、则此自动生成的字符串将由`s` a.m字符组成、后跟存储阵列用户标签、存储阵列标识符和随机生成的字符串。用户标签中非字母数字字符将转换为下划线(`_`)字符。例如、abc#8的用户标签将转换为`s A.abc_8`、然后再附加到密钥标识符的其余部分。对于没有用户标签的存储阵列、密钥标识符由存储阵列标识符和随机生成的字符串组成。

====


 a| 
`密码短语`
 a| 
一个字符串、用于对安全密钥进行加密、以便将安全密钥存储在外部文件中。请将密码短语用双引号("")括起来。

有关用于创建有效密码短语的正确表单的信息、请参阅此命令问题描述 中的注释。

您的密码短语必须满足以下条件：

* 长度必须介于8到32个字符之间。
* 不得包含空格。
* 必须至少包含一个大写字母。
* 必须至少包含一个小写字母。
* 必须至少包含一个数字。
* 必须至少包含一个非字母数字字符、例如<>@+。


[NOTE]
====
如果您的密码短语不符合这些条件、则会收到一条错误消息、并要求您重试此命令。

====


 a| 
`文件`
 a| 
要将安全密钥保存到的文件路径和文件名。例如：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
文件名的扩展名必须为`.slk`。

====
将文件路径和名称用双引号("")括起来。



 a| 
`commitSecurityKey`—仅适用于内部密钥管理
 a| 
此参数会将所有FDE驱动器以及控制器的安全密钥提交到存储阵列。提交安全密钥后、需要一个密钥才能访问存储阵列中启用了安全保护的驱动器上的数据。只能使用密钥读取或更改数据、如果不将数据变为无用或完全擦除驱动器、则决不能在非安全模式下使用该驱动器。

默认值为false。如果此参数设置为false、请发送单独的`set storageArray securityKey`命令将安全密钥提交到存储阵列。

|===


== 最低固件级别

7.40、用于内部密钥管理

8.40、用于外部密钥管理
