---
permalink: commands-a-z/create-snapgroup.html 
sidebar: sidebar 
keywords: create, snapshot, group 
summary: create snapGroup命令将创建一个新的快照组以及关联的存储库卷。 
---
= 创建快照组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`create snapGroup`命令可创建新的快照组以及关联的存储库卷。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

快照组包含关联基础卷的一系列快照映像。快照组具有一个存储库卷、用于保存属于快照组的所有快照映像的数据。

[NOTE]
====
在创建快照组之前、请确保具有可用容量的卷组可用。

====


== 语法

[source, cli, subs="+macros"]
----
create snapGroup userLabel=pass:quotes[_"snapGroupName_" sourceVolume=_"volumeName"_]
[(repositoryVolume="repos_xxxx" |
repositoryVolume=(pass:quotes[_volumeGroupName_] [capacity=capacityValue]) |
repositoryVolume=(pass:quotes[_diskPoolName_] [capacity=capacityValue]))]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[rollbackPriority=(highest | high | medium | low | lowest)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]|
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapshotSchedule_)]]
----


== Parameters

|===
| 参数 | Description 


 a| 
`用户标签`
 a| 
要为新快照组指定的名称。将快照组标识符用双引号("")括起来。



 a| 
`sSourceVolume`
 a| 
要用作快照映像源的卷的名称。将源卷名称用双引号("")括起来。



 a| 
`repositoryVolume`
 a| 
要包含快照组中已更改数据的存储库卷的名称。

您可以通过两个选项来定义存储库卷的名称：

* 使用现有存储库卷：name
* 运行此命令时、请创建一个新的存储库卷


现有存储库卷的名称由两部分组成：

* 术语"repos"
* 存储管理软件分配给存储库卷名称的四位数字标识符


将现有存储库卷的名称用双引号("")括起来。

如果要在运行此命令时创建新的存储库卷、则必须输入要在其中创建存储库卷的卷组或磁盘池的名称。您也可以选择定义存储库卷的容量。如果要定义容量、可以使用以下值：

* 一个整数值、表示基本卷容量的百分比
* 一个小数值、表示基本卷容量的百分比
* 存储库卷的特定大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。


如果不使用容量选项、则存储管理软件会将容量设置为基本卷容量的20%。

运行此命令时、存储管理软件将为快照卷创建存储库卷。



 a| 
`repositoryFullPolicy`
 a| 
定义在快照组存储库卷已满时如何继续处理快照映像。您可以选择使对基础卷的I/O写入失败(`failBaseWrites`)或删除(清除)存储库卷中的快照映像(`purgeSnapImages`)。`purgeSnapImages`选项可删除最旧的快照映像以释放空间。默认操作为`purgeSnapImages`。



 a| 
`rollBackPriority`
 a| 
确定是否应将系统资源分配给回滚操作而牺牲系统性能。值`high`表示回滚操作的优先级高于所有其他主机I/O值`low`表示执行回滚操作时、应尽可能减少对主机I/O的影响默认值为`medium`。



 a| 
`repositoryFullLimit`
 a| 
收到快照组存储库卷接近全满警告时存储库容量的百分比。使用整数值。例如、值70表示70%。默认值为75。



 a| 
`autodeleteLimit`
 a| 
可以将每个快照组配置为自动删除其快照映像、以使快照组中的快照映像总数保持在指定级别或以下。启用此选项后、每当在快照组中创建新的快照映像时、系统都会自动删除组中最早的快照映像、以符合限制值。此操作可释放存储库容量、以便用于满足其余Snapshot映像的持续写入时复制要求。



 a| 
`enableSchedule`
 a| 
使用此参数可以启用或禁用计划快照操作的功能。要启用快照计划、请将此参数设置为`true`。要关闭快照计划、请将此参数设置为`false`。

|===


== 注释：

每个快照组名称必须唯一。您可以对用户标签使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。用户标签最多可以包含30个字符。

要创建快照组、您必须具有一个关联的存储库卷来存储快照映像。您可以使用现有存储库卷、也可以创建新的存储库卷。您可以在创建快照组时创建存储库卷。快照组存储库卷是一个可扩展卷、其结构为一个串联集合、最多包含16个标准卷实体。最初、可扩展存储库卷只有一个元素。可扩展存储库卷的容量与单个元素的容量完全相同。您可以通过向可扩展存储库卷附加其他标准卷来增加该卷的容量。然后、复合可扩展存储库卷容量将成为所有串联标准卷的容量之和。

快照组会根据创建每个快照映像的时间对快照映像进行严格的排序。在另一个快照映像之后创建的快照映像是相对于该另一个快照映像的_success继承 者_。在另一个快照映像之前创建的快照映像是相对于另一个快照映像的_predecent_。

Snapshot组存储库卷必须满足以下各项的总和所需的最小容量：

* 32 MB、用于支持快照组和写入时复制处理的固定开销。
* 回滚处理的容量、是基础卷容量的1/5000。


最小容量由控制器固件和存储管理软件强制实施。

首次创建快照组时、它不包含任何快照映像。创建快照映像时、您可以将快照映像添加到快照组。使用`create SnapImage`命令创建快照映像并将快照映像添加到快照组。

快照组可以具有以下状态之一：

* *最佳*—快照组运行正常。
* *已满*—快照组存储库已满。无法执行其他写入时复制操作。只有将存储库已满策略设置为失败基础写入的快照组才会出现此状态。如果任何快照组处于完整状态、则会为存储阵列发布需要注意的情况。
* *超过阈值*-快照组存储库卷使用量达到或超过其警报阈值。处于此状态的任何快照组都会导致为存储阵列发布需要注意的情况。
* *失败*—快照组遇到问题、导致快照组中的所有快照映像都不可用。例如、某些类型的存储库卷故障可以将发生原因 设置为故障状态。要从故障状态恢复、请使用`revve snapGroup`命令。


您可以使用`autodeleteLimit`参数将每个快照组配置为自动删除快照映像。通过自动删除快照映像、您可以避免例行手动删除不需要的映像、这可能会因为存储库卷已满而阻止创建未来的快照映像。使用`autodeleteLimit`参数时、它会导致存储管理软件自动删除快照映像、从最早的映像开始。存储管理软件会删除快照映像、直到其达到与您使用`autodeleteLimit`参数输入的数量相等的多个快照映像为止。将新的Snapshot映像添加到存储库卷后、存储管理软件将删除最旧的快照映像、直到达到`autodeleteLimit`参数编号为止。

使用`enableSchedule`参数和`schedule`参数、您可以计划为快照组创建快照映像。使用这些参数、您可以计划每日、每周或每月(按天或日期)创建快照。`enableSchedule`参数用于启用或禁用快照计划功能。启用计划时、您可以使用`schedule`参数来定义快照的发生时间。

下表说明了如何使用`schedule`参数的选项：

|===
| 参数 | Description 


 a| 
`s计划`
 a| 
用于指定计划参数。



 a| 
`即时`
 a| 
立即启动操作。此项与任何其他计划参数不能共存。



 a| 
`enableSchedule`
 a| 
如果设置为`true`、则会启用计划。如果设置为`false`、则计划将关闭。

[NOTE]
====
默认值为 `false` 。

====


 a| 
`sTartDate`
 a| 
启动操作的特定日期。输入日期的格式为MM：DD：YY。默认值为当前日期。例如、此选项为`startDate=06：27：11`。



 a| 
`scheduleDay`
 a| 
要启动操作的一周中的某一天。可以是以下全部或一个或多个值：

* `m每日`
* `星期二`
* `星期三`
* `星期四`
* `星期五`
* `saturday`
* `sUnday`


[NOTE]
====
将值括在圆括号中。例如、`scheduleDay=(星期三)`。

====
可以通过将天数括在一组圆括号中并使用空格分隔来指定一天以上。例如、`scheduleDay=(星期一星期三星期五)`。

[NOTE]
====
此参数与每月计划不兼容。

====


 a| 
`sTartTime`
 a| 
一天中启动操作的时间。输入时间的格式为HH：mm、其中HH是小时、MM是小时后的分钟。使用24小时制时钟。例如、下午2：00为14：00。此选项的一个示例是`startTime=14：27`。



 a| 
`scheduleInterval`
 a| 
两次操作之间的最短时间(以分钟为单位)。计划间隔不应超过1440 (24小时)、并且应为30的倍数。

此选项的一个示例是`scheduleInterval=180`。



 a| 
`endDate`
 a| 
停止操作的特定日期。输入日期的格式为MM：DD：YY。如果不需要结束日期、可以指定`noEndDate`。例如、此选项为`endDate=11：26：11`。



 a| 
`TimesPerDay`
 a| 
一天中执行此操作的次数。此选项的一个示例是`timesPerDae=4`。



 a| 
`时区`
 a| 
指定计划要使用的时区。可以通过两种方式指定：

* * GMT±HH：MM*
+
与GMT的时区偏移。示例：`timezone=GMT-06：00`。

* *文本字符串*
+
标准时区文本字符串必须用引号括起来。示例：``timezone="America/Chicago"``





 a| 
`s计划日期`
 a| 
要执行此操作的月份中的某一天。这些天数的值为数字值、范围为1-31。

[NOTE]
====
此参数与每周计划不兼容。

====
例如、`scheduleDate`选项为`scheduleDate=("15")`。



 a| 
`mon th`
 a| 
要执行此操作的特定月份。月份的值为：

* `JAN` 1月
* `feb`—2月
* `mar`- 3月
* `4月` 4月
* `may`- 5月
* `jun`—6月
* `Jul`- Jul
* `8月` 8月
* `sEP`—9月
* `oct`—10月
* `11月`—11月
* `dEC`—12月


[NOTE]
====
将值括在圆括号中。例如、`month=(JAN)`。

====
可以指定多个月、方法是将月份括在一组圆括号中、并使用空格分隔每个月。例如、`month=(Jul Jul decd)`。

将此参数与`scheduleDate`参数结合使用、可在一个月的特定日期执行此操作。

[NOTE]
====
此参数与每周计划不兼容。

====
|===
下表说明了如何使用`timezone`参数：

|===
| 时区名称 | GMT偏移 


 a| 
`etc/GMT+12`
 a| 
`GMT-12：00`



 a| 
`etc/GMT+11`
 a| 
`GMT-11：00`



 a| 
`太平洋/火鲁鲁鲁`
 a| 
`GMT-10：00`



 a| 
`美洲/安克雷奇`
 a| 
`GMT-09：00`



 a| 
`America/Santa_ISA贝尔`
 a| 
`GMT-08：00`



 a| 
`美洲/洛杉矶`
 a| 
`GMT-08：00`



 a| 
`美洲/凤凰城`
 a| 
`GMT-07：00`



 a| 
`美洲/奇瓦华`
 a| 
`GMT-07：00`



 a| 
`美洲/丹佛`
 a| 
`GMT-07：00`



 a| 
`美洲/危地马拉`
 a| 
`GMT-06：00`



 a| 
`美洲/芝加哥`
 a| 
`GMT-06：00`



 a| 
`美洲/墨西哥_城市`
 a| 
`GMT-06：00`



 a| 
`美洲/里贾纳`
 a| 
`GMT-06：00`



 a| 
`美洲/波哥大`
 a| 
`GMT-05：00`



 a| 
`美洲/纽约`
 a| 
`GMT-05：00`



 a| 
`etc/GMT+5`
 a| 
`GMT-05：00`



 a| 
`美洲/ Caracas`
 a| 
`GMT-04：30`



 a| 
`美洲/亚松森`
 a| 
`GMT-04：00`



 a| 
`美洲/哈利法克斯`
 a| 
`GMT-04：00`



 a| 
`美洲/Cuiaba`
 a| 
`GMT-04：00`



 a| 
`America/La_Paz`
 a| 
`GMT-04：00`



 a| 
`美洲/圣地亚哥`
 a| 
`GMT-04：00`



 a| 
`America/St_Johns`
 a| 
`GMT-03：30`



 a| 
`America/Sao_圣保罗`
 a| 
`GMT-03：00`



 a| 
`America/布宜诺斯艾利斯`
 a| 
`GMT-03：00`



 a| 
`America/Cayenne`
 a| 
`GMT-03：00`



 a| 
`America/godthab`
 a| 
`GMT-03：00`



 a| 
`美洲/蒙特维亚`
 a| 
`GMT-03：00`



 a| 
`etc/GMT+2`
 a| 
`GMT-02：00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01：00`



 a| 
`Atlantic/CAPE_Verde`
 a| 
`GMT-01：00`



 a| 
`非洲/卡萨布兰卡`
 a| 
`GMT`



 a| 
`etc/GMT`
 a| 
`GMT`



 a| 
`欧洲/伦敦`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`欧洲/柏林`
 a| 
`GMT+01：00`



 a| 
`欧洲/布达佩斯`
 a| 
`GMT+01：00`



 a| 
`欧洲/巴黎`
 a| 
`GMT+01：00`



 a| 
`欧洲/华沙`
 a| 
`GMT+01：00`



 a| 
`非洲/拉各斯`
 a| 
`GMT+01：00`



 a| 
`非洲/温得和克`
 a| 
`GMT+01：00`



 a| 
`亚洲/安曼`
 a| 
`GMT+02：00`



 a| 
`亚洲/贝鲁特`
 a| 
`GMT+02：00`



 a| 
`非洲/开罗`
 a| 
`GMT+02：00`



 a| 
`亚洲/大马市`
 a| 
`GMT+02：00`



 a| 
`非洲/约翰内斯堡`
 a| 
`GMT+02：00`



 a| 
`欧洲/基辅`
 a| 
`GMT+02：00`



 a| 
`亚洲/耶路撒冷`
 a| 
`GMT+02：00`



 a| 
`欧洲/伊斯坦布尔`
 a| 
`GMT+03：00`



 a| 
`欧洲/明斯克`
 a| 
`GMT+02：00`



 a| 
`亚洲/巴格达`
 a| 
`GMT+03：00`



 a| 
`亚洲/利雅得`
 a| 
`GMT+03：00`



 a| 
`非洲/内罗比`
 a| 
`GMT+03：00`



 a| 
`亚洲/ Tehran`
 a| 
`GMT+03：30`



 a| 
`欧洲/莫斯科`
 a| 
`GMT+04：00`



 a| 
`亚洲/迪拜`
 a| 
`GMT+04：00`



 a| 
`亚洲/巴库`
 a| 
`GMT+04：00`



 a| 
`印度/毛里塔尼亚`
 a| 
`GMT+04：00`



 a| 
`亚洲/第比利斯`
 a| 
`GMT+04：00`



 a| 
`亚洲/埃里温`
 a| 
`GMT+04：00`



 a| 
`亚洲/卡布尔`
 a| 
`GMT+04：30`



 a| 
`亚洲/卡拉奇`
 a| 
`GMT+05：00`



 a| 
`亚洲//Tashkent`
 a| 
`GMT+05：00`



 a| 
`亚洲/加尔各答`
 a| 
`GMT+05：30`



 a| 
`亚洲/科伦坡`
 a| 
`GMT+05：30`



 a| 
`亚洲/加德满都`
 a| 
`GMT+05：45`



 a| 
`亚洲/叶卡捷林堡`
 a| 
`GMT+06：00`



 a| 
`亚洲/阿拉木图`
 a| 
`GMT+06：00`



 a| 
`亚洲/达卡`
 a| 
`GMT+06：00`



 a| 
`亚洲/ Rangoon`
 a| 
`GMT+06：30`



 a| 
`亚洲/新西比斯克`
 a| 
`GMT+07：00`



 a| 
`亚洲/曼谷`
 a| 
`GMT+07：00`



 a| 
`亚洲/克拉斯尼亚尔斯克`
 a| 
`GMT+08：00`



 a| 
`亚洲/上海`
 a| 
`GMT+08：00`



 a| 
`亚洲/新加坡`
 a| 
`GMT+08：00`



 a| 
`澳大利亚/珀斯`
 a| 
`GMT+08：00`



 a| 
`亚洲/台北`
 a| 
`GMT+08：00`



 a| 
`亚洲/乌兰巴托`
 a| 
`GMT+08：00`



 a| 
`亚洲/伊尔库茨克`
 a| 
`GMT+09：00`



 a| 
`亚洲/东京`
 a| 
`GMT+09：00`



 a| 
`亚洲/首尔`
 a| 
`GMT+09：00`



 a| 
`澳大利亚/阿德雷德`
 a| 
`GMT+09：30`



 a| 
`澳大利亚/ Darwin`
 a| 
`GMT+09：30`



 a| 
`亚洲/雅库茨克`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/布里斯班`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/悉尼`
 a| 
`GMT+10：00`



 a| 
`太平洋/莫尔斯比港`
 a| 
`GMT+10：00`



 a| 
`澳大利亚/霍巴特`
 a| 
`GMT+10：00`



 a| 
`亚洲/符拉迪沃斯托克`
 a| 
`GMT+11：00`



 a| 
`太平洋/瓜达尔卡纳尔`
 a| 
`GMT+11：00`



 a| 
`太平洋/奥克兰`
 a| 
`GMT+12：00`



 a| 
`etc/GMT-12`
 a| 
`GMT+12：00`



 a| 
`太平洋/斐济`
 a| 
`GMT+12：00`



 a| 
`亚洲/Kamchatka`
 a| 
`GMT+12：00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13：00`

|===
用于定义计划的代码串类似于以下示例：

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
如果您还使用`scheduleInterval`选项、则固件会通过选择两个选项中的最低值在`timedPerDay`选项和`scheduleInterval`选项之间进行选择。固件会将1440除以您设置的`scheduleInterval`选项值、从而计算`scheduleInterval`选项的整数值。例如、1440/180 = 8。然后、固件会将`timedPerDay`整型值与计算得出的`scheduleInterval`整型值进行比较、并使用较小的值。

要删除计划、请使用`delete volume`命令和`sschedule`参数。带有`sschedule`参数的`delete volume`命令仅删除计划、而不删除快照卷。



== 最低固件级别

7.83.

7.86添加了`scheduleDate`选项和`month`选项。
