---
permalink: commands-a-z/create-snapshot-volume.html 
sidebar: sidebar 
keywords: create, snapshot, volume 
summary: create snapVolume命令可为基础卷的快照映像创建具有读写功能的快照卷。 
---
= 创建Snapshot卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`create snapVolume`命令可为基础卷的快照映像创建具有读写功能的快照卷。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您可以将快照卷映射到主机、并且所有主机写入操作都驻留在与快照卷关联的存储库卷中。您可以将新的快照卷分配给现有存储库卷、也可以在卷组或磁盘池中创建新的存储库卷。

[NOTE]
====
不能对联机卷副本中使用的快照映像使用此命令。

====


== 语法

[source, cli, subs="+macros"]
----
create snapVolume userLabel=pass:quotes[_"snapVolumeName_" snapImageID="_snapCGID:imageID_"]
[(repositoryVolume="repos_xxxx"]
[repositoryVolume=pass:quotes[_(volumeGroupName_]pass:quotes[[capacity=_capacityValue_]]]
[repositoryVolume=pass:quotes[(_diskPoolName_]pass:quotes[[capacity=_capacityValue_])]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== Parameters

|===
| 参数 | Description 


 a| 
`用户标签`
 a| 
要为快照卷指定的名称。将快照卷名称用双引号("")括起来。



 a| 
`snapImageID`
 a| 
要添加到新快照卷的快照映像的字母数字标识符。快照映像的标识符由两部分组成：

* 快照组的名称
* 快照组中快照映像的标识符


快照映像的标识符可以是以下项之一：

* 一个整数值、是快照组中快照的序列号。
* `最新`-如果要显示在快照组中创建的最新快照映像、请使用此选项。
* `oldest`—如果要显示在快照组中创建的最早快照映像、请使用此选项。


将快照映像名称用双引号("")括起来。



 a| 
`repositoryVolume`
 a| 
存储Snapshot映像中更改的数据的存储库卷的名称。

您可以通过两个选项来定义存储库卷的名称：

* 使用现有存储库卷名称
* 运行此命令时、请创建一个新的存储库卷


现有存储库卷的名称由两部分组成：

* 术语"repos"
* 存储管理软件分配给存储库卷名称的四位数字标识符


将现有存储库卷的名称用双引号("")括起来。

如果要在运行此命令时创建新的存储库卷、则必须输入要在其中创建存储库卷的卷组或磁盘池的名称。您也可以选择定义存储库卷的容量。如果要定义容量、可以使用以下值：

* 一个整数值、表示基本卷容量的百分比
* 一个小数值、表示基本卷容量的百分比
* 存储库卷的特定大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。


如果不使用容量选项、则存储管理软件会将容量设置为基本卷容量的20%。

运行此命令时、存储管理软件将为快照卷创建存储库卷。



 a| 
`repositoryFullLimit`
 a| 
收到快照存储库卷接近全满警告时存储库容量的百分比。使用整数值。例如、值70表示70%。默认值为75。

|===


== 注释：

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

快照映像的标识符包含两个部分、并用冒号(：)分隔：

* 快照组的名称
* 快照映像的标识符


例如、如果要在名为snapGroup1的快照组中使用最新的快照映像创建名为snapData1的快照卷、而该快照组的存储库卷的最大填充限制为80%、则可以使用以下命令：

[listing]
----
create snapVolume userLabel="snapData1" snapImageID="snapGroup1:newest"
repositoryVolume="repos_1234" repositoryFullLimit=80;
----
在创建新快照组时、存储管理软件和固件会自动创建存储库卷标识符。您无法重命名存储库卷、因为重命名存储库卷会中断与快照映像的链接。



== 最低固件级别

7.83.
