---
permalink: commands-a-z/create-raid-volume-free-extent-based-select.html 
sidebar: sidebar 
keywords: create, raid, volume, free, extent, based, select 
summary: create volume命令会在卷组的可用空间中创建卷。 
---
= 创建RAID卷(基于可用块区的选择)
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`create volume`命令可在卷组的可用空间中创建卷。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[listing, subs="+macros"]
----
create volume volumeGroup=pass:quotes[_"volumeGroupName"_
userLabel="_volumeName"_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[dataAssurance=(none | enabled)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`VolumeGroup`
 a| 
存储阵列中特定卷组的名称。将卷组名称用双引号("")括起来。



 a| 
`用户标签`
 a| 
要为新卷指定的名称。将新卷名称用双引号("")括起来。

[NOTE]
====
此参数为必填项。

====


 a| 
`FreeCapacityArea`
 a| 
现有卷组中要用于创建新卷的可用空间的索引编号。可用容量是指卷组中现有卷之间的可用容量。例如、卷组可能具有以下区域：卷1、可用容量、卷2、可用容量、卷3、 可用容量。要使用卷2之后的可用容量、应输入以下索引编号：

`freeCapacityArea = 2`

[NOTE]
====
运行`show VolumeGroup`命令以确定是否存在可用容量区域。

====
[NOTE]
====
如果未指定此参数、则会在编号最低的可用容量区域创建卷、并为卷提供足够的容量。

====


 a| 
`容量`
 a| 
要添加到存储阵列的卷的大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。



 a| 
`所有者`
 a| 
拥有卷的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器如果未指定所有者、则控制器固件将确定所有者。



 a| 
`cachedReadPrefetch`
 a| 
用于打开或关闭缓存读取预取的设置。要启用缓存读取预取、请将此参数设置为`true`。要关闭缓存读取预取、请将此参数设置为`false`。



 a| 
`segmentSize`
 a| 
在将数据写入下一个驱动器之前、控制器在卷中的单个驱动器上写入的数据量(以KB为单位)。有效值为`8`、`16`、`32`、`64`、`128`、 `256`或`512`。



 a| 
`usageHint`
 a| 
`cachedReadPrefetch`参数和`segmentSize`参数的设置均为默认值。默认值基于使用卷的应用程序的典型I/O使用模式。有效值为`filesystem`、`datasystem`或`multimedia`。



 a| 
`dssPreAllocate`
 a| 
用于确保为未来区块大小分配预留容量的设置会增加。默认值为`true`。



 a| 
`securityType`
 a| 
用于指定创建卷组和所有关联卷时的安全级别的设置。这些设置有效：

`none`—卷组和卷不安全。

`capable`—卷组和卷可以设置安全设置、但尚未启用安全性。

`enabled`—卷组和卷已启用安全性。

|===


== 注释：

您可以对名称使用字母数字字符、连字符和下划线的任意组合。名称最多可以包含30个字符。

`owner`参数用于定义拥有卷的控制器。卷的首选控制器所有权是当前拥有卷组的控制器。

如果不使用`capacity`参数指定容量、则会使用卷组的可用容量区域中的所有可用容量。如果未指定容量单位、则会使用`bytes`作为默认值。



== 区块大小

区块大小决定了在将数据写入下一个驱动器之前控制器在卷中的单个驱动器上写入的数据块数。每个数据块存储512字节的数据。数据块是最小的存储单元。分段的大小决定了其包含的数据块数。例如、一个8 KB区块可容纳16个数据块。64 KB区块可容纳128个数据块。

为区块大小输入值时、系统会对照控制器在运行时提供的受支持值来检查该值。如果您输入的值无效、则控制器将返回有效值列表。使用单个驱动器处理单个请求会使其他驱动器可以同时处理其他请求。如果卷所在环境中的一个用户正在传输大量数据(例如多媒体)、则在使用一个数据条带处理单个数据传输请求时、性能会最大化。(数据条带是指分段大小乘以卷组中用于数据传输的驱动器数。) 在这种情况下、同一请求会使用多个驱动器、但每个驱动器只访问一次。

为了在多用户数据库或文件系统存储环境中获得最佳性能、请设置区块大小、以最大程度地减少满足数据传输请求所需的驱动器数量。



== 使用提示

[NOTE]
====
您无需为`cachedReadPrefetch`参数或`segmentSize`参数输入值。如果不输入值、则控制器固件会使用`usageHint`参数和`filesystem`作为默认值。为`usageHint`参数输入值和`cachedetch`参数值或为`segmentSize`参数输入值不发生原因 会产生错误。为`cachedReadPrefetch`参数或`segmentSize`参数输入的值优先于`usageHint`参数的值。下表显示了各种使用提示的区块大小和缓存读取预取设置：

====
|===
| 使用提示 | 区块大小设置 | 动态缓存读取预取设置 


 a| 
文件系统
 a| 
128 KB
 a| 
enabled



 a| 
数据库
 a| 
128 KB
 a| 
enabled



 a| 
多媒体
 a| 
256 KB
 a| 
enabled

|===


== 缓存读取预取

缓存读取预取允许控制器将其他数据块复制到缓存中、同时控制器将主机请求的数据块从驱动器读取并复制到缓存中。此操作增加了从缓存满足未来数据请求的可能性。对于使用顺序数据传输的多媒体应用程序来说、缓存读取预取非常重要。`cachedReadPrefetch`参数的有效值为`true`或`false`。默认值为`true`。



== 安全类型

使用`securityType`参数指定存储阵列的安全设置。

要将`securityType`参数设置为`enabled`、必须先创建存储阵列安全密钥。使用`create storageArray securityKey`命令创建存储阵列安全密钥。这些命令与安全密钥相关：

* `创建storageArray securityKey`
* `导出storageArray securityKey`
* `导入storageArray securityKey`
* `set storageArray securityKey`
* `启用VolumeGroup [volumeGroupName]安全性`
* `启用diskPool [diskPoolName]安全性`




== 最低固件级别

7.10添加`dssPreAllocate`参数。

7.50添加了`securityType`参数。

7.75添加`dataAssurance`参数。
