---
permalink: commands-a-z/create-storagearray-directoryserver.html 
sidebar: sidebar 
keywords: create, storage, array, directory server 
summary: 使用create storageArray directoryServer命令可以添加新的目录服务器、以用于对用户进行身份验证和授权。 
---
= 创建存储阵列目录服务器
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`create storageArray directoryServer`命令可以添加新的目录服务器、以用于对用户进行身份验证和授权。



== 支持的阵列

此命令用于适用场景 单个E2800、E5700、EF600或EF300存储阵列。它不能在E2700或E5600存储阵列上运行。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有安全管理员角色。



== 语法

[listing, subs="+macros"]
----

create storageArray directoryServer
       [domainId=pass:quotes[_"domainId"_
       domainNames=(_"domainName1"..."domainNameN"_)
       serverUrl="_serverUrl"_]
       [bindAccount=pass:quotes[_"username_" bindPassword="_password_"]]
       searchBaseDN=pass:quotes[_"distinguishedName"_
       usernameAttribute="_attributeName_"
       groupAttributes=("_attrName1"..."attrNameN_")]
        [skipConfigurationTest={true | false}]
----


== Parameters

|===
| 参数 | Description 


 a| 
`domainId`
 a| 
用于为此域指定唯一ID。如果未指定、则会生成唯一GUID。



 a| 
`domainNames`
 a| 
用于为目录服务器指定一个或多个有效域名。如果输入多个名称、请使用空格分隔这些值。



 a| 
`serverUrl`
 a| 
用于以ldap[s]//hostAddress：port的形式指定用于访问LDAP服务器的URL。如果使用的是LDAPS协议、请确保使用certificate命令导入用于验证目录服务器签名证书的根/中间证书。



 a| 
`bindAccount`
 a| 
用于指定要用作绑定帐户的用户名或绑定ID。



 a| 
`bindPassword`
 a| 
用于指定要用作绑定密码的密码。



 a| 
`searchBaseDN`
 a| 
用于指定搜索基本可分辨名称以搜索LDAP用户对象以确定组成员资格。



 a| 
`用户名属性`
 a| 
用于指定用于搜索用户对象以确定组成员资格的属性。如果指定、则字符串必须包含变量`+｛uid｝+`、该变量将替换为登录期间使用的用户名。示例：`+sAMAccountName=｛uid｝+`



 a| 
`groupAttributes`
 a| 
用于设置一个或多个组属性以查找组可分辨名称。可分辨名称用于确定角色映射的组成员资格。

[NOTE]
====
如果输入多个组、请使用空格将值分隔开。

====
[NOTE]
====
使用此参数将清除现有组。

====


 a| 
`skipConfigurationTest`
 a| 
用于在保存配置之前跳过配置测试。默认值为 `false` 。

|===


== 示例

[listing]
----
SMcli -n Array1 -c "create storageArray directoryServer
domainNames=("company.com") serverUrl="ldap://hqldap.company.com:389"
bindAccount="dummyBindDN" bindPassword="dummyPassword"
searchBaseDN="OU=_Users,DC=hq, DC=company,DC=com"
usernameAttributes="sAMAccountName={uid}" groupAttributes="memberOf";"

SMcli completed successfully.
----