---
permalink: commands-a-z/create-raid-volume-automatic-drive-select.html 
sidebar: sidebar 
keywords: create, raid, volume, automatic, drive, select 
summary: create volume命令可在存储阵列中的驱动器之间创建一个卷组、并在卷组中创建一个新卷。存储阵列控制器可选择要包含在卷中的驱动器。 
---
= 创建 RAID 卷（自动驱动器选择）- SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`create volume`命令可在存储阵列中的驱动器之间创建卷组、并在卷组中创建新卷。存储阵列控制器可选择要包含在卷中的驱动器。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
如果驱动器容量不同、则无法通过指定`driveCount`参数自动创建卷。如果要使用不同容量的驱动器创建卷、请参见 link:create-raid-volume-manual-drive-select.html["创建RAID卷(手动选择驱动器)"]。

====


== 语法

[source, cli, subs="+macros"]
----
create volume driveCount=pass:quotes[_numberOfDrives_]
[volumeGroupUserLabel=pass:quotes[_"volumeGroupUserLabel"_]]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"userLabel"_]
driveMediaType=(HDD | SSD | unknown | allMedia)
[driveType=(SAS | NVMe4K)]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[mapping=(none | default)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[secureDrives=(fips | fde )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== Parameters

|===
| 参数 | Description 


 a| 
`driveCount`
 a| 
要在卷组中使用的未分配驱动器的数量。



 a| 
`volumeGroupUserLabel`
 a| 
要为新卷组指定的名称。将新卷组名称用双引号("")括起来。

[NOTE]
====
如果未为卷组指定用户标签、则控制器固件会为其分配一个数字。

====


 a| 
`raidLevel`
 a| 
包含卷的卷组的RAID级别。有效值为`0`、`1`、`3`、`5`或`6`。



 a| 
`用户标签`
 a| 
要为新卷指定的名称。将新卷名称用双引号("")括起来。

[NOTE]
====
此参数为必填项。

====


 a| 
`driveMediaType`
 a| 
要用于卷组的驱动器介质类型。这些驱动器介质有效：

* `HDD`—如果驱动器托盘中有硬盘驱动器、请使用此选项
* `sSD`—如果驱动器托盘中有固态驱动器、请使用此选项
* `unknown`—如果您不确定驱动器托盘中的驱动器介质类型、请使用此选项
* `allMedia`—如果要使用驱动器托盘中的所有类型的驱动器介质、请使用此选项




 a| 
`d驱动器类型`
 a| 
要在卷中使用的驱动器类型。您不能混用驱动器类型。

如果存储阵列中有多种类型的驱动器、则必须使用此参数。

这些驱动器类型有效：

* `s作为`
* `NVMe4K`


如果未指定驱动器类型、则此命令默认为`任何类型`。



 a| 
`容量`
 a| 
要添加到存储阵列的卷的大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。



 a| 
`所有者`
 a| 
拥有卷的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器如果未指定所有者、则控制器固件将确定所有者。



 a| 
`cachedReadPrefetch`
 a| 
用于打开或关闭缓存读取预取的设置。要关闭缓存读取预取、请将此参数设置为`false`。要启用缓存读取预取、请将此参数设置为`true`。



 a| 
`segmentSize`
 a| 
在将数据写入下一个驱动器之前、控制器在卷中的单个驱动器上写入的数据量(以KB为单位)。有效值为`8`、`16`、`32`、`64`、`128`、 `256`或`512`。



 a| 
`usageHint`
 a| 
`cachedReadPrefetch`参数和`segmentSize`参数的设置均为默认值。默认值基于使用卷的应用程序的典型I/O使用模式。有效值为`filesystem`、`datasystem`或`multimedia`。



 a| 
`纸架LossProtect`
 a| 
创建卷组时用于强制实施托盘丢失保护的设置。要强制实施托盘丢失保护、请将此参数设置为`true`。默认值为`false`。



 a| 
`drawerLossProtect`
 a| 
用于在创建镜像存储库卷组时强制实施抽盒丢失保护的设置。要强制实施抽盒丢失保护、请将此参数设置为`true`。默认值为`false`。



 a| 
`dssPreAllocate`
 a| 
用于确保为未来区块大小分配预留容量的设置会增加。默认值为`true`。



 a| 
`securityType`
 a| 
用于指定创建卷组和所有关联卷时的安全级别的设置。这些设置有效：

* `none`—卷组和卷不安全。
* `capable`—卷组和卷可以设置安全设置、但尚未启用安全性。
* `enabled`—卷组和卷已启用安全性。




 a| 
`resourceProvisioningCapable`
 a| 
用于指定是否启用资源配置功能的设置。要禁用资源配置、请将此参数设置为`false`。默认值为`true`。



 a| 
`m设置`
 a| 
使用此参数可以将卷映射到主机。如果要稍后映射、请将此参数设置为 `none`。如果要立即映射、请将此参数设置为 `default`。卷将映射到有权访问存储池的所有主机。默认值为 `none`。



 a| 
`块大小`
 a| 
此参数用于设置要创建的卷的块大小。如果值为0或参数未设置、则会使用默认块大小。

|===


== 注释：

您可以对名称使用字母数字字符、连字符和下划线的任意组合。名称最多可以包含30个字符。

使用`driveCount`参数可以选择要在卷组中使用的驱动器数。您无需按托盘ID和插槽ID指定驱动器。控制器会选择要用于卷组的特定驱动器。

`owner`参数用于定义拥有卷的控制器。

如果未使用`capacity`参数指定容量、则会使用卷组中可用的所有驱动器容量。如果未指定容量单位、则会使用`bytes`作为默认值。



== 区块大小

区块大小决定了在将数据写入下一个驱动器之前控制器在卷中的单个驱动器上写入的数据块数。每个数据块存储512字节的数据。数据块是最小的存储单元。分段的大小决定了其包含的数据块数。例如、一个8 KB区块可容纳16个数据块。64 KB区块可容纳128个数据块。

为区块大小输入值时、系统会对照控制器在运行时提供的受支持值来检查该值。如果您输入的值无效、则控制器将返回有效值列表。使用单个驱动器处理单个请求会使其他驱动器可以同时处理其他请求。如果卷所在环境中的一个用户正在传输大量数据(例如多媒体)、则在使用一个数据条带处理单个数据传输请求时、性能会最大化。(数据条带是指分段大小乘以卷组中用于数据传输的驱动器数。) 在这种情况下、同一请求会使用多个驱动器、但每个驱动器只访问一次。

为了在多用户数据库或文件系统存储环境中获得最佳性能、请设置区块大小、以最大程度地减少满足数据传输请求所需的驱动器数量。



== 使用提示

[NOTE]
====
您无需为`cachedReadPrefetch`参数或`segmentSize`参数输入值。如果不输入值、则控制器固件会使用`usageHint`参数和`filesystem`作为默认值。为`usageHint`参数输入值和`cachedetch`参数值或为`segmentSize`参数输入值不发生原因 会产生错误。为`cachedReadPrefetch`参数或`segmentSize`参数输入的值优先于`usageHint`参数的值。下表显示了各种使用提示的区块大小和缓存读取预取设置：

====
|===
| 使用提示 | 区块大小设置 | 动态缓存读取预取设置 


 a| 
文件系统
 a| 
128 KB
 a| 
enabled



 a| 
数据库
 a| 
128 KB
 a| 
enabled



 a| 
多媒体
 a| 
256 KB
 a| 
enabled

|===


== 缓存读取预取

缓存读取预取允许控制器将其他数据块复制到缓存中、同时控制器将主机请求的数据块从驱动器读取并复制到缓存中。此操作增加了从缓存满足未来数据请求的可能性。对于使用顺序数据传输的多媒体应用程序来说、缓存读取预取非常重要。`cachedReadPrefetch`参数的有效值为`true`或`false`。默认值为`true`。



== 安全类型

使用`securityType`参数指定存储阵列的安全设置。

要将`securityType`参数设置为`enabled`、必须先创建存储阵列安全密钥。使用`create storageArray securityKey`命令创建存储阵列安全密钥。这些命令与安全密钥相关：

* `创建storageArray securityKey`
* `导出storageArray securityKey`
* `导入storageArray securityKey`
* `set storageArray securityKey`
* `启用VolumeGroup [volumeGroupName]安全性`
* `启用diskPool [diskPoolName]安全性`




== 保护驱动器

支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。使用`secureDrives`参数指定要使用的安全驱动器类型。可以使用的值为`FIPS`和`FDE`。



== 托盘丢失保护和抽盒丢失保护

要启用托盘/抽盒丢失保护、请参见下表了解其他标准：

|===
| 级别 | 托盘丢失保护标准 | 所需的最小托盘数 


 a| 
`d磁盘池`
 a| 
磁盘池在一个托盘中包含的驱动器不超过两个
 a| 
6.



 a| 
`RAID 6`
 a| 
卷组在一个托盘中包含的驱动器不超过两个
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的托盘中
 a| 
3.



 a| 
`RAID 1`
 a| 
RAID 1对中的每个驱动器都必须位于一个单独的托盘中
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现托盘丢失保护。
 a| 
不适用

|===
|===
| 级别 | 抽盒丢失保护的标准 | 所需的最小抽盒数量 


 a| 
`d磁盘池`
 a| 
池中包含所有五个抽盒中的驱动器、每个抽盒中的驱动器数量相等。如果磁盘池包含15、20、25、30、35、 40、45、50、55或60个驱动器。
 a| 
5.



 a| 
`RAID 6`
 a| 
卷组在一个抽屉中包含的驱动器不超过两个。
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的抽盒中。
 a| 
3.



 a| 
`RAID 1`
 a| 
镜像对中的每个驱动器都必须位于一个单独的抽盒中。
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现抽盒丢失保护。
 a| 
不适用

|===


== 命令示例

[listing]
----
create volume driveCount=2 volumeGroupUserLabel="FIPS_VG" raidLevel=1 userLabel="FIPS_V"
----
[listing]
----
driveMediaType=HDD securityType=capable secureDrives=fips
----


== 最低固件级别

7.10增加了RAID级别6功能和`dssPreAllocate`参数。

7.50添加了`securityType`参数。

7.60添加了`drawerLossProtect`参数。

7.75添加`dataAssurance`参数。

8.25添加了`secureDrives`参数。

8.63添加了`resourceProvisioningCapable`参数。

11.70添加 `blockSize` 参数。
