---
permalink: commands-a-z/create-ssdcache.html 
sidebar: sidebar 
keywords: create, ssd, cache 
summary: 'create ssdCache命令使用固态磁盘(SSD)为存储阵列创建读取缓存。' 
---
= 创建SSD缓存
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`create ssdCache`命令可使用固态磁盘(SSD)为存储阵列创建读取缓存。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800和E5700阵列、 只要安装了所有SMcli软件包、



== 角色

要在E2800或E5700存储阵列上执行此命令、您必须具有支持管理员角色。



== 环境

使用高性能SSD缓存读取数据可提高应用程序I/O性能和响应时间、并在不同工作负载之间持续提高性能、尤其是对于高IOP工作负载。SSD缓存可以最大限度地利用昂贵的快速SSD。除了控制器DRAM中的主缓存之外、SSD缓存也起作用。使用控制器缓存时、数据会在主机读取后存储在DRAM中。使用SSD缓存时、数据将从用户指定的基础卷复制、然后缓存在SSD上。



== 语法

[listing, subs="+macros"]
----
create ssdCache userLabel=pass:quotes[_"ssdCacheName"_]
drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,[drawerIDn,_]]pass:quotes[_slotIDn_)]
[updateExistingVolumes=(TRUE|FALSE)]
[securityType=(none|capable|enabled)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`用户标签`
 a| 
要为新SSD缓存命名的名称。将SSD缓存名称用双引号("")括起来。



 a| 
`d` 驱动器
 a| 
要用于创建SSD缓存的驱动器。对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`updateExistingVolumes`
 a| 
此可选参数用于指定是否应为存储阵列中的所有现有卷启用SSD缓存。要为所有现有卷启用SSD缓存、请将此参数设置为`true`。如果稍后要为各个卷启用SSD缓存、请将此参数设置为`false`。默认值为`true`。



 a| 
`securityType`
 a| 
此可选参数用于指定创建SSD缓存时的安全级别。这些设置有效：

* `none`—SSD缓存不安全。
* `Capable`—SSD缓存可以设置安全、但尚未启用安全性。
* `enabled`—SSD缓存已启用安全性。


|===


== 注释：

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

一个存储阵列只能有一个SSD缓存。

只有使用硬盘驱动器创建的卷才能使用SSD缓存。您不能对快照映像启用SSD缓存。

如果SSD缓存中的所有SSD均支持数据保证(Data Assurance、DA)功能、并且已启用DA功能、则会自动为SSD缓存启用DA、并且无法禁用。此外、您不能将不支持DA的SSD添加到启用了DA的SSD缓存中。



== 最低固件级别

7.84.接受采取后续行动

8.20_M3—现在支持FDE驱动器。已添加`securityType`参数。
