---
permalink: commands-a-z/create-volume-diskpool.html 
sidebar: sidebar 
keywords: create, volume, disk pool 
summary: create volume diskPool命令可在现有磁盘池中创建新的标准RAID卷或精简卷。 
---
= 在磁盘池中创建卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`create volume diskPool`命令可在现有磁盘池中创建新的标准RAID卷或精简卷。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
用于在卷组中创建标准RAID卷的某些参数与在磁盘池中创建任何类型的卷不兼容。使用旧脚本在磁盘池中创建卷时、请确保所有参数对磁盘池有效。参数无效会阻止脚本正常运行、并会发布发生原因 错误。

====


== 创建标准卷的语法

[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[dataAssurance=(none|enabled)]
[cacheReadPrefetch=(TRUE | FALSE)]
[raidLevel=(1 | 6)]
[blockSize=requestedBlockSizeValue]
----


== 创建精简配置卷的语法

[listing, subs="+macros"]
----
create volume diskPool=pass:quotes[_"diskPoolName"_
userLabel="_volumeName_"
capacity=_volumeCapacity_]
[thinProvisioned=(TRUE | FALSE)]
[owner=(a|b)]
[mapping=(none|default)]
[dataAssurance=(none|enabled)]
[(existingRepositoryLabel=pass:quotes[_existingRepositoryName_] |
[newRepositoryCapacity=pass:quotes[_newRepositoryCapacityValue_] (KB | MB | GB | TB | Bytes)]
[repositoryMaxCapacity=pass:quotes[_repositoryMaxCapacityValue_](KB|MB|GB|TB|Bytes)]
[warningThresholdPercent=pass:quotes][_warningThresholdPercentValue_]
[repositoryExpansionPolicy=(automatic|manual)]
[cacheReadPrefetch=(TRUE | FALSE)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`diskPool`
 a| 
要在其中创建新卷的磁盘池的名称。将磁盘池名称用双引号("")括起来。



 a| 
`用户标签`
 a| 
要为新卷指定的名称。将卷名称用双引号("")括起来。



 a| 
`容量`
 a| 
要创建的卷的大小。

对于标准RAID卷、将为该卷分配的容量。

对于精简卷、精简卷将公开的虚拟容量值。

大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。以下是语法示例：

* `容量= 500 MB`
* `容量= 2 GB`




 a| 
`精简配置`
 a| 
此参数用于为新卷启用精简配置。要使用精简配置、请将此参数设置为`true`。如果不希望进行精简配置、请将此参数设置为`false`。


NOTE: RAID1级卷不支持精简配置。



 a| 
`所有者`
 a| 
拥有卷的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器如果未指定所有者、则控制器固件将确定所有者。



 a| 
`m设置`
 a| 
使用此参数可以将卷映射到主机。如果要稍后映射、请将此参数设置为`none`。如果要立即映射、请将此参数设置为`default`。卷将映射到有权访问存储池的所有主机。

默认值为 `none` 。



 a| 
`existingRepositoryLabel`
 a| 
此参数用于标识精简卷的现有存储库。存储库卷具有精简卷的物理容量。此参数仅适用于精简配置。如果使用`existingRepositoryLabel`参数、则不能使用`newRepositoryCapacity`参数。



 a| 
`newRepositoryCapacity`
 a| 
此参数用于为精简卷创建新存储库。存储库卷具有精简卷的物理容量。只有在将`th精简 配置`参数的值设置为`true`时、才使用此参数。

大小的单位为`MB`、`GB`或`TB`。以下是语法示例：

* `容量= 500 MB`
* `容量= 2 GB`


默认值为虚拟容量的50%。



 a| 
`repositoryMaxCapacity`
 a| 
此参数用于为精简卷定义存储库的最大容量。只有在将`th精简 配置`参数的值设置为`true`时、才使用此参数。

大小的单位为`MB`、`GB`或`TB`。以下是语法示例：

* `容量= 500 MB`
* `容量= 2 GB`




 a| 
`warningThresholdPercent`
 a| 
收到精简卷接近全满警告警报时精简卷容量的百分比。使用整数值。例如、值70表示70%。

有效值为1到100。

如果将此参数设置为100、则会禁用警告警报。



 a| 
`repositoryExpansionPolicy`
 a| 
此参数会将扩展策略设置为`automatic`或`manual`。将策略从`automatic`更改为`manual`时、最大容量值(配额)将更改为存储库卷的物理容量。



 a| 
`cachedReadPrefetch`
 a| 
用于打开或关闭缓存读取预取的设置。要关闭缓存读取预取、请将此参数设置为`false`。要启用缓存读取预取、请将此参数设置为`true`。



 a| 
`raidLevel`
 a| 
设置要在磁盘池中创建的卷的RAID级别。要指定RAID1、请设置为`1`。要指定RAID6、请设置为`6`。如果未设置RAID级别、则默认情况下会对磁盘池使用RAID6。



 a| 
`块大小`
 a| 
此参数用于设置要创建的卷的块大小。的值 `0` 或者、未设置的参数将使用默认块大小。

|===


== 注释：

每个卷名称必须唯一。您可以对用户标签使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。用户标签最多可以包含30个字符。

对于精简卷、`capacity`参数用于指定卷的虚拟容量、而`repositoryCapacity`参数用于指定创建为存储库卷的卷的容量。使用`existingRepositoryLabel`参数指定现有未使用的存储库卷、而不是创建新卷。

为了在创建精简卷时获得最佳效果、存储库卷必须已存在或必须在现有磁盘池中创建。如果在创建精简卷时未指定某些可选参数、则存储管理软件将尝试创建存储库卷。最理想的候选卷是已存在且在大小要求范围内的存储库卷。下一个最理想的候选卷是在磁盘池可用范围内创建的新存储库卷。

不能在卷组中为精简卷创建存储库卷。

EF300或EF600不支持精简配置卷。



== 数据保证管理

数据保证(Data Assurance、DA)功能可提高整个存储系统的数据完整性。通过DA、存储阵列可以检查在主机和驱动器之间移动数据时可能发生的错误。启用此功能后、存储阵列会向卷中的每个数据块附加错误检查代码(也称为循环冗余检查或CRC)。移动数据块后、存储阵列会使用这些CRC代码来确定传输期间是否发生任何错误。可能损坏的数据既不会写入磁盘、也不会返回到主机。

如果要使用DA功能、请从仅包含支持DA的驱动器的池或卷组开始。然后、创建支持DA的卷。最后、使用支持DA的I/O接口将这些支持DA的卷映射到主机。支持DA的I/O接口包括光纤通道、SAS和基于InfiniBand的iSER (适用于RDMA/IB的iSCSI扩展)。基于以太网的iSCSI或基于InfiniBand的SRP不支持DA。

[NOTE]
====
如果所有驱动器均支持DA、则可以将`dataAssurance`参数设置为`enabled`、然后对某些操作使用DA。例如、您可以创建一个包含支持DA的驱动器的卷组、然后在该卷组中创建一个启用了DA的卷。使用已启用DA的卷的其他操作可以选择支持DA功能。

====
如果将`dataAssurance`参数设置为`enabled`、则候选卷仅会考虑支持数据保证的驱动器、否则将同时考虑支持数据保证和不支持数据保证的驱动器。如果只有数据保证驱动器可用、则会使用已启用的数据保证驱动器创建新卷。



== 最低固件级别

7.83.

8.70添加 `_raidLevel_` 和 `_blockSize` parameters
