---
permalink: commands-a-z/create-snmpuser-username.html 
sidebar: sidebar 
keywords: register, snmpv3 usm, user 
summary: 'create snmpUser username命令可创建一个新的简单网络管理协议(Simple Network Management Protocol、SNMP)用户、并将此新用户注册为SNMP代理的已知实体。如果尝试使用与现有用户相同的名称和引擎ID注册新用户、则此操作将被拒绝。' 
---
= 注册SNMPv3 USM用户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`create snmpUser username`命令可创建一个新的简单网络管理协议(Simple Network Management Protocol、SNMP)用户、并将此新用户注册为SNMP代理的已知实体。如果尝试使用与现有用户相同的名称和引擎ID注册新用户、则此操作将被拒绝。



== 支持的阵列

此命令适用于单个E4000、E2800、E5700、EF600或EF300存储阵列。它不能在E2700或E5600存储阵列上运行。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或支持管理员角色。



== 语法

[source, cli]
----
create snmpUser userName="snmpUserName"
    [engineId=(local | engineId)]
    [authProtocol=(none | sha | sha256 | sha512) authPassword="authPassword"]
    [privProtocol=(none | aes128) privPassword="privPassword"]
----


== Parameters

|===
| 参数 | Description 


 a| 
`用户名`
 a| 
要创建的SNMP USM用户的名称。将SNMP USM用户名用双引号括起来("")



 a| 
`EngineID`
 a| 
用户的权威SNMP引擎ID的标识符。该值可以是"[.code]``local``"以指定本地SNMP代理为权威代理、也可以是十六进制数字字符串以指定远程SNMP代理引擎ID。默认值为"[.code]``local``"。



 a| 
`authProtocol`
 a| 
用户要使用的身份验证协议(HMAC)。该值可以是以下值之一：

* `none`—SNMP消息不进行身份验证(默认)
* `sha`- SHA-1身份验证
* `s 256`- SHA-256身份验证
* `s 512`- SHA-512身份验证




 a| 
`authPassword`
 a| 
用于用户身份验证的密码。如果身份验证协议为"[.code]``sha``"、"[.code]``s 256``"或"[.code]``s 512``"、则必须指定



 a| 
`privProtocol`
 a| 
用户要使用的隐私协议(加密)。该值可以是以下值之一：

* `none`—SNMP消息不加密(默认)
* `aes128`—AES-18加密




 a| 
`privPassword`
 a| 
用于用户隐私/加密的密码。如果隐私协议为"[.code]``aes128``"、则必须指定此参数。

|===


== 最低固件级别

8.72
