---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: 在输入一组未分配的驱动器时、create VolumeGroup命令会创建一个可用容量卷组或一个包含一个卷的卷组。 
---
= 创建卷组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
输入一组未分配的驱动器时、`create VolumeGroup`命令将创建一个可用容量卷组或一个包含一个卷的卷组。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`d` 驱动器
 a| 
要分配给要创建的卷组的驱动器。对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`raidLevel`
 a| 
包含卷的卷组的RAID级别。有效值为`0`、`1`、`3`、`5`或`6`。



 a| 
`用户标签`
 a| 
要为新卷组指定的名称。将卷组名称用双引号("")括起来。



 a| 
`driveMediaType`
 a| 
要用于卷组的驱动器介质类型

如果存储阵列中有多种类型的驱动器介质、则必须使用此参数。

这些驱动器介质有效：

* `HDD`—如果驱动器托盘中有硬盘驱动器、请使用此选项
* `sSD`—如果驱动器托盘中有固态驱动器、请使用此选项
* `unknown`—如果您不确定驱动器托盘中的驱动器介质类型、请使用此选项
* `allMedia`—如果要使用驱动器托盘中的所有类型的驱动器介质、请使用此选项




 a| 
`d驱动器类型`
 a| 
要在卷组中使用的驱动器类型。您不能混用驱动器类型。

如果存储阵列中有多种类型的驱动器、则必须使用此参数。

这些驱动器类型有效：

* `s作为`
* `NVMe4K`


如果未指定驱动器类型、则此代码不会验证指定驱动器是否属于此驱动器类型。



 a| 
`纸架LossProtect`
 a| 
创建卷组时强制实施托盘丢失保护的设置。要强制实施托盘丢失保护、请将此参数设置为`true`。默认值为`false`。



 a| 
`drawerLossProtect`
 a| 
创建卷组时强制实施抽盒丢失保护的设置。要强制实施抽盒丢失保护、请将此参数设置为`true`。默认值为`false`。



 a| 
`securityType`
 a| 
用于指定创建卷组和所有关联卷时的安全级别的设置。这些设置有效：

* `none`—卷组和卷不安全。
* `capable`—卷组和卷可以设置安全设置、但尚未启用安全性。
* `enabled`—卷组和卷已启用安全性。




 a| 
`resourceProvisioningCapable`
 a| 
用于指定是否启用资源配置功能的设置。要禁用资源配置、请将此参数设置为`false`。默认值为`true`。

|===


== 驱动器和卷组

卷组是一组驱动器、这些驱动器由存储阵列中的控制器逻辑分组在一起。卷组中的驱动器数量是RAID级别和控制器固件的限制。创建卷组时、请遵循以下准则：

* 从固件版本7.10开始、您可以创建一个空卷组、以便预留容量供日后使用。
* 不能在一个卷组中混用驱动器类型。
* 不能在一个卷组中混用HDD和SSD驱动器。
* 卷组中的最大驱动器数取决于以下条件：
+
** 控制器的类型
** RAID级别


* RAID级别包括：0、1、3、5和6。
+
** RAID级别为3、RAID级别为5或RAID级别为6的卷组中的驱动器不能超过30个。
** RAID级别为6的卷组必须至少有五个驱动器。
** 如果RAID级别为1的卷组具有四个或更多驱动器、则存储管理软件会自动将该卷组转换为RAID级别10、即RAID级别1 + RAID级别0。


* 要启用托盘/抽盒丢失保护、请参见下表了解其他标准：


|===
| 级别 | 托盘丢失保护标准 | 所需的最小托盘数 


 a| 
`d磁盘池`
 a| 
磁盘池在一个托盘中包含的驱动器不超过两个
 a| 
6.



 a| 
`RAID 6`
 a| 
卷组在一个托盘中包含的驱动器不超过两个
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的托盘中
 a| 
3.



 a| 
`RAID 1`
 a| 
RAID 1对中的每个驱动器都必须位于一个单独的托盘中
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现托盘丢失保护。
 a| 
不适用

|===
|===
| 级别 | 抽盒丢失保护的标准 | 所需的最小抽盒数量 


 a| 
`d磁盘池`
 a| 
池中包含所有五个抽盒中的驱动器、每个抽盒中的驱动器数量相等。如果磁盘池包含15、20、25、30、35、 40、45、50、55或60个驱动器。
 a| 
5.



 a| 
`RAID 6`
 a| 
卷组在一个抽屉中包含的驱动器不超过两个。
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的抽盒中。
 a| 
3.



 a| 
`RAID 1`
 a| 
镜像对中的每个驱动器都必须位于一个单独的抽盒中。
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现抽盒丢失保护。
 a| 
不适用

|===


== 热备件

对于卷组、保护数据的一个重要策略是将存储阵列中的可用驱动器分配为热备用驱动器。热备用磁盘是指不包含任何数据的驱动器、在RAID 1、RAID 3、RAID 5或RAID 6卷组中的驱动器发生故障时、该驱动器在存储阵列中充当备用磁盘。热备用磁盘会为存储阵列添加另一个冗余级别。

通常、热备用驱动器的容量必须等于或大于其所保护驱动器上的已用容量。热备用驱动器必须与所保护的驱动器具有相同的介质类型、相同的接口类型和容量。

如果存储阵列中的某个驱动器发生故障、则热备用磁盘通常会自动替换为故障驱动器、而无需您的干预。如果在驱动器发生故障时有热备用磁盘可用、则控制器会使用冗余数据奇偶校验将数据重建到热备用磁盘上。数据清空支持还允许在软件将驱动器标记为"故障"之前将数据复制到热备用磁盘。

物理更换故障驱动器后、您可以使用以下任一选项还原数据：

更换故障驱动器后、热备用磁盘中的数据将复制回替代驱动器。此操作称为回写。

如果将热备用驱动器指定为卷组的永久成员、则不需要执行回写操作。

卷组的托盘丢失保护和抽盒丢失保护是否可用取决于卷组中驱动器的位置。由于驱动器发生故障以及热备用驱动器的位置、可能会丢失托盘丢失保护和抽盒丢失保护。要确保托盘丢失保护和抽盒丢失保护不受影响、您必须更换故障驱动器以启动回写过程。

存储阵列会自动选择支持数据保证(Data Assurance、DA)的驱动器、以便为启用了DA的卷提供热备用支持。

确保存储阵列中有支持DA的驱动器、用于为启用了DA的卷提供热备用支持。有关支持DA的驱动器的详细信息、请参阅数据保证功能。

支持安全(FIPS和FDE)的驱动器可用作支持安全和不支持安全的驱动器的热备用磁盘。不支持安全的驱动器可以为其他不支持安全的驱动器提供支持、如果卷组未启用安全保护、则可以为支持安全的驱动器提供支持。FIPS卷组只能将FIPS驱动器用作热备用磁盘；但是、您可以将FIPS热备用磁盘用于不支持安全、支持安全和启用安全的卷组。

如果您没有热备用磁盘、则仍可在存储阵列运行期间更换故障驱动器。如果驱动器属于RAID 1、RAID 3、RAID 5或RAID 6卷组、则控制器会使用冗余数据奇偶校验自动将数据重建到替代驱动器上。此操作称为重建。



== 区块大小

区块大小决定了在将数据写入下一个驱动器之前控制器在卷中的单个驱动器上写入的数据块数。每个数据块存储512字节的数据。数据块是最小的存储单元。分段的大小决定了其包含的数据块数。例如、一个8 KB区块可容纳16个数据块。64 KB区块可容纳128个数据块。

为区块大小输入值时、系统会对照控制器在运行时提供的受支持值来检查该值。如果您输入的值无效、则控制器将返回有效值列表。使用单个驱动器处理单个请求会使其他驱动器可以同时处理其他请求。如果卷所在环境中的一个用户正在传输大量数据(例如多媒体)、则在使用一个数据条带处理单个数据传输请求时、性能会最大化。(数据条带是指分段大小乘以卷组中用于数据传输的驱动器数。) 在这种情况下、同一请求会使用多个驱动器、但每个驱动器只访问一次。

为了在多用户数据库或文件系统存储环境中获得最佳性能、请设置区块大小、以最大程度地减少满足数据传输请求所需的驱动器数量。



== 使用提示

[NOTE]
====
您无需为`cachedReadPrefetch`参数或`segmentSize`参数输入值。如果不输入值、则控制器固件会使用`usageHint`参数和`filesystem`作为默认值。为`usageHint`参数输入值和`cachedetch`参数值或为`segmentSize`参数输入值不发生原因 会产生错误。为`cachedReadPrefetch`参数或`segmentSize`参数输入的值优先于`usageHint`参数的值。下表显示了各种使用提示的区块大小和缓存读取预取设置：

====
|===
| 使用提示 | 区块大小设置 | 动态缓存读取预取设置 


 a| 
文件系统
 a| 
128 KB
 a| 
enabled



 a| 
数据库
 a| 
128 KB
 a| 
enabled



 a| 
多媒体
 a| 
256 KB
 a| 
enabled

|===


== 缓存读取预取

缓存读取预取允许控制器将其他数据块复制到缓存中、同时控制器将主机请求的数据块从驱动器读取并复制到缓存中。此操作增加了从缓存满足未来数据请求的可能性。对于使用顺序数据传输的多媒体应用程序来说、缓存读取预取非常重要。`cachedReadPrefetch`参数的有效值为`true`或`false`。默认值为`true`。



== 安全类型

使用`securityType`参数指定存储阵列的安全设置。

要将`securityType`参数设置为`enabled`、必须先创建存储阵列安全密钥。使用`create storageArray securityKey`命令创建存储阵列安全密钥。这些命令与安全密钥相关：

* `创建storageArray securityKey`
* `导出storageArray securityKey`
* `导入storageArray securityKey`
* `set storageArray securityKey`
* `启用VolumeGroup [volumeGroupName]安全性`
* `启用diskPool [diskPoolName]安全性`




== 保护驱动器

支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。使用`secureDrives`参数指定要使用的安全驱动器类型。可以使用的值为`FIPS`和`FDE`。



== 数据保证管理

数据保证(Data Assurance、DA)功能可提高整个存储系统的数据完整性。通过DA、存储阵列可以检查在主机和驱动器之间移动数据时可能发生的错误。启用此功能后、存储阵列会向卷中的每个数据块附加错误检查代码(也称为循环冗余检查或CRC)。移动数据块后、存储阵列会使用这些CRC代码来确定传输期间是否发生任何错误。可能损坏的数据既不会写入磁盘、也不会返回到主机。

如果要使用DA功能、请从仅包含支持DA的驱动器的池或卷组开始。然后、创建支持DA的卷。最后、使用支持DA的I/O接口将这些支持DA的卷映射到主机。支持DA的I/O接口包括光纤通道、SAS和基于InfiniBand的iSER (适用于RDMA/IB的iSCSI扩展)。基于以太网的iSCSI或基于InfiniBand的SRP不支持DA。

[NOTE]
====
如果所有驱动器均支持DA、则可以将`dataAssurance`参数设置为`enabled`、然后对某些操作使用DA。例如、您可以创建一个包含支持DA的驱动器的卷组、然后在该卷组中创建一个启用了DA的卷。使用已启用DA的卷的其他操作可以选择支持DA功能。

====
如果将`dataAssurance`参数设置为`enabled`、则候选卷仅会考虑支持数据保证的驱动器；否则、将同时考虑支持数据保证和不支持数据保证的驱动器。如果只有数据保证驱动器可用、则会使用已启用的数据保证驱动器创建新卷组。



== 最低固件级别

7.10.

7.50添加了`securityType`参数。

7.60会添加`drawerID`用户输入、`driveMediaType`参数和`drawerLossProtect`参数。

7.75添加`dataAssurance`参数。

8.63添加了`resourceProvisioningCapable`参数。
