---
permalink: commands-a-z/delete-volume-from-disk-pool.html 
sidebar: sidebar 
keywords: delete, volume, command, normal, thin, disk pool, roles, support 
summary: delete volume命令可从磁盘池中删除普通卷或精简卷。 
---
= 从磁盘池中删除卷 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`delete volume`命令可从磁盘池中删除普通卷或精简卷。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您也可以使用此命令删除与卷相关的任何计划。删除此计划时、不会删除此卷。

[]
====
*可能会损坏存储阵列配置*-运行此命令后、卷中的所有数据都将丢失。

====


== 语法

[source, cli, subs="+macros"]
----
delete (allVolumes |
volume [volumeName] |
pass:quotes[volumes ["_volumeName1_" ... "_volumeNameN_"]]
[force=(TRUE | FALSE)]
[schedule]
[retainRepositoryMembers=(TRUE | FALSE)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`所有卷`
 a| 
此参数将删除磁盘池上的所有卷。



 a| 
`卷`
 a| 
要删除的特定卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或仅包含数字、则必须将卷名称用双引号("")括在方括号内。



 a| 
`卷`
 a| 
要删除的多个卷的名称。使用以下规则输入卷的名称：

* 请将所有名称用方括号([])括起来。
* 使用空格分隔每个名称。




 a| 
`强制`
 a| 
使用此参数可强制立即删除卷、即使控制器正在执行其他操作也是如此。要立即强制删除卷、请将此参数设置为`true`。要等待控制器完成其他操作、请勿使用此参数或将此参数设置为`false`。



 a| 
`s计划`
 a| 
此参数将删除与特定磁盘池卷相关的任何计划。仅删除计划、磁盘池卷仍会保留。



 a| 
`re存储库成员`
 a| 
删除精简卷时、默认情况下会删除关联的存储库卷。但是、如果将`retainRepositoryMembers`设置为`true`、则会保留存储库卷。对于普通卷、此参数不起作用。

|===


== 注释：

使用`allVolumes`参数时、此命令将删除卷、直到删除所有卷或遇到错误为止。如果遇到错误、此命令不会尝试删除其余卷。可以从不同的卷组中删除卷。如果将`removeVolumeGroup`参数设置为`true`、则所有变为空的卷组都将被删除。



== 最低固件级别

7.83.
