---
permalink: commands-a-z/diagnose-controller.html 
sidebar: sidebar 
keywords: diagnose, controller, command, run, diagnostic, tests, arrays, roles, context 
summary: diag controller命令可对控制器运行诊断测试。 
---
= 诊断控制器 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`diagnose controller`命令可对控制器运行诊断测试。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

诊断测试包括环回测试、在这些测试中、数据会写入驱动器并从驱动器中读取。



== 语法

[source, cli, subs="+macros"]
----
diagnose controller [(a| b)]
loopbackDriveChannel=(allchannels | (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8))
testID=(1 | 2 | 3 | discreteLines)
pass:quotes[[patternFile="_filename_"]]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`控制器`
 a| 
要运行诊断测试的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器将控制器标识符括在方括号()中。如果不指定控制器、则存储管理软件将返回语法错误。



 a| 
`loopbackDriveChannel`
 a| 
要运行诊断测试的驱动器通道。您可以选择对所有通道运行诊断、也可以选择运行诊断的特定通道。如果选择特定通道、则驱动器通道的有效值为`1`、`2`、`3`、`4`、`5`、 `6`、`7`或`8`。



 a| 
`testID`
 a| 
要运行的诊断测试的标识符。标识符和相应的测试如下所示：

* `1`—读取测试
* `2`—写入测试
* `3`—数据环路测试
* `discreteLines`—离散线诊断测试




 a| 
`模式文件`
 a| 
包含要用作测试数据的数据模式的文件路径和文件名。将数据模式的文件名用双引号("")括起来。例如：

`file="C：\Program Files\cli\sup\patfile.txt"`

|===


== 注释：

运行数据回路测试时、您可以选择指定包含数据模式的文件。如果未指定文件、则控制器固件将提供默认模式。

离散线是指在控制器托盘中的两个控制器之间连接的控制线和状态线通过离散线诊断测试、每个控制器可以检查是否可以在备用控制器的控制输入处观察到控制信号过渡。每次重新启动或每次重置控制器后、离散线诊断测试都会自动运行。在更换了未通过初始离散线诊断测试的组件后、您可以运行离散线诊断测试。离散线诊断测试将返回以下消息之一：

* 当离散线诊断测试成功运行时、将显示以下消息：
+
[listing]
----
The controller discrete lines successfully passed the diagnostic
test. No failures were detected.
----
* 如果离散线诊断测试失败、则会显示以下消息：
+
[listing]
----
One or more controller discrete lines failed the diagnostic test.
----
* 如果命令行界面无法运行离散线诊断测试、则命令行界面返回错误270、这意味着离散线诊断测试无法启动或完成。




== 最低固件级别

6.10增加了读取测试、写入测试和数据环路测试。

6.14增加了离散线诊断测试。

7.30添加更新后的驱动器通道标识符。
