---
permalink: commands-a-z/diagnose-controller-iscsihostport.html 
sidebar: sidebar 
keywords: diagnose, controller, hostport, command, diagnostic, tests, copper, cable, host, interface, cards, support, roles 
summary: diag controller iscsiHostPort命令可对iSCSI主机接口卡和控制器之间的铜缆运行诊断测试。 
---
= 诊断控制器iSCSI主机缆线
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`diagnose controller iscsiHostPort`命令可对iSCSI主机接口卡和控制器之间的铜缆运行诊断测试。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您可以对选定端口或所有端口运行诊断。这些端口必须能够支持缆线诊断。如果端口不支持缆线诊断、则会返回错误。



== 语法

[listing]
----
diagnose controller [(a|b)]
iscsiHostPort ([all] | [portLabel])
testID=cableDiagnostics
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`控制器`
 a| 
要运行缆线诊断测试的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器将控制器标识符括在方括号()中。如果不指定控制器、则存储管理软件将返回语法错误。



 a| 
`iscsiHostPort`
 a| 
要运行诊断测试的iSCSI主机端口。您可以在所有iSCSI主机端口上运行诊断程序、也可以在特定iSCSI主机端口上运行诊断程序。

有关详细信息，请参见以下内容：

<<Identifying an iSCSI host port label,"确定iSCSI主机端口标签">>



 a| 
`testID`
 a| 
要运行的诊断测试的标识符。对于此诊断测试、唯一的选择是`cableDiagnostics`。

|===


== 确定iSCSI主机端口标签

您必须为主机端口指定一个标签。请按照以下步骤指定主机端口标签：

. 如果您不知道iSCSI主机端口的端口标签、请运行`show controller`命令。
. 在结果的主机接口部分中、找到要选择的主机端口。
+
[NOTE]
====
端口标签是为`Port`字段返回的完整值。

====
. 将端口标签的整个值用引号和方括起来："portLabel"。例如、如果端口标签为`Ch2`、请按如下所示指定iSCSI主机端口：
+
[listing]
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
如果您使用的是Windows命令行、并且标签包含管道(我们)、则应转义此字符(使用｛caret｝)；否则、此字符将被解释为命令。例如、如果端口标签为`e0b\0b`、请按如下所示指定iSCSI主机端口：

====
+
[listing]
----
iscsiHostPort[\"e0b^|0b\"]
----


[NOTE]
====
为实现向后兼容性、E2700、E5600或EF560控制器(以及以前其他几代E系列或EF系列控制器)仍可使用带花括号(而不是引号和花括号)的iscsiPortNumber。对于这些控制器、iscsiPortNumber的有效值如下所示：

* 对于具有集成主机端口的控制器、编号为3、4、5或6。
* 对于仅在主机接口卡上具有主机端口的控制器、编号为1、2、3或4。


以下是先前语法的示例：

[listing]
----
iscsiHostPort[3]
----
====


== 注释：

运行缆线诊断测试时、固件将返回以下信息：

* *主机端口*：运行诊断测试的端口。
* * HIC*：与此端口关联的主机接口卡。
* 运行测试的日期和时间。
* *状态*：
+
** *正常*：所有缆线对均正常、没有任何故障。
** *打开*：四对缆线中的一个或多个已打开。
** *短*：四对缆线中的一个或多个发生短接。
** *不完整*：四个对中的一个或多个返回的测试结果不完整或无效。


* *长度*：电缆长度以米为单位列出、并返回有关电缆的以下信息：
+
** 如果缆线状态为OK、则返回缆线对的大致长度。电缆对的长度显示为范围(L1-L2)、这是电缆对最短和最长的长度。
** 如果缆线状态为"打开"或"短"、则表示与缆线对中故障的大致距离。如果发生一个故障、则会报告该缆线对的长度。如果出现多个故障、则返回的信息既是故障的最短长度、也是最长长度。这些长度将作为一个范围(L1-L2)列出、其中L1<L2。
** 如果缆线状态为不完整、则返回的信息为固件可以成功测试的最短和最长缆线对的长度。有效缆线对的长度列为范围(L1-L2)、其中L1<L2。


* 注册电缆诊断注册表的值。这些值采用十六进制格式：
+
** 两个字节表示组合的缆线状态(每个端口四个位)。
** 四个双字节数字显示每个通道的长度。






== 最低固件级别

7.77

8.10修改了iSCSI主机端口的编号系统。
