---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: download drive firmware命令可将固件映像下载到驱动器。 
---
= 下载驱动器固件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`dload drive firmware`命令可将固件映像下载到驱动器。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或支持管理员角色。



== 环境

[CAUTION]
====
*可能会损坏存储阵列配置*-如果驱动器固件下载不正确、可能会损坏驱动器或丢失数据访问。

====
[NOTE]
====
已弃用`content`参数。请改用`firmware`参数。

====
此命令用于一次仅将固件映像下载到一个驱动器型号。如果在脚本中使用此命令、请确保此命令仅使用一次。如果您多次使用此命令、操作可能会失败。您可以使用`download storageArray driveFirmware`命令一次性将固件映像下载到存储阵列中的所有驱动器。



== 语法

[listing, subs="+macros"]
----
pass:quotes[download (drive \[_trayID_,[_drawerID,_]pass:quotes[_slotID_] \| drives\ pass:quotes[[_trayID1_,[_drawerID1_,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
 [online|offline] firmware file="filename"
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`d`驱动器`或`d驱动器
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`联机`或`脱机`
 a| 
选择`online`执行联机驱动器固件下载、否则选择`offline`。默认值为`offline`。



 a| 
`文件`
 a| 
包含固件映像的文件的文件路径和文件名。将固件映像的文件路径和文件名用双引号("")括起来。例如：

`file="C：\Program Files\CLI\dnld\drvfrm.dpl"`

有效文件名的扩展名为`。lp`。



 a| 
`固件`
 a| 
指示下载控制器固件。

|===


== 注释：

尝试下载驱动器固件之前、请采取以下预防措施：

* 除非您使用`online`参数、否则请在下载固件映像之前停止存储阵列的所有I/O活动。不带`online`参数的`download drive firmware`命令会阻止所有I/O活动、直到下载完成或失败为止；但是、作为预防措施、请确保停止可能影响驱动器的所有I/O活动。
* 确保固件映像文件与驱动器托盘兼容如果下载的固件映像文件与选定驱动器托盘不兼容、则驱动器托盘可能会变得不可用。
* 下载驱动器固件时、请勿对存储阵列进行任何配置更改。尝试更改配置可能发生原因 会使固件下载失败、并使选定驱动器无法使用。
* 对于使用此命令发出的联机驱动器固件更新请求、控制器将从将新固件下载到的驱动器列表中删除RAID 0卷组驱动器。单个驱动器返回状态将设置为`never attempted with reason`。


将固件下载到驱动器时、必须提供系统上存储的固件映像的完整路径和文件名。

在存储阵列中的所有驱动器上安装固件之前、您可以使用`download drive`命令测试一个驱动器上的固件。下载将返回以下状态之一：

* 成功
* 失败、但有原因
* 无故尝试


`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 最低固件级别

7.60添加了`drawerID`用户输入。

8.25添加了`online`参数。
