---
permalink: commands-a-z/download-tray-firmware-file.html 
sidebar: sidebar 
keywords: download, tray, firmware, file, command, environmental, service, module, array, role, context 
summary: 'download tray firmware file命令可下载环境服务模块(ESM)固件。' 
---
= 下载环境卡固件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
命令`download tray firmware file`可下载环境服务模块(ESM)固件。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或支持管理员角色。



== 环境

[IMPORTANT]
====
在由System Manager管理的双工系统(例如E2800)上、控制器上运行的是IOM自动同步服务、该服务会自动将IOM固件与控制器上加载的SANtricity 操作系统捆绑包中的版本同步。如果您不希望还原IOM固件以使其与控制器上加载的版本匹配、则需要禁用此服务。可以使用System Manager或REST API暂停IOM自动同步服务。暂停此服务时、请注意、启用自动同步可确保IOM固件为最新版本。

====


== 语法

[listing, subs="+macros"]
----
download (allTrays | tray [trayID])
pass:quotes[firmware file="_filename_"]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`所有托盘`
 a| 
此参数会将新固件下载到存储阵列中的所有兼容托盘。您选择的固件包将确定哪些托盘是兼容的。已跳过不兼容的托盘。不会显示有关不兼容托盘的错误消息。



 a| 
`托盘`
 a| 
包含要将新固件加载到的ESM卡的驱动器托架。托盘ID值为`0`到`99`。将托盘ID值用方括号()括起来。

[NOTE]
====
托盘ID不能以零为前位。例如、如果显示的托盘ID为"02"、则此命令要求将其指定为"2"、而不是"02"。

====


 a| 
`文件`
 a| 
包含固件映像的文件的文件路径和文件名。将固件映像的文件路径和文件名用双引号("")括起来。例如：

`file="C：\Program Files\CLI\dnld\esmfrm.esm"`

有效文件名的扩展名为`。esm`。

|===


== 注释：

`tray`参数可将新固件下载到特定驱动器托盘如果需要将新固件下载到多个驱动器托盘、但不需要下载所有驱动器托盘、则必须为每个驱动器托盘输入此命令



== 最低固件级别

5.20
