---
permalink: commands-a-z/recover-volume.html 
sidebar: sidebar 
keywords: recover, raid, volume 
summary: recover volume命令将使用给定属性创建RAID卷、而不会初始化驱动器上的任何用户数据区域。 
---
= 恢复RAID卷
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`re封面卷`命令可创建具有给定属性的RAID卷、而无需初始化驱动器上的任何用户数据区域。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

参数值来自存储阵列的恢复配置文件数据文件(`recovery-profile.csv`)。您可以使用此命令在现有卷组中创建恢复卷或创建新卷组。

[NOTE]
====
您只能从命令行运行此命令。您不能从GUI脚本编辑器运行此命令。您不能使用存储管理GUI来恢复卷。

====
[NOTE]
====
不能对动态磁盘池(DDP)卷使用此命令。

====


== 语法

[listing, subs="+macros"]
----
recover volume (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_])) |
(drives=pass:quotes[_trayID1_,pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,_]pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])) |
volumeGroup=pass:quotes[_volumeGroupName_]))
[newVolumeGroup=pass:quotes[_volumeGroupName_]]
userLabel=pass:quotes["_volumeName_" volumeWWN="_volumeWWN_"
capacity=_volumeCapacity_
offset=_offsetValue_
raidLevel=(0 | 1 | 3 | 5 | 6)
segmentSize=_segmentSizeValue_
dssPreAllocate=(TRUE | FALSE)
SSID=_subsystemVolumeID_]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
[hostUnmapEnabled=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== Parameters

|===
| 参数 | Description 


 a| 
`d`驱动器`或`d驱动器
 a| 
要分配给要恢复的卷所在卷组的驱动器。对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`VolumeGroup`
 a| 
要在其中创建卷的现有卷组的名称。(要确定存储阵列中卷组的名称、请运行`show storageArray profile`命令。)



 a| 
`newVolumeGroup`
 a| 
要为新卷组指定的名称。将新卷组名称用双引号("")括起来。



 a| 
`用户标签`
 a| 
要恢复的卷的名称。用户标签分为两部分：

* 卷名称。将卷名称用双引号("")括起来。
* 卷的全球通用名称`volumeWWN`、采用16字节标识符的形式、例如60080E50017B43200000049887D77。将标识符用双引号("")括起来。


您必须同时输入卷名称和卷的全球通用名称。必须先输入卷名称。例如：

[listing]
----
userLabel="engdata"
volumeWWN=60080E500017B4320000000049887D77
----


 a| 
`容量`
 a| 
要添加到存储阵列的卷的大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。



 a| 
`偏移`
 a| 
从卷组开始到引用卷开始的块数。



 a| 
`raidLevel`
 a| 
包含驱动器的卷组的RAID级别。有效值为`0`、`1`、`3`、`5`或`6`。



 a| 
`segmentSize`
 a| 
在将数据写入下一个驱动器之前、控制器在卷组中的单个驱动器上写入的数据量(以KB为单位)。有效值为`8`、`16`、`32`、`64`、`128`、 `256`或`512`。



 a| 
`dssPreAllocate`
 a| 
用于打开或关闭为将来的区块大小更改分配卷存储容量的设置。要启用分配、请将此参数设置为`true`。要关闭分配、请将此参数设置为`false`。



 a| 
`sSID`
 a| 
卷的存储阵列子系统标识符。使用`show volume`命令确定存储阵列子系统标识符。



 a| 
`所有者`
 a| 
拥有卷的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器如果未指定所有者、则控制器固件将确定所有者。



 a| 
`cachedReadPrefetch`
 a| 
用于打开或关闭缓存读取预取的设置。要关闭缓存读取预取、请将此参数设置为`false`。要启用缓存读取预取、请将此参数设置为`true`。



 a| 
`hostUnmapEnabled`
 a| 
如果此参数设置为`True`、则允许主机问题描述 将命令取消映射到卷。只有在资源配置的卷上才允许使用unmap命令。



 a| 
`块大小`
 a| 
此设置为卷块大小(以字节为单位)。

|===


== 注释：

存储管理软件会收集受监控存储阵列的恢复配置文件、并将这些配置文件保存在存储管理工作站上。

`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。

如果您尝试使用`drive`参数或`drives`参数恢复卷、并且驱动器处于未分配状态、则控制器会自动创建一个新的卷组。使用`newVolumeGroup`参数指定新卷组的名称。

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

`owner`参数用于定义拥有卷的控制器。卷的首选控制器所有权是当前拥有卷组的控制器。



== 预先分配存储容量

使用`dssPreAllocate`参数可以在卷中分配容量、以存储用于重建卷的信息。将`dssPreallocate`参数设置为`true`时、控制器固件中的存储空间分配逻辑会预先分配卷中的空间、以供将来更改区块大小时使用。预先分配的空间是允许的最大分段大小。要正确恢复无法从控制器数据库检索的卷配置、必须使用`dssPreAllocate`参数。要关闭预分配功能、请将`dssPreAllocate`设置为`false`。



== 区块大小

区块大小决定了在将数据写入下一个驱动器之前控制器在卷中的单个驱动器上写入的数据块数。每个数据块存储512字节的数据。数据块是最小的存储单元。分段的大小决定了其包含的数据块数。例如、一个8 KB区块可容纳16个数据块。64 KB区块可容纳128个数据块。

为区块大小输入值时、系统会对照控制器在运行时提供的受支持值来检查该值。如果您输入的值无效、则控制器将返回有效值列表。使用单个驱动器处理单个请求会使其他驱动器可以同时处理其他请求。

如果卷所在环境中的一个用户正在传输大量数据(例如多媒体)、则在使用一个数据条带处理单个数据传输请求时、性能会最大化。(数据条带是指分段大小乘以卷组中用于数据传输的驱动器数。) 在这种情况下、同一请求会使用多个驱动器、但每个驱动器只访问一次。

为了在多用户数据库或文件系统存储环境中获得最佳性能、请设置区块大小、以最大程度地减少满足数据传输请求所需的驱动器数量。



== 缓存读取预取

缓存读取预取允许控制器将其他数据块复制到缓存中、同时控制器将主机请求的数据块从磁盘读取和复制到缓存中。此操作增加了从缓存满足未来数据请求的可能性。对于使用顺序数据传输的多媒体应用程序来说、缓存读取预取非常重要。您使用的存储阵列配置设置决定了控制器读取到缓存中的其他数据块的数量。`cachedReadPrefetch`参数的有效值为`true`或`false`。



== 最低固件级别

5.43

7.10增加了RAID 6级别功能和`newVolumeGroup`参数。

7.60添加了`drawerID`用户输入。

7.75添加`dataAssurance`参数。

8.78添加了`hostUnmapEnabled`参数。

11.70.1添加了`blocksize`参数。
