---
permalink: commands-a-z/recover-sasport-miswire.html 
sidebar: sidebar 
keywords: recover, sas, port, mis-wire 
summary: recover sasPort miswire命令告知控制器已采取更正操作、以便从连线错误的情况中恢复。 
---
= 恢复 SAS 端口错误接线 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`re封面sasPort miswire`命令告诉控制器、已采取更正操作从连线错误的情况中恢复。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或支持管理员角色。



== 环境

然后、控制器可以重新启用任何因检测到连线错误而被禁用的SAS端口。更正任何SAS连线错误情况后、运行此命令。

SAS连线错误的情况可能为以下情况之一：

* SAS拓扑无效
* 控制器主机端口到扩展托盘的连接
* 启动程序到驱动器拓扑连接
* ESM连线错误




== 语法

[source, cli]
----
recover sasPort miswire
----


== Parameters

无



== 注释：

如果检测到连线错误、则控制器固件将报告以下内容：

* 指示存在连线错误情况的严重MEL事件
* 出现"`需要注意`"情况
* 指示连线错误的恢复操作


此外、控制器还会报告因布线不当而只有一条访问路径的驱动器、ESM和托盘的"`冗余丢失`"信息(例如、存储阵列中的后两个托盘)。冗余丢失信息并不是SAS拓扑特有的。

以下是与SAS端口连线错误相关的事件通知：

* 检测到SAS连线错误
* HBA已连接到驱动器通道
* 驱动器通道交叉连接


如果出现连线不当的情况、控制器会禁用一个或多个SAS端口来保护SAS域的完整性、请执行以下步骤从该情况中恢复：

. 确定哪个缆线位于错误的位置并将其拔下。如果最后一次采取的操作是安装新的缆线、则最有可能采用这种方法。如果不是、请查找连接到非存储阵列成员设备的缆线或通道之间的缆线。恢复事件应报告检测到连线错误的通道、可能还会报告托盘
. 拔下缆线或将缆线移至正确位置后、运行`re封面sasPort misire`命令。控制器将尝试重新启用检测到连线错误时禁用的任何SAS端口。
. 如果您为修复布线不当而移除或移动的缆线仅允许控制器访问已禁用的端口、则控制器将无法重新启用已禁用的SAS端口。要完成恢复、必须重新启动存储阵列中的托盘。




== 最低固件级别

8.10
