---
permalink: commands-a-z/recreate-storagearray-mirrorrepository.html 
sidebar: sidebar 
keywords: recreate, synchronous, mirror, repository, volume 
summary: 'recreate storageArray mirrorRepository命令可使用为先前镜像存储库卷定义的参数创建新的同步镜像存储库卷(也称为镜像存储库卷)。' 
---
= 重新创建同步镜像存储库卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`recreate storageArray mirrorRepository`命令可使用为先前镜像存储库卷定义的参数创建新的同步镜像存储库卷(也称为镜像存储库卷)。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800和E5700阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800或E5700存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
对于固件版本7.80、不再使用`recreate storageArray mirrorRepository`命令。GUI或CLI不再支持此命令。如果您尝试运行此命令、则会返回一条错误消息、指示不再支持此功能、并且不会对指定的远程镜像存储库进行任何更改。

====
基本要求是、您先前已创建镜像存储库卷。使用此命令时、您可以通过以下三种方式之一定义镜像存储库卷：用户定义的驱动器、用户定义的卷组或用户定义的镜像存储库卷驱动器数量。如果您选择定义多个驱动器、则控制器固件会选择要用于镜像存储库卷的驱动器。



== 语法(用户定义的驱动器)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_,pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1
... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN_])
[trayLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== 语法(用户定义的卷组)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryVolumeGroup=pass:quotes[_volumeGroupName_
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== 语法(用户定义的驱动器数)

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
(
  [driveMediaType=(HDD | SSD | unknown | allMedia)] |
  [driveType=(SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel="userLabel"] |
[trayLossProtect=(TRUE | FALSE)] |
[drawerLossProtect=(true|false)] |
[dataAssurance=(none | enabled)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`repositoryRAIDLevel`
 a| 
镜像存储库卷的RAID级别。有效值为`1`、`3`、`5`或`6`。



 a| 
`repositoryDrives`
 a| 
要用于镜像存储库卷的驱动器。抽盒ID值为`1`到`5`。插槽ID值为`1`到`24`。将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。使用以下规则输入存储库卷的名称：

对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。

* 将所有托盘ID值、抽盒ID值和插槽ID值括在方括号()中。
* 使用逗号分隔托盘ID值、抽盒ID值和插槽ID值。
* 使用空格分隔每个驱动器位置。




 a| 
`repositoryVolumeGroup`
 a| 
镜像存储库卷所在的卷组的名称。



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
要为镜像存储库卷所在的新卷组指定的名称。将卷组名称用双引号("")括起来。



 a| 
`FreeCapacityArea`
 a| 
现有卷组中要用于重新创建镜像存储库卷的可用空间的索引编号。可用容量是指卷组中现有卷之间的可用容量。例如、卷组可能具有以下区域：卷1、可用容量、卷2、可用容量、卷3、 可用容量。要使用卷2之后的可用容量、应指定：

[listing]
----
freeCapacityArea=2
----
运行`show VolumeGroup`命令以确定是否存在可用容量区域。



 a| 
`repositoryDriveCount`
 a| 
要用于镜像存储库卷的未分配驱动器的数量。



 a| 
`driveMediaType`
 a| 
要检索其信息的驱动器介质类型。以下值是有效的驱动器介质类型：

* `HDD`表示驱动器托盘中有硬盘驱动器
* `sSD`表示驱动器托盘中有固态磁盘
* `unknown`表示您确信驱动器托盘中的驱动器介质类型
* `所有介质`表示驱动器托盘中具有所有类型的介质




 a| 
`d驱动器类型`
 a| 
要用于镜像存储库卷的驱动器类型。您不能混用驱动器类型。

如果存储阵列中有多种类型的驱动器、则必须使用此参数。

有效驱动器类型为：

* `s作为`
* `NVMe4K`


如果未指定驱动器类型、则此命令将默认为任何类型。



 a| 
`纸架LossProtect`
 a| 
创建镜像存储库卷时用于强制实施托盘丢失保护的设置。要强制实施托盘丢失保护、请将此参数设置为`true`。默认值为`false`。



 a| 
`drawerLossProtect`
 a| 
用于在创建镜像存储库卷时强制实施抽盒丢失保护的设置。要强制实施抽盒丢失保护、请将此参数设置为`true`。默认值为`false`。

|===


== 注释：

如果为镜像存储库卷输入的存储空间值太小、则控制器固件将返回一条错误消息、其中将说明镜像存储库卷所需的空间量。命令不会尝试更改镜像存储库卷。您可以使用错误消息中有关镜像存储库卷存储空间值的值重新输入命令。

`repositoryDrives`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。

分配驱动器时、如果将`tray LossProtect`参数设置为`true`并从任意一个托盘中选择了多个驱动器、则存储阵列将返回错误。如果将`tray LossProtect`参数设置为`false`、则存储阵列将执行操作、但您创建的镜像存储库卷可能无法保护托盘丢失。

在控制器固件分配驱动器时、如果将`tray LossProtect`参数设置为`true`、则如果控制器固件无法提供驱动器、从而导致新的镜像存储库卷具有托盘丢失保护、则存储阵列将返回错误。如果将`tray LossProtect`参数设置为`false`、则存储阵列会执行此操作、即使这意味着镜像存储库卷可能没有托盘丢失保护。



== 数据保证管理

数据保证(Data Assurance、DA)功能可提高整个存储系统的数据完整性。通过DA、存储阵列可以检查在主机和驱动器之间移动数据时可能发生的错误。启用此功能后、存储阵列会向卷中的每个数据块附加错误检查代码(也称为循环冗余检查或CRC)。移动数据块后、存储阵列会使用这些CRC代码来确定传输期间是否发生任何错误。可能损坏的数据既不会写入磁盘、也不会返回到主机。

如果要使用DA功能、请从仅包含支持DA的驱动器的池或卷组开始。然后、创建支持DA的卷。最后、使用支持DA的I/O接口将这些支持DA的卷映射到主机。支持DA的I/O接口包括光纤通道、SAS和基于InfiniBand的iSER (适用于RDMA/IB的iSCSI扩展)。基于以太网的iSCSI或基于InfiniBand的SRP不支持DA。

[NOTE]
====
如果所有驱动器均支持DA、则可以将`dataAssurance`参数设置为`enabled`、然后对某些操作使用DA。例如、您可以创建一个包含支持DA的驱动器的卷组、然后在该卷组中创建一个启用了DA的卷。使用已启用DA的卷的其他操作可以选择支持DA功能。

====
如果将`dataAssurance`参数设置为`enabled`、则候选卷仅会考虑支持数据保证的驱动器；否则、将同时考虑支持数据保证和不支持数据保证的驱动器。如果只有数据保证驱动器可用、则会使用已启用的数据保证驱动器创建新卷组。



== 最低固件级别

6.10

7.10增加了RAID级别6功能

7.75添加`dataAssurance`参数。

8.60会添加`driveMediaType`、`repositoryVolumeGroupUserLabel`和`drawerLossProtect`参数。
