---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: set diskPool命令可通过从池中逻辑删除驱动器来减少磁盘池的容量。 
---
= 减少磁盘池容量 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set diskPool`命令可通过从池中逻辑删除驱动器来减少磁盘池的容量。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

此命令使用动态容量缩减(DCR)功能、通过该功能、您可以从磁盘池中删除选定驱动器、并根据需要重新使用已删除的驱动器。

在一个DCR操作中、最多可以从磁盘池中删除60个驱动器。您不能将磁盘池减小到低于最小磁盘池大小。



== 语法

[source, cli, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== 参数

|===
| 参数 | Description 


 a| 
`diskPool`
 a| 
要减少容量的磁盘池的名称。将磁盘池名称用方括号([])括起来。



 a| 
`re移动驱动器`
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。

|===


== 注释：

每个磁盘池名称必须唯一。您可以对用户标签使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。用户标签最多可以包含30个字符。

如果需要创建单独的组或从存储阵列中删除不需要的容量、则可能需要从磁盘池中删除选定驱动器。已删除的驱动器将成为未分配的驱动器、其上的数据将在磁盘池中的其余驱动器之间重新分布。磁盘池的容量会根据要删除的驱动器的容量减少。从磁盘池中删除驱动器始终作为后台任务执行、在此操作期间、卷仍可完全访问。删除操作的进度将作为长时间运行操作状态的一部分进行报告。

如果磁盘池中的驱动器没有足够的可用容量来存储从磁盘池中删除的驱动器上的所有数据、则此命令将失败。磁盘池中的预留容量可用于存储从磁盘池中删除的驱动器上的数据。但是、如果预留容量降至严重阈值以下、则会将严重事件写入主要事件日志。

减小磁盘池大小可能会减少所需的预留容量。在某些情况下、为了降低此命令失败的可能性、请在运行此命令之前减少您的预留容量、以便增加可用于磁盘池数据的空间量。

控制器固件可确定您可以删除的驱动器数量、然后您可以选择要删除的特定驱动器。控制器固件会根据在其余驱动器之间重新分配数据所需的可用空间量来计算、而不会占用为重建预留的任何容量。如果磁盘池的可用容量已低于预留重建驱动器容量、则控制器不允许开始执行DCR操作。

DCR操作可能会导致配置的容量超过一个或两个池利用率阈值。如果是、则会发出正常阈值警报。



== 最低固件级别

8.10
