---
permalink: commands-a-z/remove-lunmapping.html 
sidebar: sidebar 
keywords: remove, volume, lun map 
summary: 'remove lunMapping命令可从一个或多个卷中删除逻辑单元号(LUN)或命名空间ID (NSID)映射。' 
---
= 删除卷LUN映射
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`remove lunMapping`命令可从一个或多个卷中删除逻辑单元号(LUN)或命名空间ID (NSID)映射。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[listing, subs="+macros"]
----
remove (volume pass:quotes[[_"volumeName"_]] | accessVolume) lunMapping
(host=pass:quotes[_"hostName_" | hostGroup=(_"hostGroupName"_] | defaultGroup)
----


== 从多个卷LUN或NSID映射中删除LUN或NSID映射的语法

[listing, subs="+macros"]
----
remove (allVolumes | volumes pass:quotes[[_volumeName1 ... volumeNameN_]])
lunMapping
----


== Parameters

|===
| 参数 | Description 


 a| 
`卷`
 a| 
要从中删除LUN或NSID映射的卷的名称。将卷名称双引号("")括在方括号([])内。



 a| 
`访问卷`
 a| 
此参数将删除访问卷。



 a| 
`所有卷`
 a| 
此参数将从所有卷中删除LUN映射。



 a| 
`卷`
 a| 
要从中删除LUN或NSID映射的多个卷的名称。使用以下规则输入卷的名称：

* 请将所有名称用方括号([])括起来。
* 使用空格分隔每个名称。


如果卷名称包含特殊字符或仅包含数字、请使用以下规则输入名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`主机`
 a| 
卷映射到的主机的名称。将主机名用双引号("")括起来。

只有在从一个卷中删除LUN或NSID映射时、此参数才有效。



 a| 
`hostGroup`
 a| 
包含卷映射到的主机的主机组的名称。将主机组名称用双引号("")括起来。`d默认组`值是包含卷映射到的主机的主机组。

只有在从一个卷中删除LUN或NSID映射时、此参数才有效。

|===


== 注释：

访问卷是SAN环境中用于存储管理软件与存储阵列控制器之间通信的卷。访问卷使用LUN或NSID地址并占用20 MB的存储空间、而这些空间不可用于应用程序数据存储。只有带内受管存储阵列才需要访问卷。

[NOTE]
====
*删除访问卷可能会损坏您的配置*-代理使用这些访问卷与存储阵列进行通信。如果从运行代理的主机中删除存储阵列的访问卷映射、则存储管理软件将无法再通过代理管理存储阵列。

====
指定非访问卷或访问卷时、必须使用`host`参数和`hostGroup`参数。使用`allVolumes`参数或`volumes`参数时、脚本引擎会忽略`host`参数或`hostGroup`参数。



== 最低固件级别

6.10
