---
permalink: commands-a-z/reset-drive.html 
sidebar: sidebar 
keywords: reset, drive 
summary: reset drive命令会对卷组或磁盘池中的驱动器重新加电、以帮助恢复行为不一致或不最佳的驱动器。 
---
= 重置驱动器 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`reset drive`命令可以对卷组或磁盘池中的驱动器重新加电、以帮助恢复行为不一致或不最佳的驱动器。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

通过重新启动驱动器、您可以清除发生原因 行为不一致或非最佳的一些错误。这样可以避免在驱动器仅发生瞬时非致命错误且驱动器仍可正常运行时更换驱动器。以这种方式重置驱动器可减少中断并避免更换驱动器。

如果无法通过重新启动驱动器来解决此问题、则会从驱动器复制数据、并关闭驱动器以进行更换。

[NOTE]
====
此命令不能用于由pliant制造的SSD驱动器。使用`show storageArray profile`命令或`show drive`命令显示驱动器的制造商。

====


== 语法

[source, cli]
----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----


== Parameters

|===
| 参数 | Description 


 a| 
`d驱动器`
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`d驱动器`
 a| 
要替换的驱动器的全球通用标识符(WWID)。将WWID用双引号("")括在尖括号(<>)内。

|===


== 注释：

`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。

重新启动驱动器后、控制器必须先验证驱动器是否正常运行、然后才能将其重新投入使用。如果无法验证此驱动器、则会将其标记为故障驱动器。重新启动故障驱动器需要使用全局热备用驱动器、并在更换驱动器投入使用后将其完全复制回备用驱动器。

故障驱动器不能在24小时内重新启动多次、在某些情况下也不能多次重置。驱动器电源周期的阈值和计数器保留在永久性存储中、并包含在状态捕获数据中。驱动器重新启动后、系统会记录信息性事件。



== 最低固件级别

8.20
