---
permalink: commands-a-z/reset-iscsiipaddress.html 
sidebar: sidebar 
keywords: reset, iscsi, ip address 
summary: reset iscsiIpAddress命令可重置远程存储阵列的IP地址、以便重新与本地存储阵列建立连接。 
---
= 重置iSCSI IP地址
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`reset iscsiIpAddress`命令可重置远程存储阵列的IP地址、以便重新与本地存储阵列建立连接。



== 支持的阵列

此命令会对任何单个存储阵列执行适用场景 操作、但有一些限制。如果您在E2700或E5600阵列上运行命令、则没有任何限制。

[NOTE]
====
如果在E2800、E5700、EF600和EF300阵列上运行命令、则客户端类型必须设置为 `symbol`。如果客户端类型设置为、则不会执行此命令 `https`。

====


== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您可以使用此命令通知本地存储阵列远程存储阵列的iSCSI IP地址已更改且需要更新。

在与iSCSI连接建立异步镜像关系时、本地和远程存储阵列会在异步镜像配置中存储远程存储阵列的IP地址记录。如果iSCSI端口的IP地址发生变化、尝试使用该端口的远程存储阵列将遇到通信错误。

IP地址已更改的存储阵列会向与配置为通过iSCSI连接进行镜像的异步镜像组关联的每个远程存储阵列发送一条消息。接收此消息的存储阵列会自动更新其远程目标IP地址。

如果IP地址已更改的存储阵列无法向远程存储阵列发送其控制器间消息、则系统会向您发送连接问题描述 警报。使用`reset`命令重新建立与本地存储阵列的连接。



== 语法

[listing]
----
reset (remoteStorageArrayName="storageArrayName" | remoteStorageArrayWwid=<wwID>)
iscsiIpAddress
----


== Parameters

|===
| 参数 | Description 


 a| 
`remoteStorageArrayName`
 a| 
要重置iSCSI IP地址的远程存储阵列的名称。将存储阵列名称用双引号("")括起来。



 a| 
`remoteStorageArrayWwid`
 a| 
要重置iSCSI IP地址的存储阵列的全球通用标识符(WWID)。您可以使用WWID而不是存储阵列名称来标识存储阵列。将WWID括在尖括号中(<>)。

|===


== 最低固件级别

7.84.接受采取后续行动

11.80增加了EF600和EF300阵列支持
