---
permalink: commands-a-z/reset-controller.html 
sidebar: sidebar 
keywords: reset, controller 
summary: reset controller命令用于重置控制器、并对I/O操作造成中断。 
---
= 重置控制器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`reset controller`命令可重置控制器、并中断I/O操作。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
重置控制器时、该控制器将从数据路径中删除、并且在重置操作完成之前不可用于I/O操作。如果主机正在使用由要重置的控制器拥有的卷、则定向到该控制器的I/O将被拒绝。在重置控制器之前、请确保控制器所拥有的卷未在使用中、或者确保使用这些卷的所有主机上都安装了多路径驱动程序。

====
[CAUTION]
====
如果使用带内管理、则无法控制向哪个控制器发送任何命令、并且此命令可能会产生意外结果。

====


== 语法

[source, cli]
----
reset controller [(a|b)]
----


== Parameters

|===
| 参数 | Description 


 a| 
`控制器`
 a| 
要重置的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器将控制器标识符括在方括号()中。如果不指定控制器、则存储管理软件将返回语法错误。

|===


== 注释：

接收reset controller命令的控制器将重置指定的控制器。例如、如果将reset controller命令发送到控制器A以请求重置控制器A、则控制器A将通过软重新启动自行重新启动。如果将reset controller命令发送到控制器A以请求重置控制器B、则控制器A会将控制器B置于重置状态、然后将控制器B从重置状态中释放、即硬重新启动。在某些产品中、软重新启动只会重置IOC芯片。硬重新启动会重置控制器中的IOC和扩展器芯片。



== 最低固件级别

5.20
