---
permalink: commands-a-z/save-storagearray-controllerhealthimage.html 
sidebar: sidebar 
keywords: save, storage, array, controller, health, image 
summary: 对于支持控制器运行状况映像功能的存储阵列、save storageArray controllerHealthImage命令会将控制器运行状况映像保存到主机上的指定文件中。 
---
= 保存存储阵列控制器运行状况映像
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于支持控制器运行状况映像功能的存储阵列、`save storageArray controllerHealthImage`命令可将控制器运行状况映像保存到主机上的指定文件中。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
对于固件版本8.20、`coredump`参数将替换为`controllerHealthImage`参数。

====
如果存储阵列不支持控制器运行状况映像功能、则此命令将返回错误。



== 语法

[source, cli, subs="+macros"]
----
save storageArray controllerHealthImage file=pass:quotes["_filename_"]
----


== 参数

[cols="2*"]
|===
| 参数 | Description 


 a| 
`文件`
 a| 
用于保存控制器运行状况映像的文件路径和文件名。将文件名用双引号("")括起来。例如：

[listing]
----
file="C:\Array Backups\DBMbackup_03302010.core"
----
|===


== 注释：

控制器运行状况映像文件的大小可能为1到2 GB、需要几分钟才能保存。除了保存控制器运行状况映像本身之外、此命令还会根据控制器运行状况映像元数据生成XML描述符文件。此描述符文件以ZIP文件格式保存到与控制器运行状况映像相同的路径。以下示例显示了描述符文件的XML格式。

[listing]
----
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
- <DPLcontrollerHealthImageInfo>
<dplcontrollerHealthImageTag>sometag#</dplcontrollerHealthImageTag>
<captureTime>12/22/10 3:58:53 PM IST</captureTime>
- <StorageArrayData>
<ArraySAID>600a0b80006e006a000000004c65efc1</ArraySAID>
<ManagementApiVersion>devmgr.v1083api01.Manager</ManagementApiVersion>
<fwVersion>07.83.01.00</fwVersion>
<platformType>7091</platformType>
</StorageArrayData>
<fullcontrollerHealthImageCtlr>controllerserialNumber1
     </fullcontrollerHealthImageCtlr>
<fullcontrollerHealthImageSize>fullCaptureSize</fullcontrollerHealthImageSize>
<altcontrollerHealthImageCtlr>controllerserialNumber2</altcontrollerHealthImage
     Ctlr>
<altcontrollerHealthImageSize>altCaptureSize</altcontrollerHealthImageSize>
<triggerReason>Exception</triggerReason>-<DPLcontrollerHealthImageDetail>
<dplcontrollerHealthImageReason>DPLcontrollerHealthImageReason
     </dplcontrollerHealthImageReason>
- <fwLocation >
<filename>filename</filename>
<lineNumber>line#</lineNumber>
</fwLocation >
<panicReason>panicString</panicReason>
</DPLcontrollerHealthImageDetail>
</DPLcontrollerHealthImageInfo>
----
在将控制器运行状况映像从控制器缓存检索到主机时、控制器上会设置一个标志、指示不需要检索控制器运行状况映像。此设置将持续48小时。如果在此期间出现新的控制器运行状况映像、则新的控制器运行状况映像将保存到控制器缓存中、并覆盖缓存中先前的所有控制器运行状况映像数据。



== 最低固件级别

7.83.

8.20将`coredump`参数替换为`controllerHealthImage`参数。
