---
permalink: commands-a-z/set-drive-hotspare.html 
sidebar: sidebar 
keywords: set, drive, hot spare 
summary: set drive hotspare命令会将一个或多个驱动器分配或取消分配为热备用驱动器。 
---
= 设置驱动器热备用磁盘
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set drive hotspare`命令会将一个或多个驱动器分配或取消分配为热备用驱动器。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
set (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
hotSpare=(TRUE | FALSE)
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`d`驱动器`或`d驱动器
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`热备件`
 a| 
用于将驱动器分配为热备用磁盘的设置。要将驱动器分配为热备用磁盘、请将此参数设置为`true`。要从驱动器中删除热备用磁盘分配、请将此参数设置为`false`。

|===


== 注释：

`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 最低固件级别

6.10

7.60添加了`drawerID`用户输入。
