---
permalink: commands-a-z/set-disk-pool-modify-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool, modify 
summary: 'set diskPool命令可向磁盘池(动态容量扩展或DCE)添加容量或更改整个磁盘池的控制器所有权。' 
---
= 设置磁盘池(修改磁盘池)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set diskPool`命令可向磁盘池(动态容量扩展或DCE)添加容量或更改整个磁盘池的控制器所有权。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

这两项操作是互斥的。



== 语法

[source, cli, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
(addDrives=pass:quotes[[_trayID1_,_drawerID1_,_slotID1_ ... _trayIDn_,_drawerIDn_,_slotIDn_]] |
addCapacity=pass:quotes[(_diskPoolCapacity_))]
[owner=(a| b)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`diskPool`
 a| 
要修改的磁盘池的名称。将磁盘池名称用方括号([])括起来。如果磁盘池名称包含特殊字符或仅包含数字、则必须将该名称用双引号("")括在方括号内。



 a| 
`添加驱动器`
 a| 
要添加到磁盘池的驱动器。对于大容量驱动器托盘、请指定要添加的驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定要添加的驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。插槽ID值为`1`到`24`。将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。

[NOTE]
====
此功能限制为12个驱动器。

====


 a| 
`addCapacity`
 a| 
要添加到磁盘池的额外存储容量。此参数会自动选择要添加的容量所需的驱动器。容量的单位为`字节`、`KB`、`MB`、`GB`或`TB`。



 a| 
`所有者`
 a| 
拥有磁盘池的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器如果未指定所有者、则控制器固件将确定所有者。

|===


== 注释：

在添加新驱动器时、磁盘池中已有的卷将保持联机状态并可用于I/O操作。在添加容量之前、磁盘池必须处于完成状态。如果磁盘池未处于complete状态、请在添加新驱动器之前运行`set diskPool complete`命令。

要添加容量、请使用`addDrives`参数指定各个驱动器、或者使用`addCapacity`参数指定驱动器容量。如果您使用`addDrives`、则主机必须先验证驱动器集、然后才能运行此操作。如果使用`addCapacity`参数、则指定的容量将作为要添加的最小容量。候选驱动器的服务质量最佳、容量大于或等于您指定的容量。如果没有符合最低匹配条件的候选项、或者指定的驱动器列表不可用或检测到属性不匹配、则操作将失败。

您也可以使用此命令将磁盘池的所有权从存储阵列中的一个控制器更改为另一个控制器。使用此命令更改所有权与使用命令添加驱动器或添加容量不能同时使用。



== 最低固件级别

7.83.
