---
permalink: commands-a-z/set-snmpuser-username.html 
sidebar: sidebar 
keywords: update, snmpv3, usm, user 
summary: 'set snmpUser username命令可更新现有的简单网络管理协议(Simple Network Management Protocol、SNMP) USM用户。如果只有一个用户具有要更改的USM用户名、则此用户名会使用用户名进行标识。如果多个用户具有相同的用户名和不同的引擎ID、则会使用用户名和引擎ID来标识此用户。' 
---
= 更新SNMPv3 USM用户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`set snmpUser username`命令可更新现有的简单网络管理协议(Simple Network Management Protocol、SNMP) USM用户。如果只有一个用户具有要更改的USM用户名、则此用户名会使用用户名进行标识。如果多个用户具有相同的用户名和不同的引擎ID、则会使用用户名和引擎ID来标识此用户。



== 支持的阵列

此命令适用于单个E4000、E2800、E5700、EF600或EF300存储阵列。它不能在E2700或E5600存储阵列上运行。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或支持管理员角色。



== 语法

[source, cli]
----
set snmpUser userName="snmpUserName" [engineId=(local | engineId)]
[newUserName="newSnmpUserName"] [newEngineId=(local | engineId)]
[authProtocol=(none | sha | sha256 | sha512) authPassword="authPassword"]
[privProtocol=(none | aes128) privPassword="privPassword"]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`用户名`
 a| 
要更新的SNMP USM用户的名称。将SNMP USM用户名用双引号括起来("")



 a| 
`EngineID`
 a| 
要更新的SNMP USM用户的引擎ID。如果有多个USM用户使用相同的用户名、则需要引擎ID。该值可以是`local`以指定本地SNMP代理为权威代理、也可以是十六进制数字字符串以指定远程SNMP代理引擎ID。



 a| 
`newSnmpUserName`
 a| 
要为SNMP用户指定的新名称。将SNMP用户名用双引号("")括起来。默认值为先前为用户定义的用户名。



 a| 
`newEngineId`
 a| 
要用作用户权威SNMP引擎ID标识符的新引擎ID。该值可以是"[.code]local"、用于指定本地SNMP代理为权威代理、也可以是十六进制数字字符串、用于指定远程SNMP代理引擎ID。默认值为先前为用户定义的引擎ID。



 a| 
`authProtocol`
 a| 
用户要使用的身份验证协议(HMAC)。该值可以是以下值之一：

* `none`—SNMP消息不进行身份验证(默认)
* `sha`- SHA-1身份验证
* `s 256`- SHA-256身份验证
* `s 512`- SHA-512身份验证


默认值为先前为用户定义的身份验证协议。



 a| 
`authPassword`
 a| 
用于用户身份验证的密码。如果身份验证协议为`sha`、`s 256`或`s 512`、则必须指定此参数



 a| 
`privProtocol`
 a| 
用户要使用的隐私协议(加密)。该值可以是以下值之一：

* `none`—SNMP消息不加密(默认)
* `aes128`—AES-18加密


默认值为先前为用户定义的隐私协议。



 a| 
`privPassword`
 a| 
用于用户隐私/加密的密码。如果隐私协议为"[.code]`aes128`"、则必须指定此参数。

|===


== 最低固件级别

8.72
