---
permalink: commands-a-z/set-volume-logicalunitnumber.html 
sidebar: sidebar 
keywords: set, volume, map 
summary: 'set volume logicalUnitNumber命令用于定义卷与主机或主机组之间的逻辑单元号(LUN)或命名空间ID (NSID)映射。' 
---
= 设置卷映射 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set volume logicalUnitNumber`命令可定义卷与主机或主机组之间的逻辑单元号(LUN)或命名空间ID (NSID)映射。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

此命令适用于卷组或磁盘池中的卷。

[NOTE]
====
不能对联机卷副本中使用的快照卷使用此命令。

====


== 语法

[source, cli, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] | volume <"wwID"> | accessVolume)
pass:quotes[logicalUnitNumber=_lun_]
pass:quotes[(host="_hostName_"] |
hostGroup=pass:quotes[("_hostGroupName_"] | defaultGroup)
----


== 参数

[cols="2*"]
|===
| 参数 | Description 


 a| 
`卷`
 a| 
要为其定义逻辑单元号的卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或数字、则必须在方括号内用双引号("")将卷名称括起来。



 a| 
`卷`
 a| 
要为其定义逻辑单元号的卷的全球通用标识符(WWID)。将WWID用双引号("")括在尖括号(<>)内。



 a| 
`访问卷`
 a| 
访问卷的逻辑单元号。逻辑单元号是您可以为访问卷设置的唯一属性。



 a| 
`logicalUnitNumber`
 a| 
要用于映射到特定主机的逻辑单元号或命名空间ID。此参数还会将主机分配给主机组。

[NOTE]
====
您指定的逻辑单元号或命名空间ID不得已在使用中、并且必须在主机操作系统支持的范围内。如果将卷映射到主机不支持的逻辑单元号或命名空间ID、则不会出现错误、但主机将无法访问此卷。

====


 a| 
`主机`
 a| 
卷映射到的主机的名称。将主机名用双引号("")括起来。



 a| 
`hostGroup`
 a| 
卷映射到的主机组的名称。将主机组名称用双引号("")括起来。`defaultGroup`是包含卷映射到的主机的主机组。

|===


== 注释：

主机组是一个可选的拓扑元素、如果要指定一组共享对相同卷的访问的主机、则可以定义该元素。主机组是一个逻辑实体。只有当您有两个或更多主机可以共享对相同卷的访问时、才能定义主机组。

您可以对名称使用字母数字字符、连字符和下划线的任意组合。名称最多可以包含30个字符。

访问卷是SAN环境中用于存储管理软件与存储阵列控制器之间的带内通信的卷。此卷使用LUN或NSID地址并占用20 MB的存储空间、而这些空间不可用于应用程序数据存储。只有带内受管存储阵列才需要访问卷。如果指定`accessVolume`参数、则只能设置`logicalUnitNumber`参数。



== 最低固件级别

7.83为磁盘池添加Snapshot卷。
