---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: set VolumeGroup命令用于定义卷组的属性。 
---
= 设置卷组 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set VolumeGroup`命令用于定义卷组的属性。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
每个命令只能执行一个操作(添加驱动器、更改RAID级别或更改卷组所有权)。不能使用一个命令执行多个操作。

====


== 语法

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`VolumeGroup`
 a| 
要为其设置属性的卷组的名称。将卷组名称用方括号([])括起来。



 a| 
`添加驱动器`
 a| 
要添加到卷组的驱动器的位置。对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`raidLevel`
 a| 
卷组的RAID级别。有效值为`0`、`1`、`3`、`5`或`6`。



 a| 
`所有者`
 a| 
拥有卷组的控制器。有效控制器标识符为`a`或`b`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器只有在要更改卷组所有者时、才使用此参数。

|===


== 注释：

主机I/O错误可能会导致卷组包含32个以上的卷。此操作还可能导致内部控制器重新启动、因为在设置卷组定义之前、超时期限已结束。如果您遇到此问题描述 、请暂停主机I/O操作、然后重试此命令。

使用此命令时、只能指定其中一个参数。

[NOTE]
====
指定`addDrives`参数或`raidLevel`参数将启动一个无法停止的长时间运行操作。

====
`addDrives`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 故障排除

尝试通过添加驱动器(也称为动态容量扩展(DCE)来扩展大型卷组可能会失败、并显示以下消息：

`返回代码：错误26—由于卷组中的驱动器数量以及关联卷的区块大小、修改操作无法完成。使用更改区块大小选项将卷组中所有卷的区块大小减小到128 KB或更低。然后、重试此操作。`

运行7.35.xx.xx固件的系统可能会失败、并显示以下消息、而不是上述消息：

`返回代码：错误462—无法执行符号操作步骤 、因为固件无法分配足够的缓存。发生错误时的操作：proc_startVolum`

除了上述消息之外、可能还会发生一个重大事件日志(MEL)事件、指示没有足够的缓存来完成DCE操作。

任何运行7.xx固件的控制器都可能会遇到此问题。

DCE需要足够的内存来缓冲从原始卷读取的数据以及要写入扩展卷的数据。在扩展操作中、驱动器数量、条带大小以及是否启用了镜像操作的某些组合可能会导致没有足够的可用内存来完成DCE操作。

如果遇到上述情况、可能的解决方法如下：

* 使用其他未分配的驱动器创建所需大小的卷组。
* 删除当前卷组、然后使用所需数量的驱动器重新创建卷组。
* 减小正在使用的区块大小、然后重试此操作。
* 如果可能、请向控制器添加更多内存、然后重试此操作。




== 最低固件级别

7.10增加了RAID 6功能。

7.30删除`availability`参数。

7.60添加了`drawerID`用户输入。
