---
permalink: commands-a-z/set-emailalert.html 
sidebar: sidebar 
keywords: configure, email, alert, set 
summary: set emailAlert命令可将电子邮件配置为向指定的技术支持或组织发送电子邮件。电子邮件警报包含事件摘要、有关受影响存储的详细信息以及客户联系信息。 
---
= 配置电子邮件警报设置 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`set emailAlert`命令可将电子邮件配置为向指定的技术支持或组织发送电子邮件。电子邮件警报包含事件摘要、有关受影响存储的详细信息以及客户联系信息。



== 支持的阵列

此命令适用于E4000、E2800、E5700、EF600和EF300存储阵列。但是、对于E2700或E5600阵列、您可以将命令用作smcli命令、而不是脚本命令。在这种情况下、命令适用场景 管理域中的所有阵列。



== 语法

[source, cli, subs="+macros"]
----
set emailAlert
    serverAddress=pass:quotes["_serverAddress_"] |
    serverEncryption=pass:quotes[_none_ | _smtps_ | _starttls_ |]
    serverPort=pass:quotes[_port value_] |
    serverUsername=pass:quotes["_username_"] |
    serverPassword=pass:quotes["_password_"] |
    senderAddress=pass:quotes["_emailAddress_"] |
    additionalContactInfo=pass:quotes["_filename_"]  |
    (recipientAddresses=pass:quotes[("_emailAddress1_" ... "_emailAddressN_")] |
 addRecipientAddresses=pass:quotes[("_emailAddress1_" ... "_emailAddressN_"))]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`serverAddress`
 a| 
用于设置电子邮件服务器地址。电子邮件服务器地址可以是完全限定域名、IPv4地址或IPv6地址。



 a| 
`serverEncryption`
 a| 
用于与服务器通信的加密。该值可以是以下值之一：

* ` none_`-无加密
* `_smtps_`-创建SSL/TLS连接(隐式TLS)
* `_Starttls_`-创建未加密连接、然后建立SSL/TLS会话(显式TLS)




 a| 
`serverPort`
 a| 
用于连接到服务器的TCP端口。默认值取决于加密类型。

* ` none_`-默认为端口25
* `_smtps_`—默认为端口465
* `_Starttls_`—默认为端口587




 a| 
`serverUsername`
 a| 
用于向服务器提供身份验证凭据的用户名。如果指定了用户名、则还必须指定密码。



 a| 
`serverPassword`
 a| 
用于向服务器提供身份验证凭据的密码。如果指定了密码、则还必须指定用户名。



 a| 
`s环境地址`
 a| 
用于设置发件人的电子邮件地址。



 a| 
`附加联系信息`
 a| 
用于提供包含要在电子邮件警报中使用的其他联系信息的文件名。



 a| 
`recipientAdds`
 a| 
用于设置一个或多个收件人电子邮件地址。使用此设置选项将清除现有电子邮件地址。将所有名称用圆括号括起来。请将每个名称用双引号("")括起来。使用空格分隔每个名称。



 a| 
`AddRecipientAddresss`
 a| 
用于向现有列表添加一个或多个收件人电子邮件地址。将所有名称用圆括号括起来。请将每个名称用双引号("")括起来。使用空格分隔每个名称。

|===


== 示例

[listing, subs="+macros"]
----

SMcli -n Array1 -c "set emailAlert
   serverAddress="email.server.domain.com"
    serverEncryption=pass:quotes[("_smtps_")] |
    serverPort=pass:quotes["_smtps_"] |
    serverUsername=pass:quotes["_username_"] |
    serverPassword=pass:quotes["_password_"] |
   senderAddress=\no-reply@server.domain.com
   additionalContactInfo="C:\additionalInfo.txt"
   recipientAddresses=("\person1@email.domain.com" "\person2@email.domain.com");"

SMcli -n Array1 -c "set emailAlert addRecipientAddresses=("\person3@netapp.com");"

SMcli completed successfully.
----


== 最低固件级别

8.40

11.70.1增加了`serverEncryption`、`serverPort`、`serverUsername`和`serverPassword`参数。
