---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: 'set drive nativeState命令可将缺少的(外部)驱动器重新添加到其原始卷组中、并使其成为新存储阵列中卷组的一部分。' 
---
= 将外部驱动器设置为原生
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`set drive nativeState`命令可将缺少的(外部)驱动器重新添加到其原始卷组中、并使其成为新存储阵列中卷组的一部分。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

如果驱动器属于存储阵列中的卷组、则将其视为原生。如果驱动器不属于存储阵列中的卷组、或者无法使用卷组中要传输到新存储阵列的驱动器导入该驱动器、则该驱动器将视为外部驱动器。后一个故障会在新存储阵列上创建一个不完整的卷组。

仅将此操作用于紧急恢复：需要将一个或多个驱动器从外部驱动器状态更改为其原始卷组中的原生 状态时。

[NOTE]
====
*可能的数据损坏或数据丢失*-如果出于先前所述的其他原因使用此命令、可能会导致数据丢失而不发出通知。

====


== 语法

[listing, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`d`驱动器`或`d驱动器
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800、E5700、EF600和EF300控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`所有驱动器`
 a| 
用于选择所有驱动器的设置。

|===


== 注释：

`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 最低固件级别

7.10.

7.60添加了`drawerID`用户输入。
