---
permalink: commands-a-z/set-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool 
summary: set diskPool命令可根据指定参数设置与磁盘池关联的属性。 
---
= 设置磁盘池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set diskPool`命令可根据指定参数设置与磁盘池关联的属性。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
set (diskPool pass:quotes[[_diskPoolName_]] |
diskPools pass:quotes[[_diskPoolName1_ ... _diskPoolNameN_]] | allDiskPools)
[reservedDriveCount=pass:quotes[_reservedDriveCountValue_]]
[warningThreshold=(warningThresholdValue | default)]
[criticalThreshold=(criticalThresholdValue | default)]
[criticalPriority=(highest | high | medium |low |lowest)]
[degradedPriority=(highest |high |medium |low |lowest)]
[backgroundPriority=(highest | high | medium |low |lowest)]
[userLabel=pass:quotes[_diskPoolName_]]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`diskPool`
 a| 
要为其设置属性的磁盘池的名称。将磁盘池名称用方括号([])括起来。如果磁盘池名称包含特殊字符或仅包含数字、则必须将磁盘池名称用双引号("")括在方括号内。



 a| 
`diskPools`
 a| 
要为其设置属性的多个磁盘池的名称。使用以下规则输入磁盘池的名称：

* 请将所有名称用方括号([])括起来。
* 使用空格分隔每个名称。


如果磁盘池名称包含特殊字符或数字、请使用以下规则输入名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`所有磁盘池`
 a| 
此参数用于设置存储阵列中所有磁盘池的属性。



 a| 
`reservedDriveCount`
 a| 
此参数会在磁盘池中的每个驱动器上预留空间、专用于重建故障驱动器。此计数中的每个单位表示将一个故障驱动器重建到磁盘池的其余部分的容量。



 a| 
`warningThreshold`
 a| 
磁盘池容量的百分比、当您收到磁盘池接近全满的警告警报时。使用整数值。例如、值70表示70%。为了获得最佳操作效果、此参数的值必须小于`criticalThreshold`参数的值。

有效值为0到100。

默认值为50。

将此参数设置为`0`将禁用警告警报。

如果将此值设置为`default`、则警告警报阈值由控制器固件决定。



 a| 
`关键阈值`
 a| 
磁盘池容量的百分比、当您收到磁盘池接近全满的严重警报时。使用整数值。例如、值70表示70%。为了获得最佳操作效果、此参数的值必须大于`warningThreshold`参数的值。

有效值为0到100。

默认值为85%。

如果将此参数设置为`0`、则会同时禁用警告警报和严重警报。

如果将此值设置为`default`、则严重警报阈值由控制器固件决定。



 a| 
`关键优先级`
 a| 
磁盘池上严重事件的重建操作的优先级。例如、在至少发生两个驱动器故障后重建磁盘池。

有效值为`最高`、`高`、`m中`、`低`和`最低`。默认值为`Highest`。



 a| 
`degradedPriPriority`
 a| 
磁盘池上降级事件的重建操作的优先级。例如、在一个驱动器发生故障后重建磁盘池。

有效值为`最高`、`高`、`m中`、`低`和`最低`。默认值为`high`。



 a| 
`BackgroundPriority`
 a| 
磁盘池上后台操作的优先级。

有效值为`最高`、`高`、`m中`、`低`和`最低`。默认值为`low`。



 a| 
`用户标签`
 a| 
要为磁盘池指定的新名称。将磁盘池名称用双引号("")括起来。

|===


== 注释：

每个磁盘池名称必须唯一。您可以对用户标签使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。用户标签最多可以包含30个字符。

您可以指定一组任意的磁盘池。如果选择多个磁盘池、则为`userLabel`设置一个值会导致错误。

如果不为可选参数指定值、则会分配默认值。



== 磁盘池警报阈值

每个磁盘池都有两个逐渐严重的警报级别、用于在磁盘池的存储容量接近全满时通知用户。警报阈值是磁盘池中已用容量占总可用容量的百分比。警报包括：

* 警告—这是磁盘池中已用容量接近全满的第一级警报。达到警告警报阈值时、将生成需要注意的情况、并将事件发布到存储管理软件。警告阈值将被严重阈值所取代。默认警告阈值为50%。
* 严重—这是磁盘池中已用容量接近全满的最严重警报级别。达到严重警报的阈值时、将生成需要注意的情况、并将事件发布到存储管理软件。警告阈值将被严重阈值所取代。严重警报的默认阈值为85%。


要生效、警告警报的值必须始终小于严重警报的值。如果警告警报的值与严重警报的值相同、则仅发送严重警报。



== 磁盘池后台操作

磁盘池支持以下后台操作：

* 重建
* 即时可用性格式(IAF)
* 格式。
* 动态容量扩展(DCE)
* 动态容量缩减(DCR)
* 动态卷扩展(DVE)(对于磁盘池、DVE实际上不是后台操作、但支持将DVE作为同步操作。)


磁盘池不会对后台命令进行排队。您可以按顺序启动多个后台命令、但一次启动多个后台操作会延迟先前启动的命令的完成。支持的后台操作的相对优先级为：

. 重建
. 格式。
. 系统
. DCE/DCR




== 最低固件级别

7.83.
