---
permalink: commands-a-z/set-storagearray.html 
sidebar: sidebar 
keywords: set, storage, array 
summary: set storageArray命令用于定义存储阵列的属性。 
---
= 设置存储阵列
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`set storageArray`命令用于定义存储阵列的属性。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
对于固件版本8.10、`cachFlushStop`参数已弃用、并将在未来版本的存储管理软件中删除。

====


== 语法

[listing]
----
set storageArray
([autoLoadBalancingEnable=(TRUE | FALSE)]|
[autoSupportMaintenanceWindow AutoSupport Maintenance Window parameters]
[autoSupport schedule AutoSupport Schedule Parameters]|
[autoSupportConfig (enable | disable)]|
[autoSupportOnDemand (enable | disable)]|
[autoSupportRemoteDiag (enable |disable)]|
[cacheBlockSize=cacheBlockSizeValue]|
[cacheFlushStart=cacheFlushStartSize]|
[cacheFlushStop=cacheFlushStopSize]|
[cacheMirrorDataAssuranceCheckEnable=(TRUE | FALSE)]|
[controllerHealthImageAllowOverWrite]|
[defaultHostType=("hostTypeName" |"hostTypeIdentifier")] |
[directoryServer directory server parameters]|
[externalKeyManagement external key management parameters]|
[failoverAlertDelay=delayValue]|
[hostConnectivityReporting (enable | disable)]|
[icmpPingResponse=(TRUE | FALSE)]|
[isnsIPV4ConfigurationMethod isns IPv4 Config Method Parameters]|
[isnsIPv6Address=ipAddress]|
[isnsListeningPort=listeningPortIPAddress]]|
[isnsRegistration=(TRUE | FALSE)]|
[learnCycleDate learn cycle parameters]|
[localUsername=local user name parameters]|
[loginBanner file="path_to_login_banner"]|
[managementInterface restOnly={true | false}]|
[mediaScanRate=(disabled | 1-30)]|
[odxEnabled=(TRUE | FALSE)]|
[password="password"]|
[passwordLength=<INTEGER>]|
[pqValidateOnReconstruct P/Q Validate on Reconstruct parameters]|
[redundancyMode=(simplex | duplex)]|
[revocationCheckSettings revocation check settings parameters]|
[securityKey]|
[symbol SYMbol user name and password parameters]|
[syslog syslog parameters]|
[time]|
[trayPositions=(controller | trayID ... trayIDn)]|
[unnamedDiscoverySession=(TRUE | FALSE)]|
[userLabel="storageArrayName"]|
[userSession sessionTimeout=n]|
[vaaiEnabled=(TRUE | FALSE)])
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`AutoLoadBalancingEnable`
 a| 
此参数用于在控制器上启用自动负载平衡。要启用此选项、请将此参数设置为`true`。要禁用此选项、请将此参数设置为`false`。

[NOTE]
====
启用自动负载平衡功能后、还会启用主机连接报告功能。

====


 a| 
`AutoSupport schedule`
 a| 
设置AutoSupport 消息在一周中的每天和每周发送时间和天数。



 a| 
`autosupportConfig`
 a| 
每当固件检测到严重的MEL事件时自动收集支持数据的设置。此参数具有以下值：

* `enable`—打开支持数据的收集
* `disable`—关闭支持数据的收集


请仅在以下情况下使用此参数：

* 存储阵列不支持AutoSupport (ASUP)功能
* 以支持先前使用此参数的存储阵列上的配置


[NOTE]
====
不能将此参数与ASUP命令结合使用。

====


 a| 
`autosupportMaintenanceWindow`
 a| 
打开或关闭AutoSupport 维护窗口功能并配置该功能。



 a| 
`cachBlockSize`
 a| 
控制器用于管理缓存的缓存块大小。有效值为`4`(4 KB)、`8`(8 KB)、`16`(16 KB)或`32`(32 KB)。



 a| 
`cachMirrorDataAssuranceCheckEnable`
 a| 
此参数用于在控制器上启用缓存镜像数据保证检查。要启用此选项、请将此参数设置为`true`。要禁用此选项、请将此参数设置为`false`。



 a| 
`cachFlushStart`
 a| 
导致缓存刷新的缓存中未写入数据的百分比。使用`0`到`100`之间的整数值来定义百分比。默认值为 `80` 。



 a| 
`cachFlushStop`
 a| 
[NOTE]
====
此参数已弃用、将在未来版本中删除。

====
缓存中停止缓存刷新的未写入数据的百分比。使用`0`到`100`之间的整数值来定义百分比。此值必须小于`cachFlushStart`参数的值。



 a| 
`controllerHealthImageAllowOverWrite`
 a| 
在控制器上设置一个标志、以允许新的控制器运行状况映像覆盖支持控制器运行状况映像功能的存储阵列上的现有控制器运行状况映像。



 a| 
`defaultHostType`
 a| 
控制器所连接到的任何未配置主机端口的默认主机类型。要为存储阵列生成有效主机类型列表、请运行`show storageArray hostTypeTable`命令。主机类型由名称或数字索引标识。将主机类型名称用双引号("")括起来。请勿将主机类型的数字标识符用双引号括起来。



 a| 
`d目录服务器`
 a| 
更新目录服务器配置、包括角色映射。



 a| 
`外部密钥管理`
 a| 
配置外部密钥管理服务器地址和端口号



 a| 
`failoverAlertDelay`
 a| 
故障转移警报延迟时间、以分钟为单位。延迟时间的有效值为`0`到`60`分钟。默认值为`5`。



 a| 
`hostConnectivityReporting`
 a| 
此参数用于在控制器上启用主机连接报告。要启用此选项、请将此参数设置为`enable`。要禁用此选项、请将此参数设置为`disable`。

[NOTE]
====
如果在启用自动负载平衡时尝试禁用主机连接报告、则会收到错误。首先禁用自动负载平衡功能、然后禁用主机连接报告功能。

====
[NOTE]
====
禁用自动负载平衡后、您可以保持启用主机连接报告。

====


 a| 
`icmpPingResponse`
 a| 
此参数用于打开或关闭回显请求消息。将参数设置为`true`以打开回显请求消息。将参数设置为`false`以关闭回显请求消息。



 a| 
`isnssIPv4ConfigurationMethod`
 a| 
要用于定义iSNS服务器配置的方法。您可以通过选择`static`来输入IPv4 iSNS服务器的IP地址。对于IPv4、您可以输入`dHCP`来选择让动态主机配置协议(DHCP)服务器选择iSNS服务器IP地址。要启用DHCP、必须将`isnssIPV4Address`参数设置为`0.0.0.0`。



 a| 
`isnssIPv6Address`
 a| 
要用于iSNS服务器的IPv6地址。



 a| 
`isnssListeningPort`
 a| 
要用于iSNS服务器侦听端口的IP地址。侦听端口的值范围为`49152`到`65535`。默认值为`53205`。

侦听端口位于服务器上、并执行以下活动：

* 监控传入的客户端连接请求
* 管理服务器的流量


当客户端请求与服务器进行网络会话时、侦听器会收到实际请求。如果客户端信息与侦听器信息匹配、则侦听器会授予与数据库服务器的连接。



 a| 
`isnssRegistration`
 a| 
此参数将存储阵列列为iSNS服务器上的iSCSI目标。要在iSNS服务器上注册存储阵列、请将此参数设置为`true`。要从iSNS服务器中删除存储阵列、请将此参数设置为`false`。

[NOTE]
====
运行`set storageArray`命令时、不能将`isnssRegistration`参数与任何其他参数结合使用。

====
有关iSNS注册的详细信息、请参阅`set storageArray isnssRegistration`命令。



 a| 
`learnCycleDate`
 a| 
设置控制器电池学习周期。



 a| 
`localUsername`
 a| 
用于为特定角色设置本地用户名密码或符号密码。



 a| 
`loginBanner`
 a| 
用于上传要用作登录横幅的文本文件。横幅文本可以包含建议通知和同意消息、在用户在SANtricity System Manager中建立会话之前或在用户运行命令之前、这些通知和同意消息会提供给用户



 a| 
`m设备接口`
 a| 
更改控制器的管理接口。更改管理接口类型以在存储阵列与其管理软件之间实施机密性、或者访问外部工具。



 a| 
`mediaScanRate`
 a| 
运行介质扫描的天数。有效值为`d已标记`、用于关闭介质扫描；或`1`天至`30`天、其中`1`天是最快的扫描速率、`30`天是最慢的扫描速率。除`dis标记`或`1`到`30`以外的值不允许介质扫描正常运行。



 a| 
`已启用odxEnabled`
 a| 
打开或关闭存储阵列的卸载数据传输(Offloaded Data Transfer、ODX)。



 a| 
`密码`
 a| 
存储阵列的密码。请将密码用双引号("")括起来。

[NOTE]
====
在8.40版本中、此参数已弃用。请改用`localUsername`或符号`symbol`参数以及`password`或`adminpassword`参数。

====


 a| 
`密码长度`
 a| 
用于设置所有新密码或已更新密码所需的最小长度。请使用一个介于0到30之间的值。



 a| 
`pqValidateOnReconstruct`
 a| 
修改P/Q validate on reconstruction功能。



 a| 
`redundancyMode`
 a| 
如果只有一个控制器、请使用`simplicx`模式。如果有两个控制器、请使用`duplex`模式。



 a| 
`revocationCheckSettings`
 a| 
用于启用或禁用撤消检查、以及配置联机证书状态协议(OCSP)服务器。



 a| 
`securityKey`
 a| 
设置在整个存储阵列中使用的内部安全密钥、以实施驱动器安全功能。

[NOTE]
====
用于内部安全密钥。使用外部密钥管理服务器时、请使用`create storageArray securityKey`命令。

====


 a| 
`symbol`
 a| 
用于为特定角色设置符号密码。



 a| 
`s系统日志`
 a| 
用于更改系统日志服务器地址、协议或端口号。



 a| 
`时间`
 a| 
通过将控制器时钟与运行此命令的主机的时钟同步来设置存储阵列中两个控制器上的时钟。



 a| 
`纸架位置`
 a| 
所有托盘ID的列表。列表中的托盘ID顺序定义了控制器托盘和驱动器托盘在存储阵列中的位置。有效值为`0`到`99`。输入以空格分隔的托盘ID值。将托盘ID值列表用圆括号括起来。对于控制器托盘的预定义标识符不在有效托盘位置值范围内的存储阵列、请使用`controller`值。

[NOTE]
====
固件版本6.14之后、`controller`选项无效。

====


 a| 
`unnamedDiscoverySession`
 a| 
允许存储阵列参与未命名的发现会话。



 a| 
`用户标签`
 a| 
存储阵列的名称。将存储阵列名称用双引号("")括起来。



 a| 
`用户会话`
 a| 
用于在System Manager中设置超时、以便在指定时间后断开用户的非活动会话。



 a| 
`已启用vaaiEnabled`
 a| 
打开或关闭存储阵列的VMware vStorage API阵列架构(VAAI)

|===


== 注释：

除了`isnssRegistration`之外、使用此命令时、您可以指定一个或多个可选参数。



== Auto Support数据

[NOTE]
====
不能将此参数与ASUP命令结合使用。

====
启用后、`set storageArray autosupportConfig`命令会在每次检测到严重重大事件日志(MEL)事件时返回存储阵列的所有配置和状态信息。配置和状态信息以对象图形的形式返回。对象图形包含存储阵列的所有相关逻辑和物理对象及其关联状态信息。

`set storageArray autosupportConfig`命令可通过以下方式收集配置和状态信息：

* 每72小时自动收集一次配置和状态信息。配置和状态信息将保存到存储阵列zip归档文件中。归档文件具有用于管理归档文件的时间戳。
* 为每个存储阵列维护两个存储阵列zip归档文件。zip归档文件保留在驱动器上。超过72小时时间段后、新周期中最旧的归档文件始终会被覆盖。
* 使用此命令启用配置和状态信息的自动收集后、将开始初始信息收集。在完成问题描述 操作后收集信息命令可确保一个归档文件可用并开始时间戳周期。


您可以在多个存储阵列上运行`set storageArray autosupportConfig`命令。



== 缓存块大小

定义缓存块大小时、对于需要I/O流(通常为小型随机数据流)的存储阵列、请使用4 KB缓存块大小。如果大多数I/O流大于4 KB但小于8 KB、请使用8 KB缓存块大小。对于需要大型数据传输、顺序或高带宽应用程序的存储阵列、请使用16 KB缓存块大小或32 KB缓存块大小。

`cachBlockSize`参数定义存储阵列中所有卷支持的缓存块大小。并非所有控制器类型都支持所有缓存块大小。对于冗余配置、此参数包括存储阵列中两个控制器所拥有的所有卷。



== 缓存刷新启动

如果定义了启动缓存刷新所需的值、则过低的值会增加主机读取所需数据不在缓存中的可能性。如果值较低、则还会增加保持缓存级别所需的驱动器写入次数、从而增加系统开销并降低性能。



== 默认主机类型

定义主机类型时、如果启用了存储分区、则默认主机类型仅会影响默认组中映射的卷。如果未启用存储分区、则连接到存储阵列的所有主机都必须运行相同的操作系统并与默认主机类型兼容。



== 介质扫描速率

在存储阵列中的所有卷上运行介质扫描、这些卷的状态为"最佳"、未执行修改操作、并且已启用`mediaScan Rate`参数。使用`set volume`命令启用或禁用`mediaScanRate`参数。



== Password

密码存储在每个存储阵列上。为获得最佳保护、密码必须满足以下条件：

* 密码长度必须介于8到30个字符之间。
* 密码必须至少包含一个大写字母。
* 密码必须至少包含一个小写字母。
* 密码必须至少包含一个数字。
* 密码必须至少包含一个非字母数字字符、例如<>@+。


[NOTE]
====
如果要在存储阵列中使用全磁盘加密驱动器、则必须使用这些标准作为存储阵列密码。

====
[NOTE]
====
您必须先为存储阵列设置密码、然后才能为加密的全磁盘加密驱动器创建安全密钥。

====


== 最低固件级别

5.00会添加`defaultHostType`参数。

5.40添加了`failoverAlertDelay`参数。

6.10添加了`redundancyMode`、`dayPos设置`和`Time`参数。

6.14添加`alarm`参数。

7.10添加了`icmpPingResponse`、`unnamedDiscoverySession`、`isnssIPv6Address`和`isnssIPv4ConfigurationMethod`参数。

7.15会添加更多的缓存块大小和`learnCycleDate`参数。

7.86会删除`alarm`参数、因为它不再使用、并添加`coreDumpAllowOverWrite`参数。

8.10已弃用`cachFlushStop`参数。

8.20会添加`odxEnabled`和`vaaiEnabled`参数。

8.20会更新`cachBlockSize`参数以添加`cachBlockSizeValue` of 4 (4 KB)。

8.20将`coreDumpAllowOverWrite`参数替换为`controllerHealthImageAllowOverWrite`参数。

8.30添加了`autodelLoadBalancingEnable`参数。

8.40会添加`localUsername`参数(与用户名变量以及`password`或`adminpassword`参数结合使用)。此外、还会添加`symbol`参数(与用户名变量以及`password`或`adminpassword`参数结合使用)。

8.40已弃用`password`和`userRole`独立参数。

8.40会添加`managementInterface`参数。

8.40添加了`externalKeyManagement`参数。

8.41添加了`cachMirrorDataAssuranceCheckEnable`、`directoryServer`、`userSession`、`password长度`和`loginBanner`参数。

8.42添加了`pqValidateOnReconstruct`、`syslog`、`hostConnectivityReporting`和`revocationCheckSettings`参数。
