---
permalink: commands-a-z/set-snapgroup.html 
sidebar: sidebar 
keywords: set, snapshot, group, attributes 
summary: set snapGroup命令用于定义快照组的属性。 
---
= 设置快照组属性 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set snapGroup`命令用于定义快照组的属性。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
[userLabel=pass:quotes["_snapGroupName_"]] |
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)] |
[repositoryFullLimit=pass:quotes[_percentValue_] ] |
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]] |
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`snapGroup`
 a| 
要为其设置属性的快照组的名称。将快照组名称用双引号("")括在方括号([])内。



 a| 
`用户标签`
 a| 
要为快照组指定的新名称。如果要重命名快照组、请使用此参数。将新快照组名称用双引号("")括起来。



 a| 
`repositoryFullPolicy`
 a| 
如果快照映像组的存储库卷已满、您希望如何继续处理快照映像。您可以选择对基础卷的写入失败(`failBaseWrites`)或删除(清除)快照映像(`purgeSnapImages`)。默认操作为`purgeSnapImages`。



 a| 
`repositoryFullLimit`
 a| 
收到快照映像存储库卷接近全满警告时存储库卷容量的百分比。使用整数值。例如、值70表示70%。默认值为75。



 a| 
`autodeleteLimit`
 a| 
如果选择清除存储库已满策略中的快照映像、则要自动删除的最大快照映像数。使用整数值。默认值为32。



 a| 
`rollBackPriority`
 a| 
使用此参数确定是否应将系统资源分配给回滚操作而牺牲系统性能。有效值为`最高`、`高`、`m中`、`低`或`最低` A值`高`表示回滚操作的优先级高于所有其他主机I/O值`lowest`表示执行回滚操作时、应尽可能减少对主机I/O的影响

|===


== 注释：

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

使用此命令时、您可以指定一个或多个参数。但是、您不需要使用所有参数。



== 最低固件级别

7.83.
