---
permalink: commands-a-z/set-session-erroraction.html 
sidebar: sidebar 
keywords: set, session 
summary: set session errorAction命令用于定义当前脚本引擎会话的运行方式。 
---
= 设置会话
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set session errorAction`命令可定义当前脚本引擎会话的运行方式。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员、支持管理员、安全管理员或存储监控角色。



== 环境

在此命令中、会话是指运行命令的持续时间。此命令不会永久设置存储阵列的参数。



== 语法

[source, cli]
----
set session errorAction=(stop | continue)
password="storageArrayPassword"
performanceMonitorInterval=intervalValue
performanceMonitorIterations=iterationValue
----
[listing]
----
set session errorAction=(stop | continue)
password="storageArrayPassword"
userRole=(admin | monitor)
performanceMonitorInterval=intervalValue
performanceMonitorIterations=iterationValue
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`错误操作`
 a| 
处理期间遇到错误时会话如何响应。您可以选择在遇到错误时停止会话、也可以在遇到错误后继续会话。默认值为`sTop`。(此参数用于定义执行错误的操作、而不是语法错误。某些错误条件可能会覆盖`Continue`值。)



 a| 
`密码`
 a| 
存储阵列的密码。请将密码用双引号("")括起来。

[NOTE]
====
当客户端类型设置为`https`时、此参数将被废弃。必须在执行命令行界面命令脚本之前指定密码、并且不能在执行脚本期间更改密码。

====


 a| 
`performanceMonitorInterval`
 a| 
收集性能数据的频率。为要捕获数据的轮询间隔输入一个整数值(以秒为单位)。值范围为`3`到`3600`秒。默认值为`5`秒。

[NOTE]
====
当客户端类型设置为`https`时、此参数将被废弃。要更改默认间隔值、请在各个受影响的命令中使用此参数。这些命令包括`save storageArray performanceStats`和`show drive performanceStats`。

====


 a| 
`performanceMonitorIterations`
 a| 
要捕获的样本数。输入一个整数值。所捕获样本的值范围为`1`到`3600`。默认值为`5`。

[NOTE]
====
当客户端类型设置为`https`时、此参数将被废弃。要更改默认迭代值、请在受影响的各个命令中使用此参数。这些命令包括`save storageArray performanceStats`和`show drive performanceStats`。

====
|===


== 注释：

使用此命令时、您可以指定一个或多个可选参数。

密码存储在管理域中的每个存储阵列上。如果先前未设置密码、则不需要密码。密码可以是字母数字字符的任意组合、最多30个字符。(您可以使用`set storageArray`命令定义存储阵列密码。)

您指定的轮询间隔和迭代次数将一直有效、直到会话结束为止。会话结束后、轮询间隔和迭代次数将恢复为默认值。



== 最低固件级别

5.20

8.40 -当客户端类型设置为`https`时、已废弃`password`、`userRole`、`performanceMonitorInterval`和`performanceMonitorIterations`参数。
