---
permalink: commands-a-z/set-thin-volume-attributes.html 
sidebar: sidebar 
keywords: set, thin, volume, attributes 
summary: set volume命令用于定义精简卷的属性。 
---
= 设置精简卷属性
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`set volume`命令用于定义精简卷的属性。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您可以使用参数为一个或多个精简卷定义属性。



== 语法

[listing, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]] | volume <"wwID">)
[newCapacity=pass:quotes[_capacityValue_]]
[repositoryMaxCapacity=pass:quotes[_capacityValue_]]
[repositoryExpansionPolicy=(automatic|manual)]
[warningThresholdPercent=pass:quotes[_warningThresholdPercentValue_]]
[addRepositoryCapacity=capacity-spec][hostReportingPolicy=(standard | thin)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`卷`
 a| 
要为其定义属性的卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或数字、则必须在方括号内用双引号("")将卷名称括起来。



 a| 
`卷`
 a| 
要为其定义属性的卷的全球通用标识符(WWID)。将WWID用双引号("")括在尖括号(<>)内。



 a| 
`卷`
 a| 
要为其定义属性的多个卷的名称。所有卷都具有相同的属性。使用以下规则输入卷的名称：

* 请将所有名称用方括号([])括起来。
* 使用空格分隔每个名称。


如果卷名称包含特殊字符或仅包含数字、请使用以下规则输入名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`newCapacity`
 a| 
此参数可增加精简卷的虚拟容量。虚拟容量是卷将向映射到卷的主机报告的值。如果值小于或等于现有容量、则会出现发生原因 错误。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。

最小虚拟容量为32 MB。

最大虚拟容量为256 TB。



 a| 
`repositoryMaxCapacity"`
 a| 
此参数用于设置存储库卷的最大容量。此值不得小于存储库卷的物理容量。如果新值导致容量减少到低于警告阈值的级别、则此命令将生成错误。

[NOTE]
====
命令`repositoryMaxCapacity`与`repositoryExpansionPolicy=automatic`配合使用。

====


 a| 
`repositoryExpansionPolic*`
 a| 
此参数会将扩展策略设置为`automatic`或`manual`。将策略从`automatic`更改为`manual`时、最大容量值(配额)会更改为存储库卷的物理容量。



 a| 
`warningThresholdPercent`
 a| 
收到精简卷接近全满警告警报时精简卷容量的百分比。使用整数值。例如、值70表示70%。

有效值为1到100。

如果将此参数设置为100、则会禁用警告警报。



 a| 
`addRepositoryCapacity`
 a| 
此参数从磁盘池的可用范围分配容量。如果可用空间不足、则命令将失败。

[NOTE]
====
命令`addRepositoryCapacity`可与`repositoryExpansionPolicy=manual`配合使用。

====


 a| 
`*主机报告策略*`
 a| 
此参数用于更改向主机报告精简卷的方式。有效值为`standard`或`thin`。

|===


== 注释：

使用此命令时、您可以指定一个或多个可选参数。

下表列出了精简卷的容量限制。

[cols="2*"]
|===
| 容量类型 | Size 


 a| 
最小虚拟容量
 a| 
32 MB



 a| 
最大虚拟容量
 a| 
256 TB



 a| 
最小物理容量
 a| 
4 GB



 a| 
最大物理容量
 a| 
257 TB

|===
精简卷支持标准卷执行的所有操作、但以下情况除外：

* 您不能更改精简卷的区块大小。
* 您不能为精简卷启用预读取冗余检查。
* 您不能在卷副本中使用精简卷作为目标卷。
* 不能在同步镜像操作中使用精简卷。


如果要将精简卷更改为标准卷、请使用卷复制操作创建精简卷的副本。卷副本的目标始终为标准卷。



== 最低固件级别

7.83.
