---
permalink: commands-a-z/set-host.html 
sidebar: sidebar 
keywords: set, host 
summary: set host命令可将主机分配给主机组或将主机移动到其他主机组。 
---
= 设置主机
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`set host`命令可将主机分配给主机组或将主机移动到其他主机组。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

您也可以使用此命令创建新主机组并将主机分配给新主机组。此命令执行的操作取决于主机是否具有单独的映射或没有单独的映射。



== 语法

[listing, subs="+macros"]
----
set host [hostName]
hostGroup=pass:quotes[("_hostGroupName_"] | none | defaultGroup)
userLabel=pass:quotes["_newHostName_"]
hostType=pass:quotes[(_hostTypeIndexLabel_ | _hostTypeIndexNumber_)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`主机`
 a| 
要分配给主机组的主机的名称。请将主机名用方括号([])括起来。如果主机名包含特殊字符或数字、则必须将主机名用双引号("")括在方括号内。



 a| 
`hostGroup`
 a| 
要将主机分配到的主机组的名称。(下表定义了主机是否具有单独的映射时命令的运行方式。) 将主机组名称用双引号("")括起来。`defaultGroup`选项是包含卷映射到的主机的主机组。



 a| 
`用户标签`
 a| 
新主机名。将主机名用双引号("")括起来。



 a| 
`hostType`
 a| 
主机端口的主机类型的索引标签或编号。使用`show storageArray hostTypeTable`命令生成可用主机类型标识符的列表。如果主机类型包含特殊字符、请将主机类型用双引号("")括起来。

|===
[cols="3*"]
|===
| Host Group参数 | 主机具有单独的映射 | 主机没有单独的映射 


 a| 
`主机组名称_`
 a| 
此主机将从现有主机组中删除、并置于由`主机组名称_`定义的新主机组下。
 a| 
此主机将从现有主机组中删除、并置于由`主机组名称_`定义的新主机组下。



 a| 
`无`
 a| 
此主机将作为一个独立分区从主机组中删除、并置于根节点下。
 a| 
此主机将从现有主机组中删除、并置于默认组下。



 a| 
`defaultGroup`
 a| 
命令失败。
 a| 
此主机将从现有主机组中删除、并置于默认组下。

|===


== 注释：

使用此命令时、您可以指定一个或多个可选参数。

对于名称、您可以使用字母数字字符、连字符和下划线的任意组合。名称最多可以包含30个字符。



== 最低固件级别

6.10
