---
permalink: commands-a-z/set-tray-drawer.html 
sidebar: sidebar 
keywords: set, drawer, service, action, allowed, indicator 
summary: 设置托盘抽盒命令用于打开或关闭用于存放驱动器的抽盒上的允许服务操作指示灯。 
---
= 设置允许执行抽盒维护操作指示符
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`set tray tray n抽屉`命令可打开或关闭驱动器所在抽盒上的"Service Action Allowed "指示灯。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

抽屉用于大容量驱动器托盘。抽盒滑出驱动器托盘、以便可以访问驱动器。此命令仅适用于使用抽盒的驱动器托盘。如果存储阵列不支持允许服务操作指示灯功能、则此命令将返回错误。如果存储阵列支持命令、但无法打开或关闭指示灯、则此命令将返回错误。



== 语法

[listing, subs="+macros"]
----
set tray pass:quotes[[_trayID_]] drawer pass:quotes[[_drawerID_]]
serviceAllowedIndicator=(on | off | forceOnWarning)
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`托盘`
 a| 
抽盒所在的托盘。托盘ID值为`0`到`99`。将托盘ID值用方括号()括起来。如果不输入托盘ID值、则控制器托盘的托盘ID为默认值。



 a| 
`drawer`
 a| 
要打开或关闭允许服务操作指示灯的抽盒位置。抽盒ID值为`1`到`5`。将抽盒ID值括在方括号([])中。



 a| 
`s服务Allowed指标`
 a| 
用于打开或关闭允许服务操作指示灯的设置。要打开允许服务操作指示灯、请将此参数设置为`on`。要关闭允许服务操作指示灯、请将此参数设置为`off`。

有关使用`forceOnWarning`的信息、请参见注释。

|===


== 注释：

在输入此命令之前、驱动器托盘必须满足以下条件：

* 驱动器托盘不能温度过高。
* 风扇的状态必须为"最佳"。
* 所有驱动器托盘组件都必须安装到位。
* 驱动器抽盒中的卷不能处于已降级状态。如果从驱动器抽盒中删除驱动器、并且某个卷已处于"已降级"状态、则此卷可能会失败。


[NOTE]
====
如果不能满足上述任何条件、请勿问题描述 此命令。

====
系统会检查受影响驱动器抽盒中包含驱动器的所有卷、以确保在发送命令之前这些卷具有抽盒丢失保护功能。如果卷具有抽盒丢失保护功能、则可以继续执行Set Service Action Allowed命令、而不会停止卷的I/O活动。

如果受影响抽盒中的任何卷没有抽盒丢失保护、则必须停止这些卷的I/O活动。此时将显示一条警告、指示此命令不应完成。

要打开或关闭整个高容量驱动器托盘的允许服务操作指示灯、请使用`set tray serviceAllowedindicator`命令。



== 使用forceOnWarning参数

如果您正在准备要删除的组件、并且希望覆盖有关卷没有抽盒丢失保护的警告、请输入以下参数：

[listing]
----
serviceAllowedIndicator=forceOnWarning
----
`forceOnWarning`参数会发送请求、以便准备将组件删除到控制器固件、并强制执行`set d抽屉serviceAllowed指标`命令以继续操作。

[NOTE]
====
此参数会将抽盒中的所有驱动器标记为无法访问、并可能导致卷出现故障和复杂的恢复、包括需要重新启动主机。请谨慎使用此参数。

====


== 最低固件级别

7.60
