---
permalink: commands-a-z/set-syslog.html 
sidebar: sidebar 
keywords: configure, syslog, set 
summary: set syslog命令用于配置系统日志警报信息。您可以将事件监控器配置为在发生可警报事件时向系统日志服务器发送警报。 
---
= 配置系统日志设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`set syslog`命令可配置系统日志警报信息。您可以将事件监控器配置为在发生可警报事件时向系统日志服务器发送警报。



== 支持的阵列

此命令适用于单个E4000、E2800、E5700、EF600或EF300存储阵列。它不能在E2700或E5600存储阵列上运行。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

* 系统日志服务器地址必须可用。此地址可以是完全限定域名、IPv4地址或IPv6地址。
* 系统日志服务器的UDP端口号必须可用。此端口通常为514。




== 语法

[source, cli, subs="+macros"]
----
set syslog [defaultFacility=pass:quotes[_facilityNumber_]]
| [defaultTag=pass:quotes[_defaultTag_]]
| [syslogFormat=pass:quotes[_rfc3164_|_rfc5424_]]
| (serverAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_)]
| addServerAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_))]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`defaultFacility`
 a| 
可选。用于指定默认设施编号。默认设施必须是介于0到23之间的数值。



 a| 
`defaultTag`
 a| 
可选。用于指定默认标记。用引号将字符串括起来。



 a| 
`s系统日志格式`
 a| 
用于系统日志消息的消息传送格式。该值可以是以下值之一：

* `rfc3164`—符合RFC 3164的格式
* `rfc5424`—符合RFC 5424的格式




 a| 
`serverAdds`
 a| 
用于设置一个或多个具有关联端口号的系统日志服务器地址。使用此设置选项将清除现有服务器地址。系统日志服务器地址可以是完全限定域名、IPv4地址或IPv6地址。UDP端口必须是介于0到65535之间的数值。通常、系统日志的UDP端口为514。将所有地址括在圆括号中。如果输入多个地址、请使用空格将其分隔开。



 a| 
`AddServerAdds`
 a| 
用于添加一个或多个具有关联端口号的系统日志服务器地址。使用此设置选项不会清除现有服务器地址。系统日志服务器地址可以是完全限定域名、IPv4地址或IPv6地址。UDP端口必须是介于0到65535之间的数值。通常、系统日志的UDP端口为514。将所有地址括在圆括号中。如果输入多个地址、请使用空格将其分隔开。

|===


== 示例

[listing]
----

SMcli -n Array1 -c "set syslog serverAddresses=("ICTM1402S02H2.company.com:22");"

SMcli -n Array1 -c "set syslog addServerAddresses=("serverName1.company.com:514"
"serverName2.company.com:514");"

SMcli completed successfully.
----


== 最低固件级别

8.40

11.70.1添加了`ssyslogFormat`参数以指定系统日志消息格式。
