---
permalink: commands-a-z/set-storagearray-traypositions.html 
sidebar: sidebar 
keywords: set, storage, array, tray, positions 
summary: set storageArray TrayPos件 命令用于定义托盘在存储阵列中的位置。输入此命令时、必须将所有托盘都包含在存储阵列中。 
---
= 设置存储阵列托盘位置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set storageArray TrayPos件`命令可定义托盘在存储阵列中的位置。输入此命令时、必须将所有托盘都包含在存储阵列中。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
set storageArray trayPositions=pass:quotes[(controller | _trayID_ ... _trayIDn_)]
----


== 参数

[cols="2*"]
|===
| 参数 | Description 


 a| 
`纸架位置`
 a| 
所有托盘ID的列表。列表中的托盘ID顺序定义了控制器托盘和驱动器托盘在存储阵列中的位置。有效值为`0`到`99`。输入以空格分隔的托盘ID值。将托盘ID值列表用圆括号括起来。对于控制器托盘的预定义标识符不在有效托盘位置值范围内的存储阵列、请使用`controller`值。

|===


== 注释：

此命令将按托盘ID在`tray Pos址`列表中的位置定义托盘在存储阵列中的位置。例如、如果您的控制器托盘的ID设置为84、而驱动器托盘的ID设置为1、12、 和50、`托架安装`顺序(`84 1 12 50`)将控制器托盘置于第一个位置、驱动器托盘1置于第二个位置、驱动器托盘12置于第三个位置、驱动器托盘50置于第四个位置。`托架安装`顺序(`1 84 50 12`)将控制器托盘置于第二个位置、驱动器托盘1置于第一个位置、驱动器托盘50置于第三个位置、驱动器托盘12置于第四个位置。

[NOTE]
====
您必须将存储阵列中的所有托盘都包含在由`arrays Posé s`参数定义的列表中。如果列表中的托盘数与存储阵列中的托盘总数不匹配、则会显示一条错误消息。

====
[NOTE]
====
管理软件可直观地将第一个位置显示在顶部、而将其他位置显示在下方、最后一个位置显示在底部。

====


== 最低固件级别

6.10

对于6.14和6.16、`controller`不是有效值。
