---
permalink: commands-a-z/set-snapgroup-enableschedule.html 
sidebar: sidebar 
keywords: set, snapshot, group, schedule 
summary: set snapGroup enableSchedule命令用于定义为快照组创建快照映像的计划。 
---
= 设置快照组计划 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set snapGroup enableSchedule`命令可定义为快照组创建快照映像的计划。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 语法

[source, cli, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
enableSchedule=(TRUE | FALSE)
schedule (immediate | snapshotSchedule)
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`snapGroup`
 a| 
要为其设置属性的快照组的名称。将快照组名称用双引号("")括在方括号([])内。



 a| 
`enableSchedule`
 a| 
使用此参数可以启用或禁用计划快照操作的功能。要启用快照计划、请将此参数设置为`true`。要关闭快照计划、请将此参数设置为`false`。

|===


== 注释：

您可以对名称使用字母数字字符、下划线(_)、连字符(-)和井号(#)的任意组合。名称最多可以包含30个字符。

使用`enableSchedule`参数和`schedule`参数、您可以计划为快照组创建快照映像。使用这些参数、您可以计划每日、每周或每月(按天或日期)创建快照。`enableSchedule`参数用于启用或禁用快照计划功能。启用计划时、您可以使用`schedule`参数来定义快照的发生时间。

以下列表说明了如何使用`schedule`参数的选项：

* `immediate`—输入命令后、系统将创建快照映像、并开始写入时复制操作。
* `sTartDate`—要创建快照映像并执行写时复制操作的特定日期。输入日期的格式为`MM：DD：YY`。如果不提供开始日期、则会使用当前日期。例如、此选项为`startDate=06：27：11`。
* `scheduleDay`—一周中要创建快照映像并执行写时复制操作的某一天。您可以输入以下值：`monday`、`星期二`、`Wedday`、`Thurday`、`Fri`、 `saturday`、`sunday`和`all`。此选项的一个示例是`scheduleDay=Wedday`。
* `sTartTime`—一天中要创建快照映像并开始执行写时复制操作的时间。输入时间的格式为`HH：MM`、其中`HH`是小时、`MM`是小时后的分钟。使用24小时制时钟。例如、下午2：00为14：00。此选项的一个示例是`* StartTime=14：27*`。
* `scheduleInterval`—在两次写时复制操作之间、您希望至少有一段时间(以分钟为单位)。您可以创建一个计划、在此计划中、由于复制操作的持续时间、您会执行重叠的写入时复制操作。您可以使用此选项确保在两次写入时复制操作之间有时间。`scheduleInterval`选项的最大值为1440分钟。此选项的一个示例是`* scheduleInterval=180*`。
* `endDate`—要停止创建快照映像并结束写时复制操作的特定日期。输入日期的格式为`MM：DD：YY`。例如、此选项为`* endDate=11：26：11*`。
* `noEndDate`—如果不希望结束计划的写时复制操作、请使用此选项如果您稍后决定结束写时复制操作、则必须重新输入`set snapGroup`命令并指定结束日期。
* `timesPerDay`—您希望计划在一天内运行的次数。此选项的一个示例是`timesPerDae=4`。
* `timezone`—使用此参数可定义存储阵列运行所在的时区。您可以通过以下两种方式之一定义时区：
+
** `GMT±HH：MM`-与GMT的时区偏移。以小时和分钟为单位输入偏移量。例如、GMT-06：00是美国的中央时区。
** `文本字符串`—标准时区文本字符串。例如："美洲/芝加哥"或"澳大利亚/布里斯班"。时区文本字符串区分大小写。如果输入的文本字符串不正确、则会使用GMT时间。将文本字符串用双引号引起来。




用于定义计划的代码串类似于以下示例：

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
如果您还使用`scheduleInterval`选项、则固件会通过选择两个选项中的最低值在`timedPerDay`选项和`scheduleInterval`选项之间进行选择。固件会将1440除以您设置的`scheduleInterval`选项值、从而计算`scheduleInterval`选项的整数值。例如、1440/180 = 8。然后、固件会将`timedPerDay`整型值与计算得出的`scheduleInterval`整型值进行比较、并使用较小的值。

要删除计划、请使用`delete volume`命令和`sschedule`参数。带有`sschedule`参数的`delete volume`命令仅删除计划、而不删除快照卷。



== 最低固件级别

7.83.

7.86添加了`scheduleDate`选项和`month`选项。
