---
permalink: commands-a-z/set-event-alert.html 
sidebar: sidebar 
keywords: set, event, alert, filter 
summary: set event alert命令可通过禁用或启用与特定可更改事件相关的通知来管理警报事件通知。要阻止有关特定可更改事件的通知、请将其阻止。要启用有关特定可更改事件的通知、请取消阻止该事件。 
---
= 设置事件警报筛选
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`set event alert`命令可通过禁用或启用与特定可处理事件相关的通知来管理警报事件通知。为了防止收到有关特定可更改事件的通知、您需要对其进行_block_。要启用有关特定可更改事件的通知、请取消阻止_它。



== 支持的阵列

此命令仅适用于E2700和E5600存储阵列。



== 环境

[NOTE]
====
此命令是一个smcli命令、而不是一个脚本命令。您必须从命令行运行此命令。您不能从存储管理软件中的脚本编辑器运行此命令

====


== 环境

定义存储阵列时、您可以配置警报并定义事件警报的管理方式。如果您已将存储阵列配置为发送警报、则在发生可更改的事件时、系统会向指定的收件人发送通知。此通知可以是以下一种或所有类型：

* email
* 系统日志
* SNMP陷阱通知


set event alert命令行界面命令可用于单个存储阵列。在存储阵列上运行命令时、只有该存储阵列受命令的影响。未对其运行CLI命令的其他存储阵列具有默认行为。

[NOTE]
====
阻止事件警报不会阻止将事件发布到系统事件日志中。所有事件都会继续发布到事件日志中。

====
[NOTE]
====
不能使用此命令将不可加列的事件设置为可加列的事件。

====


== 用于阻止事件警报的语法

[listing, subs="+macros"]
----
set blockEventAlert pass:quotes[_eventType_]
----


== 取消阻止事件警报的语法

[listing, subs="+macros"]
----
set unBlockEventAlert pass:quotes[_eventType_]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`_eventType_`
 a| 
此参数是事件的整数值。以十六进制格式输入事件值、例如0x280D。十六进制值始终以* 0x*开头、以表示它采用十六进制格式。如果不使用0x、则在应用block或取消阻止命令之前、该值将被解释为十进制值并转换为十六进制值。这可能发生原因 会阻止或取消阻止不正确的事件。

如果输入的事件无效、则会显示一个错误。

|===


== 最低固件级别

8.10
