---
permalink: commands-a-z/set-iscsiinitiator.html 
sidebar: sidebar 
keywords: set, iscsi, initiator 
summary: set iscsiInitiator命令用于设置iSCSI启动程序的属性。 
---
= 设置 iSCSI 启动器 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`set iscsiInitiator`命令可设置iSCSI启动程序的属性。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。

[NOTE]
====
此命令已弃用、并替换为 xref:set-initiator.adoc[设置启动程序] 命令：

====


== 语法

[source, cli, subs="+macros"]
----
set iscsiInitiator (pass:quotes[["_initiatorUserLabel_"]] | <"_iscsiInitiatorName_">)
(userLabel=pass:quotes["_newName_"] |
host=pass:quotes["_newHostName_"] |
chapSecret=pass:quotes["_newSecurityKey_"])
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`initiatorUserLabel`
 a| 
要为其设置属性的iSCSI启动程序的iSCSI启动程序用户标签。将iSCSI启动程序用户标签用双引号("")括在方括号([])内。

[NOTE]
====
使用主机端口所连接的主机名开始启动程序用户标签。由于主机上可能有多个主机端口标识符、因此请为主机端口ID使用唯一后缀。如果主机名`ICTM1590S02H1`、则启动程序标签显示如下：

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`iscsiInitiatorName`
 a| 
要为其设置属性的启动程序的名称。将`iscsiInitiatorName`用双引号("")括在尖括号(<>)内。

[NOTE]
====
`iscsiInitiatorName`是iSCSI限定名称(iqn)。例如：

====
[listing]
----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----


 a| 
`用户标签`
 a| 
要用于iSCSI启动程序的新用户标签。将新用户标签用双引号("")括起来。

[NOTE]
====
最佳做法是、在启动程序用户标签开头使用主机端口所连接的主机名。由于主机上可能有多个主机端口标识符、因此请为主机端口ID使用唯一后缀。如果主机名是`ICTM1590S02H1`、则会显示启动程序用户标签的示例：

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`主机`
 a| 
主机端口连接到的新主机的名称。将主机名用双引号("")括起来。示例如下：

[listing]
----
["ICTM1590S02H2"]
----


 a| 
`chapSecret`
 a| 
要用于对对等连接进行身份验证的安全密钥。将安全密钥用双引号("")括起来。

|===


== 注释：

您可以对名称使用字母数字字符、连字符和下划线的任意组合。名称最多可以包含30个字符。

质询握手身份验证协议(CHAP)是一种对连接对等方进行身份验证的协议。CHAP基于共享_secret_的对等方。机密是一种类似于密码的安全密钥。

使用`chapSecret`参数为需要相互身份验证的启动程序设置安全密钥。CHAP密钥必须介于12到57个字符之间。此表列出了有效字符。

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
空间
 a| 
！
 a| 
"
 a| 
#
 a| 
美元
 a| 
%
 a| 
和
 a| 
'
 a| 
（
 a| 
）
 a| 
*
 a| 



 a| 
，
 a| 
-
 a| 
。
 a| 
/
 a| 
0
 a| 
1.
 a| 
2.
 a| 
3.
 a| 
4.
 a| 
5.
 a| 
6.
 a| 
7.



 a| 
8.
 a| 
9
 a| 
：
 a| 
；
 a| 
<
 a| 
=
 a| 
>
 a| 
？
 a| 
@
 a| 
答
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
g
 a| 
H
 a| 
I
 a| 
J
 a| 
k
 a| 
L
 a| 
M
 a| 
不包括
 a| 
O



 a| 
P
 a| 
问
 a| 
r
 a| 
S
 a| 
电话
 a| 
u
 a| 
五
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
答
 a| 
B
 a| 
C
 a| 
D
 a| 
E
 a| 
F
 a| 
g



 a| 
H
 a| 
I
 a| 
J
 a| 
k
 a| 
L
 a| 
M
 a| 
不包括
 a| 
O
 a| 
P
 a| 
问
 a| 
r
 a| 
S



 a| 
电话
 a| 
u
 a| 
五
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
｛
 a| 
我们可以为您提供
 a| 
｝
 a| 
~
 a| 

|===


== 最低固件级别

7.10.

8.41此命令已弃用。
