---
permalink: commands-a-z/show-storagearray-autoconfiguration.html 
sidebar: sidebar 
keywords: show, storage, array, auto, configuration 
summary: show storageArray autosconfiguration命令显示了运行autoConfigure storageArray命令时存储阵列创建的默认自动配置。 
---
= 显示存储阵列自动配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`show storageArray autosconfiguration`命令显示了运行`autosConfigure storageArray`命令时存储阵列创建的默认自动配置。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员或存储监控角色。



== 环境

如果要确定存储阵列是否支持特定属性、请在运行此命令时输入属性的参数。您无需为此命令输入任何参数即可返回配置信息。



== 语法

[source, cli, subs="+macros"]
----
show storageArray autoConfiguration
[driveType=(SAS | NVMe4K)
driveMediaType=(HDD | SSD | unknown | allMedia)
raidLevel=(0 | 1 | 3 | 5 | 6)
pass:quotes[volumeGroupWidth=_numberOfDrives_]
pass:quotes[volumeGroupCount=_numberOfVolumeGroups_]
pass:quotes[volumesPerGroupCount=_numberOfVolumesPerGroup_]
pass:quotes[hotSpareCount=_numberOfHotspares_]
pass:quotes[segmentSize=_segmentSizeValue_]
cacheReadPrefetch=(TRUE | FALSE)
securityType=(none | capable | enabled)
secureDrives=(fips | fde)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`d驱动器类型`
 a| 
要用于存储阵列的驱动器类型。

如果存储阵列中只有一种类型的驱动器、则不需要`driveType`参数。如果存储阵列中有多种类型的驱动器、则必须使用此参数。

有效驱动器类型为：

* `s作为`
* `NVMe4K`




 a| 
`driveMediaType`
 a| 
要用于镜像存储库卷组的驱动器介质类型。有效的驱动器介质包括：

* `HDD`—如果驱动器托盘中有硬盘驱动器、请使用此选项
* `sSD`—如果驱动器托盘中有固态驱动器、请使用此选项
* `unknown`—如果您不确定驱动器托盘中的驱动器介质类型、请使用
* `allMedia`—如果要使用驱动器托盘中的所有类型的驱动器介质、请使用此选项


使用`repositoryDriveCount`参数时、请使用此参数。

如果存储阵列中有多种类型的驱动器介质、则必须使用此参数。



 a| 
`raidLevel`
 a| 
存储阵列中包含驱动器的卷组的RAID级别。有效RAID级别为`0`、`1`、`3`、`5`或`6`。



 a| 
`volumeGroupWidth`
 a| 
存储阵列中卷组中的驱动器数量、具体取决于驱动器的容量。使用整数值。



 a| 
`volumeGroupCount`
 a| 
存储阵列中的卷组数量。使用整数值。



 a| 
`volumesPerGroupCount`
 a| 
每个卷组的容量相等的卷数。使用整数值。



 a| 
`热空间计数`
 a| 
存储阵列中所需的热备用磁盘数。使用整数值。



 a| 
`segmentSize`
 a| 
在将数据写入下一个驱动器之前、控制器在卷中的单个驱动器上写入的数据量(以KB为单位)。有效值为`8`、`16`、`32`、`64`、`128`、 `256`或`512`。



 a| 
`cachedReadPrefetch`
 a| 
用于打开或关闭缓存读取预取的设置。要关闭缓存读取预取、请将此参数设置为`false`。要启用缓存读取预取、请将此参数设置为`true`。



 a| 
`securityType`
 a| 
用于指定创建卷组和所有关联卷时的安全级别的设置。这些设置有效：

* `none`—卷组和卷不安全。
* `capable`—卷组和卷可以设置安全设置、但尚未启用安全性。
* `enabled`—卷组和卷已启用安全性。




 a| 
`secureDrives`
 a| 
要在卷组中使用的安全驱动器的类型。这些设置有效：

* `FIPS`—仅使用FIPS兼容驱动器。
* `FDE`—使用FDE兼容的驱动器。


[NOTE]
====
请将此参数与`securityType`参数结合使用。如果为`securityType`参数指定`none`、则会忽略`secureDrives`参数的值、因为非安全卷组不需要指定安全驱动器类型。

====
|===


== 注释：

如果未指定任何属性、则此命令将为每种驱动器类型返回RAID级别5候选项。如果RAID级别5候选项不可用、则此命令将返回RAID级别6、RAID级别3、RAID级别1或RAID级别0的候选项。指定自动配置属性时、控制器会验证固件是否支持这些属性。



== 驱动器和卷组

卷组是一组驱动器、这些驱动器由存储阵列中的控制器逻辑分组在一起。卷组中的驱动器数量是RAID级别和控制器固件的限制。创建卷组时、请遵循以下准则：

* 从固件版本7.10开始、您可以创建一个空卷组、以便预留容量供日后使用。
* 不能在一个卷组中混用SAS和光纤通道等驱动器类型。
* 卷组中的最大驱动器数取决于以下条件：
+
** 控制器的类型
** RAID级别


* RAID级别包括：0、1、10、3、5、 和6。
+
** 在CDE3992或CDE3994存储阵列中、RAID级别为0的卷组和RAID级别为10的卷组最多可以包含112个驱动器。
** 在CE6998存储阵列中、RAID级别为0的卷组和RAID级别为10的卷组最多可以包含224个驱动器。
** RAID级别为3、RAID级别为5或RAID级别为6的卷组中的驱动器不能超过30个。
** RAID级别为6的卷组必须至少有五个驱动器。
** 如果RAID级别为1的卷组具有四个或更多驱动器、则存储管理软件会自动将该卷组转换为RAID级别10、即RAID级别1 + RAID级别0。


* 如果卷组包含具有不同容量的驱动器、则卷组的总容量将基于容量最小的驱动器。
* 要启用托盘/抽盒丢失保护、请参见下表了解其他标准：


[cols="3*"]
|===
| 级别 | 托盘丢失保护标准 | 所需的最小托盘数 


 a| 
`d磁盘池`
 a| 
磁盘池在一个托盘中包含的驱动器不超过两个
 a| 
6.



 a| 
`RAID 6`
 a| 
卷组在一个托盘中包含的驱动器不超过两个
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的托盘中
 a| 
3.



 a| 
`RAID 1`
 a| 
RAID 1对中的每个驱动器都必须位于一个单独的托盘中
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现托盘丢失保护。
 a| 
不适用

|===
[cols="3*"]
|===
| 级别 | 抽盒丢失保护的标准 | 所需的最小抽盒数量 


 a| 
`d磁盘池`
 a| 
池中包含所有五个抽盒中的驱动器、每个抽盒中的驱动器数量相等。如果磁盘池包含15、20、25、30、35、 40、45、50、55或60个驱动器。
 a| 
5.



 a| 
`RAID 6`
 a| 
卷组在一个抽屉中包含的驱动器不超过两个。
 a| 
3.



 a| 
`RAID 3`或`RAID 5`
 a| 
卷组中的每个驱动器都位于一个单独的抽盒中。
 a| 
3.



 a| 
`RAID 1`
 a| 
镜像对中的每个驱动器都必须位于一个单独的抽盒中。
 a| 
2.



 a| 
`RAID 0`
 a| 
无法实现抽盒丢失保护。
 a| 
不适用

|===


== 热备件

对于卷组、保护数据的一个重要策略是将存储阵列中的可用驱动器分配为热备用驱动器。热备用磁盘是指不包含任何数据的驱动器、在RAID 1、RAID 3、RAID 5或RAID 6卷组中的驱动器发生故障时、该驱动器在存储阵列中充当备用磁盘。热备用磁盘会为存储阵列添加另一个冗余级别。

通常、热备用驱动器的容量必须等于或大于其所保护驱动器上的已用容量。热备用驱动器必须与所保护的驱动器具有相同的介质类型、相同的接口类型和容量。

如果存储阵列中的某个驱动器发生故障、则热备用磁盘通常会自动替换为故障驱动器、而无需您的干预。如果在驱动器发生故障时有热备用磁盘可用、则控制器会使用冗余数据奇偶校验将数据重建到热备用磁盘上。数据清空支持还允许在软件将驱动器标记为"故障"之前将数据复制到热备用磁盘。

物理更换故障驱动器后、您可以使用以下任一选项还原数据：

更换故障驱动器后、热备用磁盘中的数据将复制回替代驱动器。此操作称为回写。

如果将热备用驱动器指定为卷组的永久成员、则不需要执行回写操作。

卷组的托盘丢失保护和抽盒丢失保护是否可用取决于卷组中驱动器的位置。由于驱动器发生故障以及热备用驱动器的位置、可能会丢失托盘丢失保护和抽盒丢失保护。要确保托盘丢失保护和抽盒丢失保护不受影响、您必须更换故障驱动器以启动回写过程。

存储阵列会自动选择支持数据保证(Data Assurance、DA)的驱动器、以便为启用了DA的卷提供热备用支持。

确保存储阵列中有支持DA的驱动器、用于为启用了DA的卷提供热备用支持。有关支持DA的驱动器的详细信息、请参阅数据保证功能。

支持安全(FIPS和FDE)的驱动器可用作支持安全和不支持安全的驱动器的热备用磁盘。不支持安全的驱动器可以为其他不支持安全的驱动器提供支持、如果卷组未启用安全保护、则可以为支持安全的驱动器提供支持。FIPS卷组只能将FIPS驱动器用作热备用磁盘；但是、您可以将FIPS热备用磁盘用于不支持安全、支持安全和启用安全的卷组。

如果您没有热备用磁盘、则仍可在存储阵列运行期间更换故障驱动器。如果驱动器属于RAID 1、RAID 3、RAID 5或RAID 6卷组、则控制器会使用冗余数据奇偶校验自动将数据重建到替代驱动器上。此操作称为重建。



== 区块大小

区块大小决定了在将数据写入下一个驱动器之前控制器在卷中的单个驱动器上写入的数据块数。每个数据块存储512字节的数据。数据块是最小的存储单元。分段的大小决定了其包含的数据块数。例如、一个8 KB区块可容纳16个数据块。64 KB区块可容纳128个数据块。

为区块大小输入值时、系统会对照控制器在运行时提供的受支持值来检查该值。如果您输入的值无效、则控制器将返回有效值列表。使用单个驱动器处理单个请求会使其他驱动器可以同时处理其他请求。如果卷所在环境中的一个用户正在传输大量数据(例如多媒体)、则在使用一个数据条带处理单个数据传输请求时、性能会最大化。(数据条带是指分段大小乘以卷组中用于数据传输的驱动器数。) 在这种情况下、同一请求会使用多个驱动器、但每个驱动器只访问一次。

为了在多用户数据库或文件系统存储环境中获得最佳性能、请设置区块大小、以最大程度地减少满足数据传输请求所需的驱动器数量。



== 缓存读取预取

缓存读取预取允许控制器将其他数据块复制到缓存中、同时控制器将主机请求的数据块从驱动器读取并复制到缓存中。此操作增加了从缓存满足未来数据请求的可能性。对于使用顺序数据传输的多媒体应用程序来说、缓存读取预取非常重要。`cachedReadPrefetch`参数的有效值为`true`或`false`。默认值为`true`。



== 安全类型

使用`securityType`参数指定存储阵列的安全设置。

要将`securityType`参数设置为`enabled`、必须先创建存储阵列安全密钥。使用`create storageArray securityKey`命令创建存储阵列安全密钥。这些命令与安全密钥相关：

* `创建storageArray securityKey`
* `导出storageArray securityKey`
* `导入storageArray securityKey`
* `set storageArray securityKey`
* `启用VolumeGroup [volumeGroupName]安全性`
* `启用diskPool [diskPoolName]安全性`




== 保护驱动器

支持安全的驱动器可以是全磁盘加密(Full Disk Encryption、FDE)驱动器、也可以是联邦信息处理标准(Federal Information Processing Standard、FIPS)驱动器。使用`secureDrives`参数指定要使用的安全驱动器类型。可以使用的值为`FIPS`和`FDE`。



== 命令示例

[listing]
----
show storageArray autoConfiguration securityType=capable secureDrives=fips;
----


== 最低固件级别

7.10增加了RAID级别6功能并消除了热备用磁盘限制。

7.50添加了`securityType`参数。

7.75添加`dataAssurance`参数。

8.25添加了`secureDrives`参数。
