---
permalink: commands-a-z/show-snapimage.html 
sidebar: sidebar 
keywords: show, snapshot, image 
summary: show snapImage命令可返回有关用户先前创建的快照映像的信息。 
---
= 显示快照映像
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`sHow SnapImage`命令可返回有关用户先前创建的快照映像的信息。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 显示特定快照映像的语法

[listing, subs="+macros"]
----
show (allSnapImages | snapImage pass:quotes[["_snapImageName_"]] |
snapImages pass:quotes[["_snapImageName1_" ... "_snapImageNamen_"]])
[summary]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`所有SnapImages`
 a| 
用于返回有关存储阵列中所有快照映像的信息的参数。



 a| 
`snapImage`
 a| 
要检索其信息的快照映像的名称。快照映像的名称由两部分组成：

* 快照组的名称
* 快照组中快照映像的标识符


快照映像的标识符可以是以下项之一：

* 一个整数值、是快照组中快照的序列号。
* `latest`—要显示在快照组中创建的最新快照映像、请使用此选项。
* `oldest`—如果要显示在快照组中创建的最早快照映像、请使用此选项。


将快照映像名称用双引号("")括在方括号([])内。



 a| 
`snapImages`
 a| 
要检索其信息的多个快照映像的名称。使用以下规则输入快照映像的名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`summary`
 a| 
此参数将返回有关快照映像的简明信息列表。

|===


== 注释：

快照映像的名称包含两个部分、并用冒号(：)分隔：

* 快照组的标识符
* 快照映像的标识符


例如、如果要在名为snapGroup1的快照组中显示Snapshot映像12345、则应使用以下命令：

[listing]
----
show snapImage ["snapGroup1:12345"];
----
要显示名为snapGroup1的快照组中的最新快照映像、应使用以下命令：

[listing]
----
show snapImage ["snapGroup1:newest"];
----
要显示名称为snapGroup1、snapGroup2和snapGroup3的多个快照一致性组中的快照映像、应使用以下命令：

[listing]
----
show snapImages ["snapGroup1:12345 snapGroup2:newest snapGroup3:oldest"];
----


== 最低固件级别

7.83.
