---
permalink: commands-a-z/show-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: show, ssd, cache, statistics 
summary: show ssdCache命令可显示有关SSD缓存使用情况的数据。 
---
= 显示 SSD 缓存统计信息 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`show ssdCache`命令可显示有关SSD缓存使用情况的数据。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有支持管理员角色。



== 语法

[source, cli, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`ssdCache`
 a| 
要检索其信息的SSD缓存的名称。将SSD缓存名称括在方括号([])中。如果SSD缓存名称包含特殊字符或数字、则必须将SSD缓存名称用双引号("")括在方括号内。



 a| 
`ssdCacheTM统计信息`
 a| 
`show ssdCache`命令的一个可选参数、用于指示您要检索缓存统计信息。



 a| 
`控制器`
 a| 
每个控制器都会为其所拥有的卷存储SSD缓存元数据。因此、SSD缓存统计信息会按控制器进行维护和显示。有效的控制器标识符为`a`、`b`或`both`、其中`a`是插槽A中的控制器、`b`是插槽B中的控制器、`两个`都是两个控制器。将控制器标识符括在方括号()中。如果不指定控制器、则默认值为`both`。



 a| 
`文件`
 a| 
要将SSD缓存统计信息保存到的文件路径和文件名。将统计信息保存到文件时、可以使用其他统计信息。

将文件名用双引号("")括起来。例如：

`file="C：\Program Files\CLI\logssdcachestats.csv"`。

您可以使用任何文件名、但必须使用`.csv`扩展名。

|===


== 注释：

屏幕上将显示以下统计信息：

* *读取*—启用了SSD缓存的卷的主机读取总数。
+
比较读取与写入之间的关系。读取值必须大于写入值、才能有效地执行SSD缓存操作。读取与写入的比率越大、缓存的运行就越好。

* *写入*-主机写入启用了SSD缓存的卷的总数。
* *缓存命中*—缓存命中数的计数。
* *缓存命中率(%)*—源自缓存命中/总读取。
+
要实现有效的SSD缓存操作、缓存命中百分比应大于50%。少量数字可能表示以下几点：

+
** 读取与写入的比率太小。
** 不会重复读取。
** 缓存容量太小。
+
[NOTE]
====
为了帮助确定理想的SSD缓存容量、您可以使用`sStart ssdCache [ssdCacheName] performanceModeling`命令运行性能建模工具。

====


* *缓存分配量(%)*—分配的SSD缓存存存储容量、以此控制器可用的SSD缓存存储的百分比表示。源自已分配的字节/可用字节。
+
缓存分配百分比通常显示为100%。如果此数字小于100%、则表示缓存尚未预热或SSD缓存容量大于所访问的所有数据。在后一种情况下、SSD缓存容量越小、性能也就越高。请注意、这并不表示缓存的数据已放置到SSD缓存中、只是在将数据放置到SSD缓存中之前的准备步骤。

* *缓存利用率(%)*—包含已启用卷中的数据的SSD缓存存储容量、以分配的SSD缓存存储百分比表示。此值表示SSD缓存的利用率或密度。源自用户数据字节/已分配字节。
+
缓存利用率百分比通常低于100%、可能要低得多。此数字显示已填充缓存数据的SSD缓存容量百分比。此数字低于100%的原因是、SSD缓存的每个分配单元(SSD缓存缓存块)都划分为称为子块的较小单元、这些子块在一定程度上是独立填充的。数字越高通常越好、但即使数字越小、性能也会显著提高。



将数据保存到文件时会包括以下附加统计信息：

* *读取块*-主机读取中的块数。
* *写入块*-主机写入中的块数。
* *完整命中块*-块缓存命中数。
+
完整命中块表示已从SSD缓存中完全读取的块数。SSD缓存只会对完全缓存命中的操作的性能产生影响。

* *部分命中*—至少有一个块(而不是所有块)位于SSD缓存中的主机读取次数。这是一个SSD缓存*未命中*、在该缓存中可从基础卷满足读取要求。
+
部分缓存命中和部分缓存命中块是由于在SSD缓存中仅包含一部分数据的操作而导致的。在这种情况下、操作必须从缓存的HDD卷中检索数据。SSD缓存不会对这种类型的命中带来任何性能优势。如果部分缓存命中块数高于完整缓存命中块数、则不同的I/O特征类型(文件系统、数据库或Web服务器)可能会提高性能。

* *部分命中-块*-部分命中中的块数。
+
部分缓存命中和部分缓存命中块是由于在SSD缓存中仅包含一部分数据的操作而导致的。在这种情况下、操作必须从缓存的HDD卷中检索数据。SSD缓存不会对这种类型的命中带来任何性能优势。如果部分缓存命中块数高于完整缓存命中块数、则不同的I/O特征类型(文件系统、数据库或Web服务器)可能会提高性能。

* *未命中*- SSD缓存中没有块的主机读取次数。这是SSD缓存未命中情况、因为已从基础卷中完成读取。
* *未命中-块*-未命中的块数。
* *填充操作(主机读取)*-将数据从基础卷复制到SSD缓存的主机读取次数。
* *填充操作(主机读取)-块*-填充操作中的块数(主机读取)。
* *填充操作(主机写入)*-将数据从基础卷复制到SSD缓存的主机写入数。
+
对于因写入I/O操作而未填充缓存的缓存配置设置、填充操作(主机写入)计数可能为零。

* *填充操作(主机写入)-块*-填充操作中的块数(主机写入)。
* *失效操作*-数据从SSD缓存中失效/删除的次数。对于每个主机写入请求、每个具有强制单元访问(FUA)的主机读取请求、每个验证请求以及某些其他情况、都会执行缓存失效操作。
* *回收操作*- SSD缓存块重新用于另一个基础卷和/或不同LBA范围的次数。
+
为了有效地执行缓存操作、与读取和写入操作的总数相比、回收的数量要少一些、这一点非常重要。如果回收操作的数量接近读取和写入的总数、则SSD缓存将达到巨大的速度。需要增加缓存容量或工作负载不适合与SSD缓存一起使用。

* *可用字节数*—SSD缓存中可供此控制器使用的字节数。
+
可用字节数、已分配字节数和用户数据字节数用于计算缓存分配%和缓存利用率%。

* *已分配字节*—此控制器从SSD缓存分配的字节数。从SSD缓存分配的字节数可能为空、或者可能包含基础卷的数据。
+
可用字节数、已分配字节数和用户数据字节数用于计算缓存分配%和缓存利用率%。

* *用户数据字节*- SSD缓存中包含基础卷数据的已分配字节数。
+
可用字节数、已分配字节数和用户数据字节数用于计算缓存分配%和缓存利用率%。





== 最低固件级别

7.84.接受采取后续行动

11.80增加了EF600和EF300阵列支持
