---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: show allDrives命令可返回有关存储阵列中驱动器的信息。 
---
= 显示驱动器 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`show allDrives`命令可返回有关存储阵列中驱动器的信息。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

对于存储阵列中的每个驱动器、此命令将返回以下信息：

* 驱动器总数
* 驱动器的类型(SAS或NVMe4K)
* 有关基本驱动器的信息：
+
** 托盘位置和插槽位置
** 状态
** 容量
** 数据传输速率
** 产品ID
** 固件级别


* 有关SSD驱动器使用寿命的信息(如果阵列不包含SSD驱动器、则不会显示此信息)：
+
** 平均擦除计数。
** 剩余的备用块。
** 已用持久性百分比(11.41版本中的新增功能)。使用的持久性百分比是迄今为止写入SSD驱动器的数据量除以驱动器的理论总写入限制。


* 有关驱动器通道的信息：
+
** 托盘位置和插槽位置
** 首选通道
** 冗余通道


* 热备用磁盘覆盖范围
* 每个驱动器的详细信息
+
[NOTE]
====
NVMe驱动器的制造日期信息不可用。

====




== 语法

[source, cli, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`所有驱动器`
 a| 
用于返回有关存储阵列中所有驱动器的信息的设置。



 a| 
`driveMediaType`
 a| 
要检索其信息的驱动器介质类型。以下值是有效的驱动器介质类型：

* `HDD`—如果驱动器托盘中有硬盘驱动器、请使用此选项
* `sSD`—如果驱动器托盘中有固态驱动器、请使用此选项
* `unknown`—如果您不确定驱动器托盘中的驱动器介质类型、请使用此选项
* `allMedia`—如果要使用驱动器托盘中的所有类型的驱动器介质、请使用此选项




 a| 
`d驱动器类型`
 a| 
要检索其信息的驱动器类型。您不能混用驱动器类型。

有效驱动器类型为：

* `s作为`
* `NVMe4K`


如果未指定驱动器类型、则此命令将默认为任何类型。



 a| 
`d`驱动器`或`d驱动器
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。



 a| 
`summary`
 a| 
用于返回指定驱动器的状态、容量、数据传输速率、产品ID和固件版本的设置。

|===


== 注释：

要确定有关存储阵列中所有驱动器的类型和位置的信息、请使用`allDrives`参数。

要确定有关存储阵列中SAS驱动器的信息、请使用`driveType`参数。

要确定特定位置的驱动器类型、请使用`drive`参数、然后输入驱动器的托盘ID和插槽ID。

`d驱动器`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 最低固件级别

5.43

7.60会添加`drawerID`用户输入和`driveMediaType`参数。

8.41为E2800、E5700或EF570系统中的SSD驱动器添加了使用寿命报告信息、以使用寿命百分比的形式显示。
