---
permalink: commands-a-z/start-cgsnapimage-rollback.html 
sidebar: sidebar 
keywords: start, consistency, group, snapshot, rollback 
summary: start cgSnapImage rollback命令可对快照一致性组中的成员基础卷启动回滚操作。 
---
= 启动一致性组快照回滚
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
`sstart cgSnapImage rollback`命令可对快照一致性组中的成员基础卷启动回滚操作。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800、E5700、 EF600和EF300阵列、前提是安装了所有SMcli软件包。



== 角色

要在E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

基础卷的内容会立即更改、以与一致性组快照卷的时间点内容匹配。成功完成回滚操作后、基础卷将立即可用于读/写请求。

与一致性组快照卷关联的存储库卷将继续跟踪在回滚操作完成后基础卷与一致性组快照卷之间发生的任何新更改。

要停止对成员基础卷执行回滚操作、请使用`stop cgSnapImage rollback`命令。



== 语法

[listing, subs="+macros"]
----
start cgSnapImage pass:quotes[["_snapCGID:imageID_"]] rollback
memberVolumeSet pass:quotes[("_memberVolumeName1_" ... "_memberVolumeNameN_")]
----


== 参数

[cols="2*"]
|===
| 参数 | Description 


 a| 
`cgSnapImage`
 a| 
要启动回滚操作的一致性组快照映像的名称。快照映像的名称由两部分组成：

* 快照组的名称
* 快照组中快照映像的标识符。


快照映像的标识符可以是以下项之一：

* 一个整数值、是快照组中快照的序列号。
* `latest`—要显示在快照组中创建的最新快照映像、请使用此选项。
* `oldest`—如果要显示在快照组中创建的最早快照映像、请使用此选项。


将快照映像名称用双引号("")括在方括号([])内。



 a| 
`memberVolumeSet`
 a| 
要回滚的一致性组中的一个或多个成员基础卷的名称。将每个成员基础卷名称用双引号("")括在圆括号内。

您可以输入多个卷名称。将所有卷名称括在一组方括号([])中。将每个卷名称用双引号("")括起来。使用空格分隔每个卷名称。

如果未使用`memberVolumeSet`参数、则回滚过程将适用场景 一致性组的所有成员卷。

|===


== 注释：

快照映像的名称包含两个部分、并用冒号(：)分隔：

* 快照组的标识符
* 快照映像的标识符


例如、如果要对名为CG1的整个一致性组中的最新快照映像启动回滚操作、则应使用以下命令：

[listing]
----
start cgSnapImage ["CG1:newest"] rollback;
----
要对名为CG2的一致性组中的基础卷成员memVol1、memVol2和memVol3的Snapshot映像12345启动回滚操作、您应使用以下命令：

[listing]
----
start cgSnapImage ["CG2:12345"] rollback memberVolumeset=("memVol1 memVol2 memVol3");
----


== 最低固件级别

7.83.
