---
permalink: commands-a-z/start-increasevolumecapacity-volume.html 
sidebar: sidebar 
keywords: increase, capacity, volume, disk pool, volume, group 
summary: start increaseVolumeCapacity volume命令可增加磁盘池或卷组中标准卷或存储库卷的容量。 
---
= 增加磁盘池或卷组中卷的容量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`sStart increaseVolumeCapacity volume`命令可增加磁盘池或卷组中标准卷或存储库卷的容量。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

在此命令中、标准卷也称为厚卷。

[NOTE]
====
您不能使用此命令增加精简卷的容量。

====


== 语法

[source, cli, subs="+macros"]
----
pass:quotes[start increaseVolumeCapacity volume="_volumeName_"
incrementalCapacity=_volumeCapacity_]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`卷`
 a| 
要增加容量的磁盘池或卷组中的卷的名称。将卷名称用双引号("")括起来。



 a| 
`增量容量`
 a| 
用于增加卷存储大小(容量)的设置。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。默认值为`bytes`。



 a| 
`添加驱动器`
 a| 
用于向卷添加新驱动器的设置。对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。

[NOTE]
====
`addDrives`参数只能用于增加卷组的容量。参数不能用于增加磁盘池的容量。

====
|===


== 注释：

在某些情况下、`drive`参数可能会显示为命令语法的有效输入。但是、您不能在此命令中使用`drive`参数。

如果设置`incrementalCapacity`参数、则会启动一个无法停止的长时间运行操作。长时间运行的操作在后台执行、不会阻止您运行其他命令。要显示长时间运行的操作的进度、请使用`show volume actionProprogress`命令。

`addDrives`参数既支持高容量驱动器托盘、也支持低容量驱动器托盘。高容量驱动器托盘具有用于容纳驱动器的抽盒。抽盒滑出驱动器托盘、以便可以访问驱动器。低容量驱动器托盘没有抽屉。对于大容量驱动器托盘、您必须指定驱动器托盘的标识符(ID)、抽盒ID以及驱动器所在插槽的ID。对于低容量驱动器托盘、只需指定驱动器托盘的ID以及驱动器所在插槽的ID即可。对于低容量驱动器托盘、确定驱动器位置的另一种方法是指定驱动器托盘的ID、将抽盒的ID设置为`0`、并指定驱动器所在插槽的ID。



== 最低固件级别

7.83.
