---
permalink: commands-a-z/start-volume-initialize.html 
sidebar: sidebar 
keywords: initialize, thin volume 
summary: start volume initialize命令用于初始化或重新初始化精简卷。 
---
= 初始化精简卷 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`sStart volume initialize`命令可初始化或重新初始化精简卷。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

此操作取决于所使用的参数：

* 如果不使用任何可选参数、则此命令将删除精简卷上的数据。存储库卷容量不受影响。
* 此命令可与任何可选参数结合使用、用于执行发生原因 重新初始化和存储库卷操作。


[NOTE]
====
初始化精简卷会启动一个长时间运行的操作、此操作无法停止。

====


== 语法

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
pass:quotes[[existingRepositoryLabel=_existingRepositoryName_]]
pass:quotes[[diskPool=_diskPoolName_ capacity=_capacityValue_]]
[retainRepositoryMembers=(TRUE|FALSE)]
----


== 参数

[cols="2*"]
|===
| 参数 | Description 


 a| 
`卷`
 a| 
要开始初始化的卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或数字、则必须将卷名称用双引号("")括在方括号内。



 a| 
`existingRepositoryLabel`
 a| 
此参数将按指定的候选卷替换存储库卷。

* 指定的值为现有存储库卷用户标签。指定的卷必须是未使用的存储库卷、其名称必须采用正确的格式。
* 如果新指定的存储库卷位于其他磁盘池上、则精简卷将所有权更改为该池。
* 默认情况下、旧存储库卷将被删除。


如果现有存储库卷名称包含特殊字符或仅包含数字、则必须将卷名称用双引号("")括起来。



 a| 
`diskPool`
 a| 
要在其中创建具有指定容量的新存储库卷的磁盘池的名称。如果磁盘池名称包含特殊字符或仅包含数字、则必须将磁盘池名称用双引号("")括起来。

您必须将此参数与`capacity`参数结合使用、才能使用指定容量创建新的存储库卷。



 a| 
`容量`
 a| 
要为要创建的存储库卷设置的大小。大小的单位为`字节`、`KB`、`MB`、`GB`或`TB`。

最小物理容量为4 GB。

最大物理容量为257 TB。

您必须将此参数与`diskPool`参数结合使用、才能创建具有指定容量的新存储库卷。



 a| 
`re存储库成员`
 a| 
如果此参数设置为`true`、则会保留旧存储库。默认情况下、旧存储库将被删除。如果重复使用现有存储库、则会忽略此参数。

|===


== 注释：

如果未使用`volume`参数指定卷、则此命令将重置存储库中的元数据、并实际上导致精简卷在主机中显示为空。如果使用`*卷*`参数指定卷、则该卷将被新创建的卷替换、如果使用`existingRepositoryLabel`参数指定了一个卷、则该卷将被现有卷替换。如果您使用`existingRepositoryLabel`参数指定位于其他磁盘池中的现有卷、则精简卷将所有权更改为新磁盘池。

重新初始化精简卷后、精简卷的卷参数(例如虚拟容量、配额和警告阈值)将保留其先前的值。

[NOTE]
====
即时可用性格式(Immediate Availability Format、IAF)不适用于大于64 TB的卷。

====
下表列出了精简卷的容量限制。

[cols="2*"]
|===
| 容量类型 | Size 


 a| 
最小虚拟容量
 a| 
32 MB



 a| 
最大虚拟容量
 a| 
256 TB



 a| 
最小物理容量
 a| 
4 GB



 a| 
最大物理容量
 a| 
257 TB

|===
精简卷支持标准卷执行的所有操作、但以下情况除外：

* 您不能更改精简卷的区块大小。
* 您不能为精简卷启用预读取冗余检查。
* 您不能在卷副本中使用精简卷作为目标卷。
* 不能在同步镜像操作中使用精简卷。


如果要将精简卷更改为标准卷、请使用卷复制操作创建精简卷的副本。卷副本的目标始终为标准卷。



== 最低固件级别

7.83.

8.30将精简卷的最大容量增加到256 TB。
