---
permalink: commands-a-z/start-secureerase-drive.html 
sidebar: sidebar 
keywords: start, fde, secure, drive, erase 
summary: 'start secureErase drive命令会擦除一个或多个全磁盘加密(Full Disk Encryption、FDE)驱动器中的所有数据、以便可以重复使用这些数据作为FDE驱动器。' 
---
= 启动 FDE 安全驱动器擦除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用`sStart secureErase drive`命令可擦除一个或多个全磁盘加密(Full Disk Encryption、FDE)驱动器中的所有数据、以便可以将这些数据重复用作FDE驱动器。



== 支持的阵列

此命令适用于任何单个存储阵列、包括E4000、E2700、E5600、E2800、E5700、EF600和EF300阵列、前提是已安装所有SMClu软件包。



== 角色

要在E4000、E2800、E5700、EF600或EF300存储阵列上执行此命令、您必须具有安全管理员角色。



== 环境

只有当FDE驱动器不再属于安全卷组或磁盘池、或者安全密钥未知时、才运行此命令。

[NOTE]
====
要在FIPS驱动器已锁定且用于解锁的安全密钥不可用时擦除该驱动器、请使用`set drive securityID`命令。

====


== 语法

[source, cli, subs="+macros"]
----
[start secureErase (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`d`驱动器`或`d驱动器
 a| 
对于大容量驱动器托盘、请指定驱动器的托盘ID值、抽盒ID值和插槽ID值。对于低容量驱动器托盘、请指定驱动器的托盘ID值和插槽ID值。托盘ID值为`0`到`99`。抽盒ID值为`1`到`5`。

所有插槽ID最大值均为24。插槽ID值从0或1开始、具体取决于托盘型号。与E2800和E5700控制器兼容的驱动器托盘的插槽ID编号从0开始。与E2700和E5600控制器兼容的驱动器托盘的插槽ID编号从1开始。

将托盘ID值、抽盒ID值和插槽ID值括在方括号()中。

[NOTE]
====
驱动器列表不能包含存储阵列中的所有驱动器、否则命令将被拒绝。要安全擦除所有驱动器、请运行此命令两次、并在两个不同的组中指定驱动器列表。

====
|===


== 注释：

控制器固件会创建一个锁定、用于限制对FDE驱动器的访问。FDE驱动器的状态称为"安全功能"。创建安全密钥时、状态将设置为安全已启用、从而限制对存储阵列中所有FDE驱动器的访问。



== 最低固件级别

7.40
