---
permalink: commands-a-z/suspend-syncmirror-primaries.html 
sidebar: sidebar 
keywords: suspend, synchronous, mirror 
summary: suspend SyncMirror 主节点命令可暂停同步镜像操作。 
---
= 暂停同步镜像
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
使用`susPEND SyncMirror 主节点`命令可暂停同步镜像操作。



== 支持的阵列

此命令将适用场景 任意单个存储阵列、包括E2700、E5600、E2800和E5700阵列、 只要安装了所有SMcli软件包、



== 角色

要在E2800或E5700存储阵列上执行此命令、您必须具有存储管理员角色。



== 环境

[NOTE]
====
在先前版本的此命令中、功能标识符为`remoteMirror`。此功能标识符不再有效、并替换为`SyncMirror`。

====


== 语法

[listing, subs="+macros"]
----

suspend syncMirror (primary pass:quotes[[_primaryVolumeName_]]
primaries pass:quotes[[_primaryVolumeName1_ ... _primaryVolumeNameN_])]
[writeConsistency=(TRUE | FALSE)]
----


== Parameters

[cols="2*"]
|===
| 参数 | Description 


 a| 
`主卷`
 a| 
要暂停操作的主卷的名称。将卷名称括在方括号([])中。如果卷名称包含特殊字符或数字、则必须在方括号内用双引号("")将卷名称括起来。



 a| 
`主卷`
 a| 
要暂停操作的多个主卷的名称。所有卷都具有相同的属性。使用以下规则输入卷的名称：

* 请将所有名称用方括号([])括起来。
* 使用空格分隔每个名称。


如果卷名称包含特殊字符或数字、请使用以下规则输入名称：

* 请将所有名称用方括号([])括起来。
* 请将每个名称用双引号("")括起来。
* 使用空格分隔每个名称。




 a| 
`写入并发性`
 a| 
此参数用于定义此命令中标识的卷是位于写入一致性组中还是单独。对于同一写入一致性组中的卷、将此参数设置为`true`。对于单独的卷、将此参数设置为`false`。

|===


== 注释：

如果将`writeConsistency`参数设置为`true`、则卷必须位于一个或多个写入一致性组中。此命令将暂停包含卷的所有写入一致性组。例如、如果卷A、B和C位于写入一致性组中、并且它们具有远程对等项A`、B`'和C`'、则命令：

[listing]
----
suspend syncMirror volume ["A"] writeConsistency=TRUE
----
暂停A-A`、B-B`和C-C`。如果您的写入一致性组为1｛A、B、C｝、而写入一致性组为2｛D、E、F｝、则命令：

[listing]
----
suspend syncMirror volumes ["A" "D"] writeConsistency=TRUE
----
暂停两个写入一致性组。



== 最低固件级别

6.10
